In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx" , sheet_name = "loans" )
df

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
8,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
9,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
10,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
11,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
12,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
13,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
14,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
15,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
16,L009,C014,Personal Loan,587969,10.8,25,Closed,2024-10-23
17,L010,C014,Education Loan,6152922,10.0,69,Pending,2020-10-04
18,L011,C014,Business Loan,3548178,12.3,114,Pending,2022-06-07
19,L012,C006,Education Loan,1894221,13.5,205,Pending,2022-04-03
20,L013,C001,Personal Loan,1541007,13.5,71,Closed,2022-09-24
21,L014,C014,Home Loan,1588709,10.1,179,Approved,2020-04-14
22,L015,C014,Education Loan,828775,12.7,207,Closed,2024-09-21
23,L016,C011,Home Loan,739802,12.8,146,Pending,2020-03-13
24,L017,C004,Car Loan,1976576,9.9,184,Closed,2021-09-23
25,L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
26,L019,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19
27,L020,C015,Home Loan,1594460,14.9,43,Approved,2023-10-26
28,L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
29,L022,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28
30,L023,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22
31,L024,C010,Business Loan,4281181,14.7,20,Pending,2021-01-16
32,L025,C018,Personal Loan,1166796,10.7,57,Pending,2023-05-13
33,L026,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09
34,L027,C013,Personal Loan,3549884,14.8,226,Closed,2021-12-23
35,L028,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15
36,L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
37,L030,C019,Car Loan,1426135,10.1,74,Approved,2024-03-05
38,L031,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07
39,L032,C007,Education Loan,3798744,13.3,133,Closed,2024-02-20
40,L033,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30
41,L034,C010,Personal Loan,2052094,14.6,200,Closed,2024-10-20
42,L035,C006,Education Loan,4685042,10.5,79,Approved,2024-07-27
43,L036,C015,Education Loan,1543364,12.9,210,Closed,2021-07-21
44,L037,C015,Education Loan,2021420,9.1,15,Approved,2020-05-06
45,L038,C016,Business Loan,2123782,13.4,14,Approved,2024-04-01
46,L039,C017,Education Loan,1137129,11.4,36,Closed,2024-10-12
47,L040,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10
48,L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
49,L042,C014,Education Loan,1464471,16.1,34,Closed,2024-09-13
50,L043,C012,Business Loan,3546161,10.6,196,Closed,2021-09-24
51,L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
52,L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
53,L046,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28
54,L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
55,L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [6]:
df.columns

Index(['loan_id', 'customer_id', 'loan_type', 'amount', 'interest_rate',
       'tenure_months', 'status', 'start_date'],
      dtype='str')

In [9]:
df.loc[0:4]

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07

In [10]:
df1 = df[df["loan_type"] == "Home Loan"]
df1

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
10,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
12,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
21,L014,C014,Home Loan,1588709,10.1,179,Approved,2020-04-14
23,L016,C011,Home Loan,739802,12.8,146,Pending,2020-03-13
25,L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
27,L020,C015,Home Loan,1594460,14.9,43,Approved,2023-10-26
28,L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
30,L023,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22
36,L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
38,L031,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07
40,L033,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30
48,L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
51,L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
52,L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09

In [18]:
df.loc[(df.amount > 2000000) & (df.status == "Approved")].count()

loan_id          10
customer_id      10
loan_type        10
amount           10
interest_rate    10
tenure_months    10
status           10
start_date       10
dtype: int64

In [20]:
df.sort_values("interest_rate", ascending = False).head(5)

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
25,L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
28,L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
26,L019,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
11,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20

In [23]:
df[df["status"] == "Closed"][["loan_id", "amount", "status"]]

   loan_id   amount  status
0     L001  3259410  Closed
5     L006  1625677  Closed
6     L007   551378  Closed
7     L008  4709020  Closed
8     L001  3259410  Closed
13    L006  1625677  Closed
14    L007   551378  Closed
15    L008  4709020  Closed
16    L009   587969  Closed
20    L013  1541007  Closed
22    L015   828775  Closed
24    L017  1976576  Closed
25    L018  1792913  Closed
26    L019  5127881  Closed
29    L022  5359663  Closed
33    L026  5825880  Closed
34    L027  3549884  Closed
39    L032  3798744  Closed
40    L033  3157197  Closed
41    L034  2052094  Closed
43    L036  1543364  Closed
46    L039  1137129  Closed
47    L040  5864614  Closed
49    L042  1464471  Closed
50    L043  3546161  Closed

In [25]:
df["loan_type"].value_counts()

loan_type
Home Loan         16
Education Loan    15
Business Loan     12
Car Loan           8
Personal Loan      5
Name: count, dtype: int64

In [27]:
df[["amount", "interest_rate"]].mean()

amount           3.364845e+06
interest_rate    1.311250e+01
dtype: float64

In [29]:
df.groupby("loan_type")[["amount","interest_rate"]].sum()

                  amount  interest_rate
loan_type
Business Loan   39468314          155.3
Car Loan        30269459          109.6
Education Loan  52978728          198.8
Home Loan       56817047          206.2
Personal Loan    8897750           64.4

In [30]:
df.groupby("loan_type").agg({"amount": "sum", "interest_rate" : "mean"})

                  amount  interest_rate
loan_type
Business Loan   39468314      12.941667
Car Loan        30269459      13.700000
Education Loan  52978728      13.253333
Home Loan       56817047      12.887500
Personal Loan    8897750      12.880000

In [35]:
df.groupby("status").agg({"loan_type": "count"})

          loan_type
status
Approved         15
Closed           25
Pending          16

In [36]:
df.status.value_counts()

status
Closed      25
Pending     16
Approved    15
Name: count, dtype: int64

In [39]:
status_counts = df.groupby("status").agg(count = ("loan_type" , "count"))

In [40]:
status_counts

          count
status
Approved     15
Closed       25
Pending      16

In [49]:
result = df.groupby("customer_id")["loan_id"].count().sort_values(ascending = False).head(3)
result

customer_id
C004    7
C014    6
C001    5
Name: loan_id, dtype: int64

In [54]:
df.groupby("status")["tenure_months"].agg({"mean","min", "max"})

                mean  max  min
status
Approved   78.866667  179   14
Closed    119.520000  226   25
Pending   104.625000  205   20

In [56]:
df.groupby("loan_type")["amount"].agg({"mean", "min", "max"})

                        mean      max      min
loan_type
Business Loan   3.289026e+06  5359663   551378
Car Loan        3.783682e+06  5967384  1426135
Education Loan  3.531915e+06  7637483   828775
Home Loan       3.551065e+06  6574178   739802
Personal Loan   1.779550e+06  3549884   587969

In [58]:
df["start_date"].dtype

dtype('<M8[us]')

In [62]:
df["start_date"] = pd.to_datetime(df["start_date"], dayfirst = True)

In [63]:
df["start_date"].dtype

dtype('<M8[us]')

In [64]:
df["start_date"].head(1)

0   2021-11-09
Name: start_date, dtype: datetime64[us]

In [65]:
df["int_amount"] = df["amount"] *(df["interest_rate"]/100)

In [4]:
df[0:1]

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09

In [8]:
data = ["Car Loan" , "Education Loan"]

In [15]:
df[df["loan_type"].isin(data)].sort_values("amount").head(1)

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
22,L015,C014,Education Loan,828775,12.7,207,Closed,2024-09-21

In [17]:
df1 = df.set_index("loan_id")

In [22]:
df.filter(items = ["loan_id","status"]).head(1)

  loan_id  status
0    L001  Closed

In [28]:
df1.index

Index(['L001', 'L002', 'L003', 'L004', 'L005', 'L006', 'L007', 'L008', 'L001',
       'L002', 'L003', 'L004', 'L005', 'L006', 'L007', 'L008', 'L009', 'L010',
       'L011', 'L012', 'L013', 'L014', 'L015', 'L016', 'L017', 'L018', 'L019',
       'L020', 'L021', 'L022', 'L023', 'L024', 'L025', 'L026', 'L027', 'L028',
       'L029', 'L030', 'L031', 'L032', 'L033', 'L034', 'L035', 'L036', 'L037',
       'L038', 'L039', 'L040', 'L041', 'L042', 'L043', 'L044', 'L045', 'L046',
       'L047', 'L048'],
      dtype='str', name='loan_id')

In [30]:
df.iloc[0:10].sort_values(by = "start_date")

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
8,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
9,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06

In [31]:
# we can past a list in sort in by =[] so according to the first item the result will be sorted

In [33]:
df.rename(columns = {"interest_rate" : "int_rate", "loan_type" : "type"}, inplace= True )
df

,loan_id,customer_id,type,amount,int_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
8,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
9,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
10,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
11,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
12,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
13,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
14,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
15,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
16,L009,C014,Personal Loan,587969,10.8,25,Closed,2024-10-23
17,L010,C014,Education Loan,6152922,10.0,69,Pending,2020-10-04
18,L011,C014,Business Loan,3548178,12.3,114,Pending,2022-06-07
19,L012,C006,Education Loan,1894221,13.5,205,Pending,2022-04-03
20,L013,C001,Personal Loan,1541007,13.5,71,Closed,2022-09-24
21,L014,C014,Home Loan,1588709,10.1,179,Approved,2020-04-14
22,L015,C014,Education Loan,828775,12.7,207,Closed,2024-09-21
23,L016,C011,Home Loan,739802,12.8,146,Pending,2020-03-13
24,L017,C004,Car Loan,1976576,9.9,184,Closed,2021-09-23
25,L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
26,L019,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19
27,L020,C015,Home Loan,1594460,14.9,43,Approved,2023-10-26
28,L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
29,L022,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28
30,L023,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22
31,L024,C010,Business Loan,4281181,14.7,20,Pending,2021-01-16
32,L025,C018,Personal Loan,1166796,10.7,57,Pending,2023-05-13
33,L026,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09
34,L027,C013,Personal Loan,3549884,14.8,226,Closed,2021-12-23
35,L028,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15
36,L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
37,L030,C019,Car Loan,1426135,10.1,74,Approved,2024-03-05
38,L031,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07
39,L032,C007,Education Loan,3798744,13.3,133,Closed,2024-02-20
40,L033,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30
41,L034,C010,Personal Loan,2052094,14.6,200,Closed,2024-10-20
42,L035,C006,Education Loan,4685042,10.5,79,Approved,2024-07-27
43,L036,C015,Education Loan,1543364,12.9,210,Closed,2021-07-21
44,L037,C015,Education Loan,2021420,9.1,15,Approved,2020-05-06
45,L038,C016,Business Loan,2123782,13.4,14,Approved,2024-04-01
46,L039,C017,Education Loan,1137129,11.4,36,Closed,2024-10-12
47,L040,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10
48,L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
49,L042,C014,Education Loan,1464471,16.1,34,Closed,2024-09-13
50,L043,C012,Business Loan,3546161,10.6,196,Closed,2021-09-24
51,L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
52,L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
53,L046,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28
54,L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
55,L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [40]:
df.loc[0:15].sort_values(by = ["int_rate", "start_date"]).head(5)  # int rate is sorted

,loan_id,customer_id,type,amount,int_rate,tenure_months,status,start_date
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
12,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
14,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09

In [39]:
df.loc[0:10].sort_values(by = ["start_date" , "int_rate"]).head(5) # date is sorted

,loan_id,customer_id,type,amount,int_rate,tenure_months,status,start_date
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
10,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09

In [43]:
df.set_index("loan_id", inplace = True)
df

,customer_id,type,amount,int_rate,tenure_months,status,start_date
loan_id,,,,,,,
L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
L009,C014,Personal Loan,587969,10.8,25,Closed,2024-10-23
L010,C014,Education Loan,6152922,10.0,69,Pending,2020-10-04
L011,C014,Business Loan,3548178,12.3,114,Pending,2022-06-07
L012,C006,Education Loan,1894221,13.5,205,Pending,2022-04-03
L013,C001,Personal Loan,1541007,13.5,71,Closed,2022-09-24
L014,C014,Home Loan,1588709,10.1,179,Approved,2020-04-14
L015,C014,Education Loan,828775,12.7,207,Closed,2024-09-21
L016,C011,Home Loan,739802,12.8,146,Pending,2020-03-13
L017,C004,Car Loan,1976576,9.9,184,Closed,2021-09-23
L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
L019,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19
L020,C015,Home Loan,1594460,14.9,43,Approved,2023-10-26
L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
L022,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28
L023,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22
L024,C010,Business Loan,4281181,14.7,20,Pending,2021-01-16
L025,C018,Personal Loan,1166796,10.7,57,Pending,2023-05-13
L026,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09
L027,C013,Personal Loan,3549884,14.8,226,Closed,2021-12-23
L028,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15
L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
L030,C019,Car Loan,1426135,10.1,74,Approved,2024-03-05
L031,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07
L032,C007,Education Loan,3798744,13.3,133,Closed,2024-02-20
L033,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30
L034,C010,Personal Loan,2052094,14.6,200,Closed,2024-10-20
L035,C006,Education Loan,4685042,10.5,79,Approved,2024-07-27
L036,C015,Education Loan,1543364,12.9,210,Closed,2021-07-21
L037,C015,Education Loan,2021420,9.1,15,Approved,2020-05-06
L038,C016,Business Loan,2123782,13.4,14,Approved,2024-04-01
L039,C017,Education Loan,1137129,11.4,36,Closed,2024-10-12
L040,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10
L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
L042,C014,Education Loan,1464471,16.1,34,Closed,2024-09-13
L043,C012,Business Loan,3546161,10.6,196,Closed,2021-09-24
L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
L046,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28
L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [45]:
df.loc["L005"]     # because we set index at loan_id

,customer_id,type,amount,int_rate,tenure_months,status,start_date
loan_id,,,,,,,
L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07

In [50]:
df.iloc[5]

customer_id                     C011
type                  Education Loan
amount                       1625677
int_rate                        14.7
tenure_months                     58
status                        Closed
start_date       2021-12-07 00:00:00
Name: L006, dtype: object

In [53]:
df.sort_index(ascending = False).head(5)

,customer_id,type,amount,int_rate,tenure_months,status,start_date
loan_id,,,,,,,
L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19
L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
L046,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28
L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21

In [56]:
group = df.groupby("type")

In [57]:
group.max()

,customer_id,amount,int_rate,tenure_months,status,start_date
type,,,,,,
Business Loan,C016,5359663,15.4,196,Pending,2024-04-01
Car Loan,C019,5967384,16.3,189,Pending,2024-11-19
Education Loan,C017,7637483,16.7,210,Pending,2024-10-12
Home Loan,C015,6574178,17.6,210,Pending,2024-04-09
Personal Loan,C018,3549884,14.8,226,Pending,2024-10-23

In [64]:
df[df["amount"] >= 5359662]

,customer_id,type,amount,int_rate,tenure_months,status,start_date
loan_id,,,,,,,
L010,C014,Education Loan,6152922,10.0,69,Pending,2020-10-04
L022,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28
L026,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09
L028,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15
L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
L040,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10
L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [67]:
df[df["customer_id"] == "C016"]["amount"].values

array([2123782, 7637483])

In [77]:
df.groupby("type").min()

,customer_id,amount,int_rate,tenure_months,status,start_date
type,,,,,,
Business Loan,C001,551378,10.4,14,Approved,2021-01-16
Car Loan,C001,1426135,9.9,71,Approved,2021-03-20
Education Loan,C002,828775,9.1,15,Approved,2020-05-06
Home Loan,C001,739802,9.4,18,Approved,2020-02-07
Personal Loan,C001,587969,10.7,25,Closed,2021-12-23

In [81]:
df.groupby("type").agg({"tenure_months" :["min", "max", "sum"], "amount" :["min", "max", "sum"]})

               tenure_months              amount
                         min  max   sum      min      max       sum
type
Business Loan             14  196  1122   551378  5359663  39468314
Car Loan                  71  189  1135  1426135  5967384  30269459
Education Loan            15  210  1357   828775  7637483  52978728
Home Loan                 18  210  1652   739802  6574178  56817047
Personal Loan             25  226   579   587969  3549884   8897750

In [86]:
df.groupby(["type","status"]).agg({"amount" :["min", "max", "mean"]})

                          amount
                             min      max          mean
type           status
Business Loan  Approved  2123782  2123782  2.123782e+06
               Closed     551378  5359663  3.243180e+06
               Pending   3548178  4281181  3.799697e+06
Car Loan       Approved  1426135  3185486  2.599036e+06
               Closed    1976576  5864614  3.920595e+06
               Pending   4331889  5967384  4.877054e+06
Education Loan Approved  2021420  4685042  3.353231e+06
               Closed     828775  5825880  2.553066e+06
               Pending   1894221  7637483  5.823667e+06
Home Loan      Approved  1522769  6092884  3.170262e+06
               Closed    1792913  3157197  2.475055e+06
               Pending    739802  6574178  4.666916e+06
Personal Loan  Closed     587969  3549884  1.932738e+06
               Pending   1166796  1166796  1.166796e+06

### joins

In [88]:
df1 = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name = "Customer")
df1

,customer_id,name,city,age,phone,join_date,gender
0,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
1,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F
2,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M
3,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
4,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F
5,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
6,C007,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F
7,C008,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F
8,C009,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
9,C010,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
10,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F
11,C012,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F

In [95]:
df.merge(df1, how = "right" , on = "customer_id")

,customer_id,type,amount,int_rate,tenure_months,status,start_date,name,city,age,phone,join_date,gender
0,C001,Business Loan,551378,10.4,33,Closed,2023-03-05,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
1,C001,Business Loan,551378,10.4,33,Closed,2023-03-05,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
2,C001,Personal Loan,1541007,13.5,71,Closed,2022-09-24,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
3,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
4,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
5,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F
6,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F
7,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M
8,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M
9,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
10,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
11,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
12,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
13,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
14,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
15,C004,Car Loan,1976576,9.9,184,Closed,2021-09-23,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
16,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F
17,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F
18,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F
19,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
20,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
21,C006,Education Loan,1894221,13.5,205,Pending,2022-04-03,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
22,C006,Education Loan,4685042,10.5,79,Approved,2024-07-27,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
23,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F
24,C007,Education Loan,3798744,13.3,133,Closed,2024-02-20,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F
25,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F
26,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F
27,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
28,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
29,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
30,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
31,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
32,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
33,C010,Business Loan,4281181,14.7,20,Pending,2021-01-16,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
34,C010,Personal Loan,2052094,14.6,200,Closed,2024-10-20,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
35,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F
36,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F
37,C011,Home Loan,739802,12.8,146,Pending,2020-03-13,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F
38,C012,Business Loan,3546161,10.6,196,Closed,2021-09-24,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F

In [96]:
df_customers = pd.DataFrame({
    "customer_id": ["C001","C002","C003","C004","C005"],
    "name":        ["Alice","Bob","Carol","Dan","Eva"],
    "city":        ["Karachi","Lahore","Islamabad","Karachi","Lahore"]
})

df_loans = pd.DataFrame({
    "customer_id": ["C001","C002","C003","C006","C007"],
    "loan_type":   ["Home Loan","Car Loan","Education","Personal","Home Loan"],
    "amount":      [500000, 300000, 150000, 80000, 620000]
})

In [97]:
df = df_customers
df1 = df_loans

In [106]:
df.merge(df1 , how = "inner" , on = "customer_id")

  customer_id   name       city  loan_type  amount
0        C001  Alice    Karachi  Home Loan  500000
1        C002    Bob     Lahore   Car Loan  300000
2        C003  Carol  Islamabad  Education  150000

In [3]:
df

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
8,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
9,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
10,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
11,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
12,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
13,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
14,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
15,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08
16,L009,C014,Personal Loan,587969,10.8,25,Closed,2024-10-23
17,L010,C014,Education Loan,6152922,10.0,69,Pending,2020-10-04
18,L011,C014,Business Loan,3548178,12.3,114,Pending,2022-06-07
19,L012,C006,Education Loan,1894221,13.5,205,Pending,2022-04-03
20,L013,C001,Personal Loan,1541007,13.5,71,Closed,2022-09-24
21,L014,C014,Home Loan,1588709,10.1,179,Approved,2020-04-14
22,L015,C014,Education Loan,828775,12.7,207,Closed,2024-09-21
23,L016,C011,Home Loan,739802,12.8,146,Pending,2020-03-13
24,L017,C004,Car Loan,1976576,9.9,184,Closed,2021-09-23
25,L018,C008,Home Loan,1792913,17.6,48,Closed,2023-12-26
26,L019,C007,Education Loan,5127881,16.7,68,Closed,2020-10-19
27,L020,C015,Home Loan,1594460,14.9,43,Approved,2023-10-26
28,L021,C013,Home Loan,4476822,16.8,152,Pending,2020-08-27
29,L022,C005,Business Loan,5359663,15.4,68,Closed,2021-06-28
30,L023,C001,Home Loan,4953882,13.0,148,Approved,2022-10-22
31,L024,C010,Business Loan,4281181,14.7,20,Pending,2021-01-16
32,L025,C018,Personal Loan,1166796,10.7,57,Pending,2023-05-13
33,L026,C003,Education Loan,5825880,14.5,140,Closed,2021-07-09
34,L027,C013,Personal Loan,3549884,14.8,226,Closed,2021-12-23
35,L028,C002,Education Loan,7610042,13.5,22,Pending,2022-10-15
36,L029,C009,Home Loan,6012977,15.2,29,Pending,2024-04-03
37,L030,C019,Car Loan,1426135,10.1,74,Approved,2024-03-05
38,L031,C005,Home Loan,2241545,10.1,130,Approved,2021-07-07
39,L032,C007,Education Loan,3798744,13.3,133,Closed,2024-02-20
40,L033,C002,Home Loan,3157197,9.4,210,Closed,2022-08-30
41,L034,C010,Personal Loan,2052094,14.6,200,Closed,2024-10-20
42,L035,C006,Education Loan,4685042,10.5,79,Approved,2024-07-27
43,L036,C015,Education Loan,1543364,12.9,210,Closed,2021-07-21
44,L037,C015,Education Loan,2021420,9.1,15,Approved,2020-05-06
45,L038,C016,Business Loan,2123782,13.4,14,Approved,2024-04-01
46,L039,C017,Education Loan,1137129,11.4,36,Closed,2024-10-12
47,L040,C001,Car Loan,5864614,12.9,180,Closed,2021-09-10
48,L041,C008,Home Loan,6574178,10.6,80,Pending,2022-12-27
49,L042,C014,Education Loan,1464471,16.1,34,Closed,2024-09-13
50,L043,C012,Business Loan,3546161,10.6,196,Closed,2021-09-24
51,L044,C003,Home Loan,5530800,12.9,128,Pending,2021-04-21
52,L045,C005,Home Loan,6092884,11.6,179,Approved,2024-04-09
53,L046,C009,Business Loan,3569733,15.3,74,Pending,2023-11-28
54,L047,C016,Education Loan,7637483,15.2,23,Pending,2024-01-17
55,L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [7]:
df.rename(columns = {"loan_type" : "type","start_date" : "date"} ,inplace = True)
df.columns

Index(['loan_id', 'customer_id', 'type', 'amount', 'interest_rate',
       'tenure_months', 'status', 'date'],
      dtype='str')

In [10]:
df.loc[(df.type == "Car Loan") & (df.status == "Pending")]

,loan_id,customer_id,type,amount,interest_rate,tenure_months,status,date
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
11,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
55,L048,C015,Car Loan,5967384,12.5,177,Pending,2024-11-19

In [ ]:
df.groupby("type").agg(