In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [4]:
df= pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Kaggle\Titanic-Dataset.csv" , usecols = ['Age','Pclass','SibSp','Parch','Survived'])
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [8]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [9]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [12]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

## Applying Feature Construction

In [13]:
df["Family Size"] = df["SibSp"] + df["Parch"] +1 
df.head()

   Survived  Pclass   Age  SibSp  Parch  Family Size
0         0       3  22.0      1      0            2
1         1       1  38.0      1      0            2
2         1       3  26.0      0      0            1
3         1       1  35.0      1      0            2
4         0       3  35.0      0      0            1

In [14]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [15]:
myfunc(2)

1

In [16]:
df["Family Type"] = df["Family Size"].apply(myfunc)

In [18]:
df.sample(5)

     Survived  Pclass   Age  SibSp  Parch  Family Size  Family Type
97          1       1  23.0      0      1            2            1
228         0       2  18.0      0      0            1            0
369         1       1  24.0      0      0            1            0
484         1       1  25.0      1      0            2            1
239         0       2  33.0      0      0            1            0

In [19]:
df.drop(columns = ["SibSp" , "Family Size" , "Parch"] , inplace = True)
df.head()

   Survived  Pclass   Age  Family Type
0         0       3  22.0            1
1         1       1  38.0            1
2         1       3  26.0            0
3         1       1  35.0            1
4         0       3  35.0            0

In [21]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]
X.head()

   Pclass   Age  Family Type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [23]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))   # accuracy increased

np.float64(0.7003174603174602)