In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\messy_sales_data.xlsx")
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,NaN,0.0,Bob Smith,Pending
2,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,NaN,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,NaN,David Brown,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,NaN,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,NaN,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,NaN,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,NaN,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,NaN,0.0,Bob Smith,Pending

In [8]:
pd.set_option("display.max_rows" , 101)
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,NaN,0.0,Bob Smith,Pending
2,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,NaN,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,NaN,David Brown,Completed
5,1005,NaN,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,NaN,15.0,Alice Johnson,Pending
6,1006,2024-01-15,Tom Clark,tom@email.com,South,Webcam,Electronics,three,79.99,NaN,0.0,Bob Smith,Completed
7,1007,2024-01-18,Lisa Hall,lisa@email.com,East,Headphones,Accessories,4,expensive,NaN,10.0,Carol White,Completed
8,1008,2024-01-20,James Wilson,james@email.com,north,laptop,electronics,1,999.99,NaN,5.0,alice johnson,completed
9,1009,2024-01-22,Emma Davis,emma@email.com,SOUTH,MOUSE,ACCESSORIES,3,29.99,NaN,0.0,BOB SMITH,PENDING
10,1010,2024-01-25,Chris Martin,chris@email.com,West,Monitor,Electronics,-1,299.99,NaN,5.0,David Brown,Completed
11,1011,2024-01-27,Anna Taylor,anna@email.com,North,Keyboard,Accessories,2,-49.99,NaN,0.0,Alice Johnson,Completed
12,1012,2024-01-30,Peter Jones,peter@email.com,East,Webcam,Electronics,2,79.99,NaN,10.0,Carol White,Completed
13,1013,2024-02-02,Mary White,mary@email.com,West,Headphones,Accessories,1,149.99,NaN,0.0,David Brown,Pending
14,1014,2024-02-05,Paul Harris,paulharris,North,Laptop,Electronics,1,999.99,NaN,20.0,Alice Johnson,Completed
15,1015,2024-02-07,Rachel Green,rachel@,South,Mouse,Accessories,6,29.99,NaN,0.0,Bob Smith,Completed
16,1016,2024-02-10,Steve Adams,steve@email.com,East,Laptop,Electronics,500,999.99,NaN,5.0,Carol White,Completed
17,1017,2024-02-12,Laura Scott,laura@email.com,West,Mouse,Accessories,2,0.01,NaN,0.0,David Brown,Completed
18,1018,2024-02-15,Kevin Baker,kevin@email.com,North,Laptop,Accessories,1,999.99,NaN,10.0,Alice Johnson,Completed
19,1019,2024-02-17,Nancy King,nancy@email.com,South,Mouse,Electronics,3,29.99,NaN,0.0,Bob Smith,Pending
20,1020,2024-02-20,George Hill,george@email.com,East,Keyboard,Accessories,2,49.99,NaN,5.0,Carol White,Cancled
21,1021,2024-02-22,Helen Young,helen@email.com,West,Monitor,Electronics,1,299.99,NaN,0.0,David Brown,Compelted
22,1022,2024-02-25,Frank Allen,frank@email.com,North,Webcam,Electronics,3,79.99,NaN,15.0,Alice Johnson,NaN
23,1023,2024-02-27,Sandra Wright,sandra@email.com,South,Headphones,Accessories,2,149.99,NaN,NaN,Bob Smith,Completed
24,1024,2024-03-01,NaN,n/a@email.com,East,Laptop,Electronics,1,999.99,NaN,0.0,NaN,Pending
25,1025,2024-03-03,Daniel Lewis,daniel@email.com,West,Mouse,Accessories,4,29.99,NaN,150.0,David Brown,Completed
26,1026,2024-03-05,Patricia Lee,patricia@email.com,North,Keyboard,Accessories,0,49.99,NaN,5.0,Alice Johnson,Completed
27,1027,03/08/2024,Robert Hall,robert@email.com,South,Monitor,Electronics,2,299.99,NaN,10.0,Bob Smith,Completed
28,1028,March 10 2024,Susan Carter,susan@email.com,East,Webcam,Electronics,1,79.99,NaN,0.0,Carol White,Cancelled
29,1029,2024-03-12,Thomas Turner,thomas@email.com,West,Headphones,Accessories,3,149.99,NaN,5.0,David Brown,Completed
30,1030,2024-07-02,Bob Smith,bobsmith@hotmail.com,South,Mouse,Accessories,3,741.74,NaN,20.0,Alice Johnson,Cancelled
31,1031,2024-08-19,Alice Jones,alicejones@yahoo.com,South,Headphones,Accessories,10,46.01,NaN,5.0,David Brown,Completed
32,1032,2024-07-04,Eve Smith,evesmith@yahoo.com,West,Keyboard,Accessories,5,172.37,NaN,10.0,Alice Johnson,Completed
33,1033,2024-05-27,Frank Davis,frankdavis@hotmail.com,North,Webcam,Electronics,8,545.5,NaN,15.0,Alice Johnson,Cancelled
34,1034,2024-07-09,Jack Davis,jackdavis@yahoo.com,North,Laptop,Electronics,4,777.61,NaN,0.0,Bob Smith,Completed
35,1035,2024-12-08,Hank Davis,hankdavis@yahoo.com,East,Keyboard,Accessories,4,676.77,NaN,0.0,Bob Smith,Cancelled
36,1036,2024-01-26,Carol Hall,carolhall@email.com,East,Webcam,Electronics,9,235.22,NaN,10.0,Alice Johnson,Completed
37,1037,2024-08-13,Frank Clark,frankclark@hotmail.com,North,Mouse,Accessories,10,878.84,NaN,10.0,Bob Smith,Cancelled
38,1038,2024-07-12,Hank Brown,hankbrown@hotmail.com,South,Mouse,Accessories,9,548.2,NaN,20.0,David Brown,Cancelled
39,1039,2024-02-13,Dave Brown,davebrown@email.com,North,Laptop,Electronics,2,169.78,NaN,5.0,David Brown,Cancelled
40,1040,2024-06-04,Grace Young,graceyoung@email.com,East,Headphones,Accessories,1,686.68,NaN,0.0,Carol White,Cancelled
41,1041,2024-05-27,Eve Clark,eveclark@yahoo.com,West,Laptop,Electronics,5,972.45,NaN,5.0,Alice Johnson,Cancelled
42,1042,2024-06-16,Iris Young,irisyoung@yahoo.com,South,Keyboard,Accessories,3,548.59,NaN,20.0,Alice Johnson,Cancelled
43,1043,2024-12-16,Alice Jones,alicejones@hotmail.com,East,Mouse,Accessories,1,256.05,NaN,20.0,Alice Johnson,Completed
44,1044,2024-10-14,Bob Lewis,boblewis@yahoo.com,South,Webcam,Electronics,8,947.91,NaN,5.0,Carol White,Cancelled
45,1045,2024-04-08,Dave Lewis,davelewis@yahoo.com,East,Monitor,Electronics,6,449.34,NaN,20.0,David Brown,Completed
46,1046,2024-01-28,Bob Davis,bobdavis@gmail.com,South,Headphones,Accessories,4,27.05,NaN,0.0,Bob Smith,Completed
47,1047,2024-08-26,Frank Jones,frankjones@yahoo.com,East,Webcam,Electronics,8,229.95,NaN,5.0,David Brown,Completed
48,1048,2024-01-22,Grace Taylor,gracetaylor@gmail.com,North,Webcam,Electronics,7,367.21,NaN,15.0,David Brown,Cancelled
49,1049,2024-07-06,Bob Smith,bobsmith@email.com,East,Laptop,Electronics,4,207.76,NaN,20.0,David Brown,Completed
50,1050,2024-04-06,Eve Hall,evehall@yahoo.com,North,Monitor,Electronics,9,115.95,NaN,20.0,Alice Johnson,Completed
51,1051,2024-08-10,Grace Hall,gracehall@email.com,South,Monitor,Electronics,1,181.34,NaN,0.0,David Brown,Pending
52,1052,2024-06-02,Grace Lewis,gracelewis@email.com,South,Mouse,Accessories,5,233.35,NaN,0.0,Alice Johnson,Cancelled
53,1053,2024-02-22,Alice Young,aliceyoung@email.com,South,Laptop,Electronics,9,98.51,NaN,5.0,Alice Johnson,Cancelled
54,1054,2024-10-19,Dave Clark,daveclark@gmail.com,South,Headphones,Accessories,10,58.95,NaN,0.0,David Brown,Cancelled
55,1055,2024-11-10,Iris Davis,irisdavis@hotmail.com,South,Webcam,Electronics,6,253.91,NaN,15.0,Bob Smith,Cancelled
56,1056,2024-04-17,Hank Davis,hankdavis@gmail.com,North,Monitor,Electronics,10,998.49,NaN,0.0,Alice Johnson,Cancelled
57,1057,2024-11-17,Eve Brown,evebrown@hotmail.com,North,Mouse,Accessories,6,299.29,NaN,15.0,Carol White,Cancelled
58,1058,2024-05-20,Alice Lewis,alicelewis@hotmail.com,North,Mouse,Accessories,5,133.12,NaN,0.0,Bob Smith,Pending
59,1059,2024-07-27,Dave Davis,davedavis@yahoo.com,East,Headphones,Accessories,8,266.1,NaN,0.0,Alice Johnson,Cancelled
60,1060,2024-01-04,Eve Smith,evesmith@gmail.com,East,Mouse,Accessories,5,178.35,NaN,15.0,David Brown,Cancelled
61,1061,2024-06-26,Bob Brown,bobbrown@gmail.com,East,Headphones,Accessories,9,165.13,NaN,5.0,Alice Johnson,Pending
62,1062,2024-12-05,Alice Davis,alicedavis@yahoo.com,South,Webcam,Electronics,2,366.61,NaN,20.0,David Brown,Cancelled
63,1063,2024-12-26,Dave Brown,davebrown@yahoo.com,West,Laptop,Electronics,3,741.83,NaN,10.0,David Brown,Cancelled
64,1064,2024-06-10,Dave Wilson,davewilson@yahoo.com,North,Monitor,Electronics,1,861.42,NaN,5.0,Bob Smith,Pending
65,1065,2024-11-17,Dave Taylor,davetaylor@gmail.com,South,Monitor,Electronics,6,293.03,NaN,0.0,Carol White,Pending
66,1066,2024-10-14,Grace Lewis,gracelewis@hotmail.com,North,Laptop,Electronics,5,195,NaN,10.0,Alice Johnson,Completed
67,1067,2024-09-26,Frank Davis,frankdavis@email.com,North,Monitor,Electronics,10,206.28,NaN,0.0,David Brown,Completed
68,1068,2024-05-22,Iris Taylor,iristaylor@hotmail.com,West,Laptop,Electronics,6,630.69,NaN,0.0,Carol White,Cancelled
69,1069,2024-10-10,Grace Davis,gracedavis@email.com,East,Headphones,Accessories,3,208,NaN,15.0,Bob Smith,Cancelled
70,1070,2024-08-15,Grace Lewis,gracelewis@gmail.com,East,Keyboard,Accessories,4,441.29,NaN,20.0,Carol White,Pending
71,1071,2024-04-22,Dave Lewis,davelewis@email.com,South,Webcam,Electronics,2,298.11,NaN,20.0,Carol White,Completed
72,1072,2024-07-21,Eve Taylor,evetaylor@yahoo.com,South,Laptop,Electronics,1,259.95,NaN,15.0,Alice Johnson,Pending
73,1073,2024-04-06,Jack Taylor,jacktaylor@email.com,West,Monitor,Electronics,4,164.62,NaN,0.0,Alice Johnson,Pending
74,1074,2024-10-27,Iris Hall,irishall@gmail.com,South,Laptop,Electronics,8,150.67,NaN,15.0,Carol White,Pending
75,1075,2024-08-21,Iris Clark,irisclark@email.com,South,Webcam,Electronics,8,461.07,NaN,5.0,Carol White,Cancelled
76,1076,2024-02-05,Dave Wilson,davewilson@email.com,North,Webcam,Electronics,5,249.8,NaN,10.0,Carol White,Cancelled
77,1077,2024-08-14,Carol Taylor,caroltaylor@email.com,South,Webcam,Electronics,4,82.94,NaN,15.0,Carol White,Cancelled
78,1078,2024-01-12,Alice Taylor,alicetaylor@email.com,West,Headphones,Accessories,1,859.6,NaN,20.0,David Brown,Pending
79,1079,2024-06-22,Eve Clark,eveclark@email.com,South,Monitor,Electronics,4,287.48,NaN,15.0,Alice Johnson,Pending
80,1080,2024-11-14,Grace Brown,gracebrown@email.com,South,Headphones,Accessories,9,46.43,NaN,15.0,Alice Johnson,Completed
81,1081,2024-07-09,Carol Hall,carolhall@yahoo.com,North,Keyboard,Accessories,7,340.81,NaN,15.0,Carol White,Pending
82,1082,2024-02-25,Grace Wilson,gracewilson@gmail.com,West,Laptop,Electronics,9,71.04,NaN,10.0,Bob Smith,Cancelled
83,1083,2024-02-19,Alice Smith,alicesmith@yahoo.com,South,Laptop,Electronics,10,169.33,NaN,5.0,David Brown,Cancelled
84,1084,2024-02-19,Dave Hall,davehall@hotmail.com,East,Mouse,Accessories,10,615.1,NaN,0.0,Bob Smith,Pending
85,1085,2024-05-28,Alice Wilson,alicewilson@email.com,West,Webcam,Electronics,4,94.48,NaN,5.0,Alice Johnson,Cancelled
86,1086,2024-07-27,Jack Jones,jackjones@gmail.com,East,Headphones,Accessories,7,668.29,NaN,0.0,Carol White,Completed
87,1087,2024-09-21,Hank Jones,hankjones@email.com,East,Webcam,Electronics,8,713.16,NaN,15.0,Bob Smith,Cancelled
88,1088,2024-08-08,Eve Young,eveyoung@email.com,West,Monitor,Electronics,10,283.03,NaN,5.0,Alice Johnson,Pending
89,1089,2024-06-26,Hank Young,hankyoung@email.com,East,Laptop,Electronics,8,853.93,NaN,5.0,David Brown,Completed
90,1090,2024-12-14,Eve Davis,evedavis@hotmail.com,East,Headphones,Accessories,1,526.29,NaN,5.0,Alice Johnson,Completed
91,1091,2024-04-13,Hank Lewis,hanklewis@yahoo.com,West,Webcam,Electronics,8,459.21,NaN,0.0,Alice Johnson,Pending
92,1092,2024-12-15,Dave Wilson,davewilson@hotmail.com,West,Headphones,Accessories,9,356.88,NaN,20.0,Carol White,Pending
93,1093,2024-04-24,Eve Wilson,evewilson@hotmail.com,South,Laptop,Electronics,4,329.24,NaN,20.0,Bob Smith,Completed
94,1094,2024-12-18,Hank Wilson,hankwilson@hotmail.com,North,Mouse,Accessories,5,242.93,NaN,5.0,Carol White,Completed
95,1095,2024-01-19,Carol Wilson,carolwilson@gmail.com,North,Headphones,Accessories,5,703.47,NaN,5.0,David Brown,Completed
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,NaN,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,NaN,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,NaN,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,NaN,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,NaN,0.0,Bob Smith,Pending

In [10]:
df = df.drop_duplicates()
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,NaN,0.0,Bob Smith,Pending
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,NaN,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,NaN,David Brown,Completed
5,1005,NaN,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,NaN,15.0,Alice Johnson,Pending
6,1006,2024-01-15,Tom Clark,tom@email.com,South,Webcam,Electronics,three,79.99,NaN,0.0,Bob Smith,Completed
7,1007,2024-01-18,Lisa Hall,lisa@email.com,East,Headphones,Accessories,4,expensive,NaN,10.0,Carol White,Completed
8,1008,2024-01-20,James Wilson,james@email.com,north,laptop,electronics,1,999.99,NaN,5.0,alice johnson,completed
9,1009,2024-01-22,Emma Davis,emma@email.com,SOUTH,MOUSE,ACCESSORIES,3,29.99,NaN,0.0,BOB SMITH,PENDING
10,1010,2024-01-25,Chris Martin,chris@email.com,West,Monitor,Electronics,-1,299.99,NaN,5.0,David Brown,Completed
11,1011,2024-01-27,Anna Taylor,anna@email.com,North,Keyboard,Accessories,2,-49.99,NaN,0.0,Alice Johnson,Completed
12,1012,2024-01-30,Peter Jones,peter@email.com,East,Webcam,Electronics,2,79.99,NaN,10.0,Carol White,Completed
13,1013,2024-02-02,Mary White,mary@email.com,West,Headphones,Accessories,1,149.99,NaN,0.0,David Brown,Pending
14,1014,2024-02-05,Paul Harris,paulharris,North,Laptop,Electronics,1,999.99,NaN,20.0,Alice Johnson,Completed
15,1015,2024-02-07,Rachel Green,rachel@,South,Mouse,Accessories,6,29.99,NaN,0.0,Bob Smith,Completed
16,1016,2024-02-10,Steve Adams,steve@email.com,East,Laptop,Electronics,500,999.99,NaN,5.0,Carol White,Completed
17,1017,2024-02-12,Laura Scott,laura@email.com,West,Mouse,Accessories,2,0.01,NaN,0.0,David Brown,Completed
18,1018,2024-02-15,Kevin Baker,kevin@email.com,North,Laptop,Accessories,1,999.99,NaN,10.0,Alice Johnson,Completed
19,1019,2024-02-17,Nancy King,nancy@email.com,South,Mouse,Electronics,3,29.99,NaN,0.0,Bob Smith,Pending
20,1020,2024-02-20,George Hill,george@email.com,East,Keyboard,Accessories,2,49.99,NaN,5.0,Carol White,Cancled
21,1021,2024-02-22,Helen Young,helen@email.com,West,Monitor,Electronics,1,299.99,NaN,0.0,David Brown,Compelted
22,1022,2024-02-25,Frank Allen,frank@email.com,North,Webcam,Electronics,3,79.99,NaN,15.0,Alice Johnson,NaN
23,1023,2024-02-27,Sandra Wright,sandra@email.com,South,Headphones,Accessories,2,149.99,NaN,NaN,Bob Smith,Completed
24,1024,2024-03-01,NaN,n/a@email.com,East,Laptop,Electronics,1,999.99,NaN,0.0,NaN,Pending
25,1025,2024-03-03,Daniel Lewis,daniel@email.com,West,Mouse,Accessories,4,29.99,NaN,150.0,David Brown,Completed
26,1026,2024-03-05,Patricia Lee,patricia@email.com,North,Keyboard,Accessories,0,49.99,NaN,5.0,Alice Johnson,Completed
27,1027,03/08/2024,Robert Hall,robert@email.com,South,Monitor,Electronics,2,299.99,NaN,10.0,Bob Smith,Completed
28,1028,March 10 2024,Susan Carter,susan@email.com,East,Webcam,Electronics,1,79.99,NaN,0.0,Carol White,Cancelled
29,1029,2024-03-12,Thomas Turner,thomas@email.com,West,Headphones,Accessories,3,149.99,NaN,5.0,David Brown,Completed
30,1030,2024-07-02,Bob Smith,bobsmith@hotmail.com,South,Mouse,Accessories,3,741.74,NaN,20.0,Alice Johnson,Cancelled
31,1031,2024-08-19,Alice Jones,alicejones@yahoo.com,South,Headphones,Accessories,10,46.01,NaN,5.0,David Brown,Completed
32,1032,2024-07-04,Eve Smith,evesmith@yahoo.com,West,Keyboard,Accessories,5,172.37,NaN,10.0,Alice Johnson,Completed
33,1033,2024-05-27,Frank Davis,frankdavis@hotmail.com,North,Webcam,Electronics,8,545.5,NaN,15.0,Alice Johnson,Cancelled
34,1034,2024-07-09,Jack Davis,jackdavis@yahoo.com,North,Laptop,Electronics,4,777.61,NaN,0.0,Bob Smith,Completed
35,1035,2024-12-08,Hank Davis,hankdavis@yahoo.com,East,Keyboard,Accessories,4,676.77,NaN,0.0,Bob Smith,Cancelled
36,1036,2024-01-26,Carol Hall,carolhall@email.com,East,Webcam,Electronics,9,235.22,NaN,10.0,Alice Johnson,Completed
37,1037,2024-08-13,Frank Clark,frankclark@hotmail.com,North,Mouse,Accessories,10,878.84,NaN,10.0,Bob Smith,Cancelled
38,1038,2024-07-12,Hank Brown,hankbrown@hotmail.com,South,Mouse,Accessories,9,548.2,NaN,20.0,David Brown,Cancelled
39,1039,2024-02-13,Dave Brown,davebrown@email.com,North,Laptop,Electronics,2,169.78,NaN,5.0,David Brown,Cancelled
40,1040,2024-06-04,Grace Young,graceyoung@email.com,East,Headphones,Accessories,1,686.68,NaN,0.0,Carol White,Cancelled
41,1041,2024-05-27,Eve Clark,eveclark@yahoo.com,West,Laptop,Electronics,5,972.45,NaN,5.0,Alice Johnson,Cancelled
42,1042,2024-06-16,Iris Young,irisyoung@yahoo.com,South,Keyboard,Accessories,3,548.59,NaN,20.0,Alice Johnson,Cancelled
43,1043,2024-12-16,Alice Jones,alicejones@hotmail.com,East,Mouse,Accessories,1,256.05,NaN,20.0,Alice Johnson,Completed
44,1044,2024-10-14,Bob Lewis,boblewis@yahoo.com,South,Webcam,Electronics,8,947.91,NaN,5.0,Carol White,Cancelled
45,1045,2024-04-08,Dave Lewis,davelewis@yahoo.com,East,Monitor,Electronics,6,449.34,NaN,20.0,David Brown,Completed
46,1046,2024-01-28,Bob Davis,bobdavis@gmail.com,South,Headphones,Accessories,4,27.05,NaN,0.0,Bob Smith,Completed
47,1047,2024-08-26,Frank Jones,frankjones@yahoo.com,East,Webcam,Electronics,8,229.95,NaN,5.0,David Brown,Completed
48,1048,2024-01-22,Grace Taylor,gracetaylor@gmail.com,North,Webcam,Electronics,7,367.21,NaN,15.0,David Brown,Cancelled
49,1049,2024-07-06,Bob Smith,bobsmith@email.com,East,Laptop,Electronics,4,207.76,NaN,20.0,David Brown,Completed
50,1050,2024-04-06,Eve Hall,evehall@yahoo.com,North,Monitor,Electronics,9,115.95,NaN,20.0,Alice Johnson,Completed
51,1051,2024-08-10,Grace Hall,gracehall@email.com,South,Monitor,Electronics,1,181.34,NaN,0.0,David Brown,Pending
52,1052,2024-06-02,Grace Lewis,gracelewis@email.com,South,Mouse,Accessories,5,233.35,NaN,0.0,Alice Johnson,Cancelled
53,1053,2024-02-22,Alice Young,aliceyoung@email.com,South,Laptop,Electronics,9,98.51,NaN,5.0,Alice Johnson,Cancelled
54,1054,2024-10-19,Dave Clark,daveclark@gmail.com,South,Headphones,Accessories,10,58.95,NaN,0.0,David Brown,Cancelled
55,1055,2024-11-10,Iris Davis,irisdavis@hotmail.com,South,Webcam,Electronics,6,253.91,NaN,15.0,Bob Smith,Cancelled
56,1056,2024-04-17,Hank Davis,hankdavis@gmail.com,North,Monitor,Electronics,10,998.49,NaN,0.0,Alice Johnson,Cancelled
57,1057,2024-11-17,Eve Brown,evebrown@hotmail.com,North,Mouse,Accessories,6,299.29,NaN,15.0,Carol White,Cancelled
58,1058,2024-05-20,Alice Lewis,alicelewis@hotmail.com,North,Mouse,Accessories,5,133.12,NaN,0.0,Bob Smith,Pending
59,1059,2024-07-27,Dave Davis,davedavis@yahoo.com,East,Headphones,Accessories,8,266.1,NaN,0.0,Alice Johnson,Cancelled
60,1060,2024-01-04,Eve Smith,evesmith@gmail.com,East,Mouse,Accessories,5,178.35,NaN,15.0,David Brown,Cancelled
61,1061,2024-06-26,Bob Brown,bobbrown@gmail.com,East,Headphones,Accessories,9,165.13,NaN,5.0,Alice Johnson,Pending
62,1062,2024-12-05,Alice Davis,alicedavis@yahoo.com,South,Webcam,Electronics,2,366.61,NaN,20.0,David Brown,Cancelled
63,1063,2024-12-26,Dave Brown,davebrown@yahoo.com,West,Laptop,Electronics,3,741.83,NaN,10.0,David Brown,Cancelled
64,1064,2024-06-10,Dave Wilson,davewilson@yahoo.com,North,Monitor,Electronics,1,861.42,NaN,5.0,Bob Smith,Pending
65,1065,2024-11-17,Dave Taylor,davetaylor@gmail.com,South,Monitor,Electronics,6,293.03,NaN,0.0,Carol White,Pending
66,1066,2024-10-14,Grace Lewis,gracelewis@hotmail.com,North,Laptop,Electronics,5,195,NaN,10.0,Alice Johnson,Completed
67,1067,2024-09-26,Frank Davis,frankdavis@email.com,North,Monitor,Electronics,10,206.28,NaN,0.0,David Brown,Completed
68,1068,2024-05-22,Iris Taylor,iristaylor@hotmail.com,West,Laptop,Electronics,6,630.69,NaN,0.0,Carol White,Cancelled
69,1069,2024-10-10,Grace Davis,gracedavis@email.com,East,Headphones,Accessories,3,208,NaN,15.0,Bob Smith,Cancelled
70,1070,2024-08-15,Grace Lewis,gracelewis@gmail.com,East,Keyboard,Accessories,4,441.29,NaN,20.0,Carol White,Pending
71,1071,2024-04-22,Dave Lewis,davelewis@email.com,South,Webcam,Electronics,2,298.11,NaN,20.0,Carol White,Completed
72,1072,2024-07-21,Eve Taylor,evetaylor@yahoo.com,South,Laptop,Electronics,1,259.95,NaN,15.0,Alice Johnson,Pending
73,1073,2024-04-06,Jack Taylor,jacktaylor@email.com,West,Monitor,Electronics,4,164.62,NaN,0.0,Alice Johnson,Pending
74,1074,2024-10-27,Iris Hall,irishall@gmail.com,South,Laptop,Electronics,8,150.67,NaN,15.0,Carol White,Pending
75,1075,2024-08-21,Iris Clark,irisclark@email.com,South,Webcam,Electronics,8,461.07,NaN,5.0,Carol White,Cancelled
76,1076,2024-02-05,Dave Wilson,davewilson@email.com,North,Webcam,Electronics,5,249.8,NaN,10.0,Carol White,Cancelled
77,1077,2024-08-14,Carol Taylor,caroltaylor@email.com,South,Webcam,Electronics,4,82.94,NaN,15.0,Carol White,Cancelled
78,1078,2024-01-12,Alice Taylor,alicetaylor@email.com,West,Headphones,Accessories,1,859.6,NaN,20.0,David Brown,Pending
79,1079,2024-06-22,Eve Clark,eveclark@email.com,South,Monitor,Electronics,4,287.48,NaN,15.0,Alice Johnson,Pending
80,1080,2024-11-14,Grace Brown,gracebrown@email.com,South,Headphones,Accessories,9,46.43,NaN,15.0,Alice Johnson,Completed
81,1081,2024-07-09,Carol Hall,carolhall@yahoo.com,North,Keyboard,Accessories,7,340.81,NaN,15.0,Carol White,Pending
82,1082,2024-02-25,Grace Wilson,gracewilson@gmail.com,West,Laptop,Electronics,9,71.04,NaN,10.0,Bob Smith,Cancelled
83,1083,2024-02-19,Alice Smith,alicesmith@yahoo.com,South,Laptop,Electronics,10,169.33,NaN,5.0,David Brown,Cancelled
84,1084,2024-02-19,Dave Hall,davehall@hotmail.com,East,Mouse,Accessories,10,615.1,NaN,0.0,Bob Smith,Pending
85,1085,2024-05-28,Alice Wilson,alicewilson@email.com,West,Webcam,Electronics,4,94.48,NaN,5.0,Alice Johnson,Cancelled
86,1086,2024-07-27,Jack Jones,jackjones@gmail.com,East,Headphones,Accessories,7,668.29,NaN,0.0,Carol White,Completed
87,1087,2024-09-21,Hank Jones,hankjones@email.com,East,Webcam,Electronics,8,713.16,NaN,15.0,Bob Smith,Cancelled
88,1088,2024-08-08,Eve Young,eveyoung@email.com,West,Monitor,Electronics,10,283.03,NaN,5.0,Alice Johnson,Pending
89,1089,2024-06-26,Hank Young,hankyoung@email.com,East,Laptop,Electronics,8,853.93,NaN,5.0,David Brown,Completed
90,1090,2024-12-14,Eve Davis,evedavis@hotmail.com,East,Headphones,Accessories,1,526.29,NaN,5.0,Alice Johnson,Completed
91,1091,2024-04-13,Hank Lewis,hanklewis@yahoo.com,West,Webcam,Electronics,8,459.21,NaN,0.0,Alice Johnson,Pending
92,1092,2024-12-15,Dave Wilson,davewilson@hotmail.com,West,Headphones,Accessories,9,356.88,NaN,20.0,Carol White,Pending
93,1093,2024-04-24,Eve Wilson,evewilson@hotmail.com,South,Laptop,Electronics,4,329.24,NaN,20.0,Bob Smith,Completed
94,1094,2024-12-18,Hank Wilson,hankwilson@hotmail.com,North,Mouse,Accessories,5,242.93,NaN,5.0,Carol White,Completed
95,1095,2024-01-19,Carol Wilson,carolwilson@gmail.com,North,Headphones,Accessories,5,703.47,NaN,5.0,David Brown,Completed
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,NaN,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,NaN,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,NaN,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,NaN,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,NaN,0.0,Bob Smith,Pending

In [13]:
df.drop(columns = "Total_Sales" , inplace  = True)

In [14]:
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,0.0,Bob Smith,Pending
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,David Brown,Completed
5,1005,NaN,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,15.0,Alice Johnson,Pending
6,1006,2024-01-15,Tom Clark,tom@email.com,South,Webcam,Electronics,three,79.99,0.0,Bob Smith,Completed
7,1007,2024-01-18,Lisa Hall,lisa@email.com,East,Headphones,Accessories,4,expensive,10.0,Carol White,Completed
8,1008,2024-01-20,James Wilson,james@email.com,north,laptop,electronics,1,999.99,5.0,alice johnson,completed
9,1009,2024-01-22,Emma Davis,emma@email.com,SOUTH,MOUSE,ACCESSORIES,3,29.99,0.0,BOB SMITH,PENDING
10,1010,2024-01-25,Chris Martin,chris@email.com,West,Monitor,Electronics,-1,299.99,5.0,David Brown,Completed
11,1011,2024-01-27,Anna Taylor,anna@email.com,North,Keyboard,Accessories,2,-49.99,0.0,Alice Johnson,Completed
12,1012,2024-01-30,Peter Jones,peter@email.com,East,Webcam,Electronics,2,79.99,10.0,Carol White,Completed
13,1013,2024-02-02,Mary White,mary@email.com,West,Headphones,Accessories,1,149.99,0.0,David Brown,Pending
14,1014,2024-02-05,Paul Harris,paulharris,North,Laptop,Electronics,1,999.99,20.0,Alice Johnson,Completed
15,1015,2024-02-07,Rachel Green,rachel@,South,Mouse,Accessories,6,29.99,0.0,Bob Smith,Completed
16,1016,2024-02-10,Steve Adams,steve@email.com,East,Laptop,Electronics,500,999.99,5.0,Carol White,Completed
17,1017,2024-02-12,Laura Scott,laura@email.com,West,Mouse,Accessories,2,0.01,0.0,David Brown,Completed
18,1018,2024-02-15,Kevin Baker,kevin@email.com,North,Laptop,Accessories,1,999.99,10.0,Alice Johnson,Completed
19,1019,2024-02-17,Nancy King,nancy@email.com,South,Mouse,Electronics,3,29.99,0.0,Bob Smith,Pending
20,1020,2024-02-20,George Hill,george@email.com,East,Keyboard,Accessories,2,49.99,5.0,Carol White,Cancled
21,1021,2024-02-22,Helen Young,helen@email.com,West,Monitor,Electronics,1,299.99,0.0,David Brown,Compelted
22,1022,2024-02-25,Frank Allen,frank@email.com,North,Webcam,Electronics,3,79.99,15.0,Alice Johnson,NaN
23,1023,2024-02-27,Sandra Wright,sandra@email.com,South,Headphones,Accessories,2,149.99,NaN,Bob Smith,Completed
24,1024,2024-03-01,NaN,n/a@email.com,East,Laptop,Electronics,1,999.99,0.0,NaN,Pending
25,1025,2024-03-03,Daniel Lewis,daniel@email.com,West,Mouse,Accessories,4,29.99,150.0,David Brown,Completed
26,1026,2024-03-05,Patricia Lee,patricia@email.com,North,Keyboard,Accessories,0,49.99,5.0,Alice Johnson,Completed
27,1027,03/08/2024,Robert Hall,robert@email.com,South,Monitor,Electronics,2,299.99,10.0,Bob Smith,Completed
28,1028,March 10 2024,Susan Carter,susan@email.com,East,Webcam,Electronics,1,79.99,0.0,Carol White,Cancelled
29,1029,2024-03-12,Thomas Turner,thomas@email.com,West,Headphones,Accessories,3,149.99,5.0,David Brown,Completed
30,1030,2024-07-02,Bob Smith,bobsmith@hotmail.com,South,Mouse,Accessories,3,741.74,20.0,Alice Johnson,Cancelled
31,1031,2024-08-19,Alice Jones,alicejones@yahoo.com,South,Headphones,Accessories,10,46.01,5.0,David Brown,Completed
32,1032,2024-07-04,Eve Smith,evesmith@yahoo.com,West,Keyboard,Accessories,5,172.37,10.0,Alice Johnson,Completed
33,1033,2024-05-27,Frank Davis,frankdavis@hotmail.com,North,Webcam,Electronics,8,545.5,15.0,Alice Johnson,Cancelled
34,1034,2024-07-09,Jack Davis,jackdavis@yahoo.com,North,Laptop,Electronics,4,777.61,0.0,Bob Smith,Completed
35,1035,2024-12-08,Hank Davis,hankdavis@yahoo.com,East,Keyboard,Accessories,4,676.77,0.0,Bob Smith,Cancelled
36,1036,2024-01-26,Carol Hall,carolhall@email.com,East,Webcam,Electronics,9,235.22,10.0,Alice Johnson,Completed
37,1037,2024-08-13,Frank Clark,frankclark@hotmail.com,North,Mouse,Accessories,10,878.84,10.0,Bob Smith,Cancelled
38,1038,2024-07-12,Hank Brown,hankbrown@hotmail.com,South,Mouse,Accessories,9,548.2,20.0,David Brown,Cancelled
39,1039,2024-02-13,Dave Brown,davebrown@email.com,North,Laptop,Electronics,2,169.78,5.0,David Brown,Cancelled
40,1040,2024-06-04,Grace Young,graceyoung@email.com,East,Headphones,Accessories,1,686.68,0.0,Carol White,Cancelled
41,1041,2024-05-27,Eve Clark,eveclark@yahoo.com,West,Laptop,Electronics,5,972.45,5.0,Alice Johnson,Cancelled
42,1042,2024-06-16,Iris Young,irisyoung@yahoo.com,South,Keyboard,Accessories,3,548.59,20.0,Alice Johnson,Cancelled
43,1043,2024-12-16,Alice Jones,alicejones@hotmail.com,East,Mouse,Accessories,1,256.05,20.0,Alice Johnson,Completed
44,1044,2024-10-14,Bob Lewis,boblewis@yahoo.com,South,Webcam,Electronics,8,947.91,5.0,Carol White,Cancelled
45,1045,2024-04-08,Dave Lewis,davelewis@yahoo.com,East,Monitor,Electronics,6,449.34,20.0,David Brown,Completed
46,1046,2024-01-28,Bob Davis,bobdavis@gmail.com,South,Headphones,Accessories,4,27.05,0.0,Bob Smith,Completed
47,1047,2024-08-26,Frank Jones,frankjones@yahoo.com,East,Webcam,Electronics,8,229.95,5.0,David Brown,Completed
48,1048,2024-01-22,Grace Taylor,gracetaylor@gmail.com,North,Webcam,Electronics,7,367.21,15.0,David Brown,Cancelled
49,1049,2024-07-06,Bob Smith,bobsmith@email.com,East,Laptop,Electronics,4,207.76,20.0,David Brown,Completed
50,1050,2024-04-06,Eve Hall,evehall@yahoo.com,North,Monitor,Electronics,9,115.95,20.0,Alice Johnson,Completed
51,1051,2024-08-10,Grace Hall,gracehall@email.com,South,Monitor,Electronics,1,181.34,0.0,David Brown,Pending
52,1052,2024-06-02,Grace Lewis,gracelewis@email.com,South,Mouse,Accessories,5,233.35,0.0,Alice Johnson,Cancelled
53,1053,2024-02-22,Alice Young,aliceyoung@email.com,South,Laptop,Electronics,9,98.51,5.0,Alice Johnson,Cancelled
54,1054,2024-10-19,Dave Clark,daveclark@gmail.com,South,Headphones,Accessories,10,58.95,0.0,David Brown,Cancelled
55,1055,2024-11-10,Iris Davis,irisdavis@hotmail.com,South,Webcam,Electronics,6,253.91,15.0,Bob Smith,Cancelled
56,1056,2024-04-17,Hank Davis,hankdavis@gmail.com,North,Monitor,Electronics,10,998.49,0.0,Alice Johnson,Cancelled
57,1057,2024-11-17,Eve Brown,evebrown@hotmail.com,North,Mouse,Accessories,6,299.29,15.0,Carol White,Cancelled
58,1058,2024-05-20,Alice Lewis,alicelewis@hotmail.com,North,Mouse,Accessories,5,133.12,0.0,Bob Smith,Pending
59,1059,2024-07-27,Dave Davis,davedavis@yahoo.com,East,Headphones,Accessories,8,266.1,0.0,Alice Johnson,Cancelled
60,1060,2024-01-04,Eve Smith,evesmith@gmail.com,East,Mouse,Accessories,5,178.35,15.0,David Brown,Cancelled
61,1061,2024-06-26,Bob Brown,bobbrown@gmail.com,East,Headphones,Accessories,9,165.13,5.0,Alice Johnson,Pending
62,1062,2024-12-05,Alice Davis,alicedavis@yahoo.com,South,Webcam,Electronics,2,366.61,20.0,David Brown,Cancelled
63,1063,2024-12-26,Dave Brown,davebrown@yahoo.com,West,Laptop,Electronics,3,741.83,10.0,David Brown,Cancelled
64,1064,2024-06-10,Dave Wilson,davewilson@yahoo.com,North,Monitor,Electronics,1,861.42,5.0,Bob Smith,Pending
65,1065,2024-11-17,Dave Taylor,davetaylor@gmail.com,South,Monitor,Electronics,6,293.03,0.0,Carol White,Pending
66,1066,2024-10-14,Grace Lewis,gracelewis@hotmail.com,North,Laptop,Electronics,5,195,10.0,Alice Johnson,Completed
67,1067,2024-09-26,Frank Davis,frankdavis@email.com,North,Monitor,Electronics,10,206.28,0.0,David Brown,Completed
68,1068,2024-05-22,Iris Taylor,iristaylor@hotmail.com,West,Laptop,Electronics,6,630.69,0.0,Carol White,Cancelled
69,1069,2024-10-10,Grace Davis,gracedavis@email.com,East,Headphones,Accessories,3,208,15.0,Bob Smith,Cancelled
70,1070,2024-08-15,Grace Lewis,gracelewis@gmail.com,East,Keyboard,Accessories,4,441.29,20.0,Carol White,Pending
71,1071,2024-04-22,Dave Lewis,davelewis@email.com,South,Webcam,Electronics,2,298.11,20.0,Carol White,Completed
72,1072,2024-07-21,Eve Taylor,evetaylor@yahoo.com,South,Laptop,Electronics,1,259.95,15.0,Alice Johnson,Pending
73,1073,2024-04-06,Jack Taylor,jacktaylor@email.com,West,Monitor,Electronics,4,164.62,0.0,Alice Johnson,Pending
74,1074,2024-10-27,Iris Hall,irishall@gmail.com,South,Laptop,Electronics,8,150.67,15.0,Carol White,Pending
75,1075,2024-08-21,Iris Clark,irisclark@email.com,South,Webcam,Electronics,8,461.07,5.0,Carol White,Cancelled
76,1076,2024-02-05,Dave Wilson,davewilson@email.com,North,Webcam,Electronics,5,249.8,10.0,Carol White,Cancelled
77,1077,2024-08-14,Carol Taylor,caroltaylor@email.com,South,Webcam,Electronics,4,82.94,15.0,Carol White,Cancelled
78,1078,2024-01-12,Alice Taylor,alicetaylor@email.com,West,Headphones,Accessories,1,859.6,20.0,David Brown,Pending
79,1079,2024-06-22,Eve Clark,eveclark@email.com,South,Monitor,Electronics,4,287.48,15.0,Alice Johnson,Pending
80,1080,2024-11-14,Grace Brown,gracebrown@email.com,South,Headphones,Accessories,9,46.43,15.0,Alice Johnson,Completed
81,1081,2024-07-09,Carol Hall,carolhall@yahoo.com,North,Keyboard,Accessories,7,340.81,15.0,Carol White,Pending
82,1082,2024-02-25,Grace Wilson,gracewilson@gmail.com,West,Laptop,Electronics,9,71.04,10.0,Bob Smith,Cancelled
83,1083,2024-02-19,Alice Smith,alicesmith@yahoo.com,South,Laptop,Electronics,10,169.33,5.0,David Brown,Cancelled
84,1084,2024-02-19,Dave Hall,davehall@hotmail.com,East,Mouse,Accessories,10,615.1,0.0,Bob Smith,Pending
85,1085,2024-05-28,Alice Wilson,alicewilson@email.com,West,Webcam,Electronics,4,94.48,5.0,Alice Johnson,Cancelled
86,1086,2024-07-27,Jack Jones,jackjones@gmail.com,East,Headphones,Accessories,7,668.29,0.0,Carol White,Completed
87,1087,2024-09-21,Hank Jones,hankjones@email.com,East,Webcam,Electronics,8,713.16,15.0,Bob Smith,Cancelled
88,1088,2024-08-08,Eve Young,eveyoung@email.com,West,Monitor,Electronics,10,283.03,5.0,Alice Johnson,Pending
89,1089,2024-06-26,Hank Young,hankyoung@email.com,East,Laptop,Electronics,8,853.93,5.0,David Brown,Completed
90,1090,2024-12-14,Eve Davis,evedavis@hotmail.com,East,Headphones,Accessories,1,526.29,5.0,Alice Johnson,Completed
91,1091,2024-04-13,Hank Lewis,hanklewis@yahoo.com,West,Webcam,Electronics,8,459.21,0.0,Alice Johnson,Pending
92,1092,2024-12-15,Dave Wilson,davewilson@hotmail.com,West,Headphones,Accessories,9,356.88,20.0,Carol White,Pending
93,1093,2024-04-24,Eve Wilson,evewilson@hotmail.com,South,Laptop,Electronics,4,329.24,20.0,Bob Smith,Completed
94,1094,2024-12-18,Hank Wilson,hankwilson@hotmail.com,North,Mouse,Accessories,5,242.93,5.0,Carol White,Completed
95,1095,2024-01-19,Carol Wilson,carolwilson@gmail.com,North,Headphones,Accessories,5,703.47,5.0,David Brown,Completed
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,0.0,Bob Smith,Pending

In [16]:
pd.reset_option("display.max_rows")

In [17]:
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,0.0,Bob Smith,Pending
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,David Brown,Completed
5,1005,NaN,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,15.0,Alice Johnson,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,0.0,Bob Smith,Pending

In [19]:
df["Customer_Name"].str.lstrip("NaN")

0         John Doe
1       Jane Smith
3              NaN
4       Mike Brown
5         Sara Lee
          ...
96        Eve Hall
97      Hank Jones
98     Grace Young
99     Alice Young
100      Bob Brown
Name: Customer_Name, Length: 100, dtype: str

In [5]:
df["Date"].dtype

In [7]:
df["Date"] = pd.to_datetime(df["Date"], format = "mixed"  , errors = "coerce")
df["Date"].dtype

dtype('<M8[us]')

In [15]:
df.describe()

          Order_ID                 Date  Total_Sales  Discount_%
count   101.000000                  100          0.0   99.000000
mean   1050.009901  2024-05-23 14:09:36          NaN    9.393939
min    1001.000000  2024-01-04 00:00:00          NaN    0.000000
25%    1025.000000  2024-02-13 00:00:00          NaN    0.000000
50%    1050.000000  2024-05-07 00:00:00          NaN    5.000000
75%    1075.000000  2024-08-14 06:00:00          NaN   15.000000
max    1100.000000  2024-12-26 00:00:00          NaN  150.000000
std      29.283270                  NaN          NaN   16.008173

In [18]:
df.duplicated().sum()

np.int64(1)

In [21]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 0 to 100
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       100 non-null    int64
 1   Date           99 non-null     datetime64[us]
 2   Customer_Name  98 non-null     str
 3   Email          99 non-null     str
 4   Region         100 non-null    str
 5   Product        99 non-null     str
 6   Category       100 non-null    str
 7   Quantity       100 non-null    object
 8   Unit_Price     100 non-null    object
 9   Total_Sales    0 non-null      float64
 10  Discount_%     98 non-null     float64
 11  Sales_Rep      99 non-null     str
 12  Status         99 non-null     str
dtypes: datetime64[us](1), float64(2), int64(1), object(2), str(7)
memory usage: 10.9+ KB

# Data cleaning

In [39]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Data_Cleaning_Simple.xlsx")

In [27]:
round(df.describe(),2)

       Customer_ID     Age     Salary  Purchases
count        50.00   49.00      47.00      50.00
mean        125.50   56.55   71670.66      15.88
std          14.58  137.97   28426.20       9.63
min         101.00   -5.00   30074.00       2.00
25%         113.25   27.00   50000.00       7.25
50%         125.50   37.00   62591.00      14.00
75%         137.75   47.00   96272.00      25.00
max         150.00  999.00  119733.00      30.00

In [30]:
df.isnull().sum()/len(df)*100

Customer_ID       0.0
Customer_Name    10.0
Age               2.0
Salary            6.0
Gender            0.0
Date_Joined       0.0
City              0.0
Purchases         0.0
dtype: float64

In [33]:
mean = df.Salary.mean()
print(mean)

71670.65957446808

In [38]:
df.loc[(df.Gender == "Female") & (df.Salary >= mean)].count()

Customer_ID      8
Customer_Name    6
Age              8
Salary           8
Gender           8
Date_Joined      8
City             8
Purchases        8
dtype: int64

In [43]:
df[df.duplicated()].shape

(0, 8)

In [44]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Salary', 'Gender',
       'Date_Joined', 'City', 'Purchases'],
      dtype='str')

In [49]:
df["Customer_ID"].duplicated().sum()

np.int64(0)

In [50]:
df[df["Customer_ID"] == 102]

,Customer_ID,Customer_Name,Age,Salary,Gender,Date_Joined,City,Purchases
1,102,Fatima Malik,27.0,107397.0,Female,2019-03-07,Karachi,3

In [59]:
for col in df.columns:         # goes through each column one by one 
    if df[col].nunique() < 20:  # if the column has less than 15 unique values ( we want cities and gender as salary, name, ID these all are unique)
        print(df[col].value_counts())  # count these values
        print("-"*30)

Gender
Female    24
Male      23
male       1
F          1
M          1
Name: count, dtype: int64
------------------------------
City
Karachi      9
Islamabad    7
Lahore       6
Peshawar     5
LAhore       3
Quetta       3
Islamabdd    2
Lhore        2
Peshawer     2
Quettaa      2
Karachii     2
Lahor        2
Lahorre      1
QUetta       1
Peshawr      1
Islambad     1
Peshwar      1
Name: count, dtype: int64
------------------------------

In [66]:
print(df["City"].nunique())   # how many unique city names 
df["City"].value_counts()

17

City
Karachi      9
Islamabad    7
Lahore       6
Peshawar     5
LAhore       3
Quetta       3
Islamabdd    2
Lhore        2
Peshawer     2
Quettaa      2
Karachii     2
Lahor        2
Lahorre      1
QUetta       1
Peshawr      1
Islambad     1
Peshwar      1
Name: count, dtype: int64

### first step handling missing values

In [72]:
df.isnull().sum()          # sum of null percolumns 
# df.isnull().count()      # count all values in the column (isnull --> gives true and false table)

Customer_ID      0
Customer_Name    5
Age              1
Salary           3
Gender           0
Date_Joined      0
City             0
Purchases        0
dtype: int64

In [74]:
df[df.isnull().any(axis=1)]

,Customer_ID,Customer_Name,Age,Salary,Gender,Date_Joined,City,Purchases
4,105,..Zara Sheikh,NaN,50926.0,Female,2020-11-27,Islamabad,5
5,106,Sana Javed,43.0,NaN,Male,2021-02-17,Karachi,12
9,110,Kamran Sheikh,36.0,NaN,Female,2020-07-23,Peshawar,21
12,113,NaN,36.0,119733.0,Female,2023-09-23,Karachi,8
34,135,Bilal Raza,25.0,NaN,Male,2019-05-05,Peshawar,24
36,137,NaN,49.0,54050.0,Female,2021-08-05,Lahore,28
38,139,NaN,53.0,93092.0,Male,2023-11-06,Peshwar,29
47,148,NaN,26.0,31220.0,Female,2022-06-26,Quetta,4
48,149,NaN,35.0,96307.0,Female,2019-09-29,Islamabad,29

In [78]:
df.dropna(subset = ["Customer_Name"] , inplace = True)

In [81]:
df.shape

(45, 8)

In [82]:
df.isnull().sum()

Customer_ID      0
Customer_Name    0
Age              1
Salary           3
Gender           0
Date_Joined      0
City             0
Purchases        0
dtype: int64

In [87]:
df["Age"].unique()

array([999.,  27.,  36.,  48.,  nan,  43.,  38.,  40.,  24.,  45.,  26.,
        42.,  25.,  30.,  49.,  22.,  -5.,  54.,  55.,  37.,  52.,  28.,
        46.,  53.,  47.])

In [88]:
df["Age"].dtype

dtype('float64')