In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\countries.csv")

In [6]:
df = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Countries.txt")
df

        Country  Region  Population  GDP_per_capita
0      Pakistan    Asia   240000000            1500
1         India    Asia  1400000000            2500
2         China    Asia  1410000000           12000
3       Germany  Europe    83000000           48000
4        France  Europe    67000000           45000
..          ...     ...         ...             ...
91       Rwanda  Africa    14000000             900
92      Burundi  Africa    13000000             300
93     Cameroon  Africa    28000000            1600
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

[96 rows x 4 columns]

In [8]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\asifb\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [16]:
df =pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\countries.xlsx",sheet_name = "Sheet2",header = 1) # mention sheet name to get excat sheet from excel
df

,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
0,USA,North America,50000,8133
1,China,Asia,11000,2300
2,Japan,Asia,6500,845
3,Germany,Europe,2500,3350
4,India,Asia,5000,880
5,UK,Europe,3000,310
6,France,Europe,2800,2436
7,Italy,Europe,2000,2451
8,Canada,North America,2200,77
9,Brazil,South America,1800,130
10,Australia,Oceania,1600,280
11,South Korea,Asia,2100,104
12,Spain,Europe,1200,281
13,Mexico,North America,900,120
14,Indonesia,Asia,850,78
15,Turkey,Asia,700,540
16,Netherlands,Europe,1500,612
17,Switzerland,Europe,1900,1040
18,Saudi Arabia,Asia,800,323
19,UAE,Asia,600,75
20,Singapore,Asia,700,4
21,Hong Kong,Asia,4500,13
22,Sweden,Europe,900,125
23,Norway,Europe,850,366
24,Denmark,Europe,650,66
25,Finland,Europe,500,49
26,Poland,Europe,450,228
27,Belgium,Europe,800,227
28,Austria,Europe,550,280
29,Ireland,Europe,1200,12
30,Portugal,Europe,300,383
31,Greece,Europe,250,114
32,Czech Republic,Europe,200,9
33,Hungary,Europe,150,94
34,Romania,Europe,120,103
35,Ukraine,Europe,100,27
36,Pakistan,Asia,90,64
37,Bangladesh,Asia,80,14
38,Vietnam,Asia,300,380
39,Thailand,Asia,600,234
40,Philippines,Asia,400,156
41,Malaysia,Asia,500,38
42,New Zealand,Oceania,200,7
43,South Africa,Africa,400,125
44,Nigeria,Africa,120,21
45,Egypt,Africa,180,80
46,Kenya,Africa,90,6
47,Morocco,Africa,100,22
48,Algeria,Africa,110,174
49,Ethiopia,Africa,60,3
50,Ghana,Africa,70,8
51,Tanzania,Africa,65,1
52,Uganda,Africa,55,3
53,Sudan,Africa,40,23
54,Angola,Africa,85,382
55,Argentina,South America,350,61
56,Chile,South America,300,9
57,Peru,South America,220,34
58,Colombia,South America,280,4
59,Venezuela,South America,90,161
60,Bolivia,South America,60,34
61,Ecuador,South America,80,0
62,Paraguay,South America,50,8
63,Uruguay,South America,120,0
64,Cuba,North America,40,500
65,Dominican Republic,North America,70,0
66,Guatemala,North America,60,0
67,Honduras,North America,40,0
68,El Salvador,North America,45,0
69,Nicaragua,North America,35,0
70,Costa Rica,North America,90,0
71,Panama,North America,150,0
72,Luxembourg,Europe,950,2
73,Iceland,Europe,60,0
74,Slovakia,Europe,130,0
75,Slovenia,Europe,140,3
76,Croatia,Europe,120,7
77,Serbia,Europe,110,13
78,Bulgaria,Europe,100,40
79,Latvia,Europe,90,6
80,Lithuania,Europe,95,5
81,Estonia,Europe,85,0
82,Qatar,Asia,700,56
83,Kuwait,Asia,650,79
84,Oman,Asia,300,17
85,Jordan,Asia,120,2
86,Iran,Asia,500,340
87,Iraq,Asia,150,96
88,Israel,Asia,900,12
89,Lebanon,Asia,60,287
90,Myanmar,Asia,70,7
91,Cambodia,Asia,65,0
92,Laos,Asia,50,0
93,Mongolia,Asia,55,3
94,Nepal,Asia,45,0
95,Sri Lanka,Asia,80,15
96,Sri Lanka,Asia,80,15

In [17]:
pd.set_option("display.max.rows",98)      # to get all rows in the data set

In [18]:
df.info()      # to get summary

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 97 non-null     str
 1   Region                  97 non-null     str
 2   Stock_Market_Cap_BnUSD  97 non-null     int64
 3   Gold_Reserves_Tonnes    97 non-null     int64
dtypes: int64(2), str(2)
memory usage: 3.2 KB

In [20]:
df.shape

(97, 4)

In [31]:
df.head(10)              # starting 10 rows for last 10 use tail

   Country         Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0      USA  North America                   50000                  8133
1    China           Asia                   11000                  2300
2    Japan           Asia                    6500                   845
3  Germany         Europe                    2500                  3350
4    India           Asia                    5000                   880
5       UK         Europe                    3000                   310
6   France         Europe                    2800                  2436
7    Italy         Europe                    2000                  2451
8   Canada  North America                    2200                    77
9   Brazil  South America                    1800                   130

In [32]:
df["Country"][0:10]

0        USA
1      China
2      Japan
3    Germany
4      India
5         UK
6     France
7      Italy
8     Canada
9     Brazil
Name: Country, dtype: str

In [33]:
df.loc[9]

Country                          Brazil
Region                    South America
Stock_Market_Cap_BnUSD             1800
Gold_Reserves_Tonnes                130
Name: 9, dtype: object

In [36]:
df[df["Country"] == "Japan"]

  Country Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
2   Japan   Asia                    6500                   845

#### Filtering

In [40]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\all data.xlsx" ,header = 1)
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
0,1,CHN,China,Beijing,Asia,1346563138,1319631875,1252303718,1184975561,1009922353,875266039,740609725,605953412,9706961,138.72
1,2,IND,India,New Delhi,Asia,251996221,246956296,234356485,221756674,188997165,163797543,138597921,113398299,3287590,76.65
2,3,USA,United States,"Washington, D.C.",North America,170967415,167548066,158999695,150451325,128225561,111128819,94032078,76935336,9372610,18.24
3,4,IDN,Indonesia,Jakarta,Asia,1098158599,1076195427,1021287497,966379567,823618949,713803089,603987229,494171369,1904569,576.59
4,5,PAK,Pakistan,Islamabad,Asia,79427434,77838885,73867513,69896141,59570575,51627832,43685088,35742345,881912,90.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,LSO,Lesotho,Maseru,Africa,57805104,56649001,53758746,50868491,43353828,37573317,31792807,26012296,30355,1904.30
146,147,SVN,Slovenia,Ljubljana,Europe,72970767,71511351,67862813,64214274,54728075,47430998,40133921,32836845,20273,3599.41
147,148,GNB,Guinea-Bissau,Bissau,Africa,45076770,44175234,41921396,39667557,33807577,29299900,24792223,20284546,36125,1247.80
148,149,MKD,North Macedonia,Skopje,Europe,21902250,21464205,20369092,19273980,16426687,14236462,12046237,9856012,25713,851.80
149,150,LVA,Latvia,Riga,Europe,21970209,21530804,20432294,19333783,16477656,14280635,12083614,9886594,64589,340.15

In [43]:
df[df["Rank"] <= 10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
0,1,CHN,China,Beijing,Asia,1346563138,1319631875,1252303718,1184975561,1009922353,875266039,740609725,605953412,9706961,138.72
1,2,IND,India,New Delhi,Asia,251996221,246956296,234356485,221756674,188997165,163797543,138597921,113398299,3287590,76.65
2,3,USA,United States,"Washington, D.C.",North America,170967415,167548066,158999695,150451325,128225561,111128819,94032078,76935336,9372610,18.24
3,4,IDN,Indonesia,Jakarta,Asia,1098158599,1076195427,1021287497,966379567,823618949,713803089,603987229,494171369,1904569,576.59
4,5,PAK,Pakistan,Islamabad,Asia,79427434,77838885,73867513,69896141,59570575,51627832,43685088,35742345,881912,90.06
5,6,NGA,Nigeria,Abuja,Africa,163440770,160171954,151999916,143827877,122580577,106236500,89892423,73548346,923768,176.93
6,7,BRA,Brazil,Brasilia,South America,277645921,272093002,258210706,244328410,208234440,180469848,152705256,124940664,8515767,32.60
7,8,BGD,Bangladesh,Dhaka,Asia,441101090,432279068,410224013,388168959,330825817,286715708,242605599,198495490,147570,2989.10
8,9,RUS,Russia,Moscow,Europe,596689023,584755242,554920791,525086340,447516767,387847864,328178962,268510060,17098242,34.90
9,10,MEX,Mexico,Mexico City,North America,75380729,73873114,70104077,66335041,56535546,48997473,41459400,33921328,1964375,38.37

In [44]:
Specific = ["Brazil","Nigeria"]
df[df["Country"].isin(Specific)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
5,6,NGA,Nigeria,Abuja,Africa,163440770,160171954,151999916,143827877,122580577,106236500,89892423,73548346,923768,176.93
6,7,BRA,Brazil,Brasilia,South America,277645921,272093002,258210706,244328410,208234440,180469848,152705256,124940664,8515767,32.60

In [46]:
df[df["Country"].str.contains("United")]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
2,3,USA,United States,"Washington, D.C.",North America,170967415,167548066,158999695,150451325,128225561,111128819,94032078,76935336,9372610,18.24
20,21,GBR,United Kingdom,London,Europe,52078423,51036854,48432933,45829012,39058817,33850974,28643132,23435290,242900,214.40
91,92,ARE,United Arab Emirates,Abu Dhabi,Asia,9417577,9229225,8758346,8287467,7063182,6121425,5179667,4237909,83600,112.65

In [5]:
# Data frame 
df = pd.DataFrame([11,12,13,14,15],columns = ["Wow"])
print(df)

   Wow
0   11
1   12
2   13
3   14
4   15

In [11]:
data = {
"Name": ["Shahzaib","Arfa", "Asad","Asif","Shireen","Assar"],
 "Age" : [23,30,30,33,56,57] ,  
"Salary" : [25000,30000,40000,600000,25000,322000]
}

In [12]:
df = pd.DataFrame(data)
df

       Name  Age  Salary
0  Shahzaib   23   25000
1      Arfa   30   30000
2      Asad   30   40000
3      Asif   33  600000
4   Shireen   56   25000
5     Assar   57  322000

In [13]:
df.head(2)                # give top rows of the data

       Name  Age  Salary
0  Shahzaib   23   25000
1      Arfa   30   30000

In [16]:
print(df.columns)
df.shape     # size of data set

Index(['Name', 'Age', 'Salary'], dtype='str')

(6, 3)

In [22]:
df.rename(columns = {"Salary":"Take_Home"},inplace = True)             # to change the columns name 
                                            # we have put inplace so the data would change here, or we can assign a varriable and call it

In [23]:
df

       Name  Age  Take_Home
0  Shahzaib   23      25000
1      Arfa   30      30000
2      Asad   30      40000
3      Asif   33     600000
4   Shireen   56      25000
5     Assar   57     322000

In [24]:
df.describe()

             Age      Take_Home
count   6.000000       6.000000
mean   38.166667  173666.666667
std    14.579666  239363.043653
min    23.000000   25000.000000
25%    30.000000   26250.000000
50%    31.500000   35000.000000
75%    50.250000  251500.000000
max    57.000000  600000.000000

In [26]:
df.to_csv("Test Data.csv")

In [28]:
import os           # to know where the data set is present 
print(os.getcwd())

C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Panda

In [29]:
df = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.csv")
df

        Country  Region  Population  GDP_per_capita
0      Pakistan    Asia   240000000            1500
1         India    Asia  1400000000            2500
2         China    Asia  1410000000           12000
3       Germany  Europe    83000000           48000
4        France  Europe    67000000           45000
..          ...     ...         ...             ...
91       Rwanda  Africa    14000000             900
92      Burundi  Africa    13000000             300
93     Cameroon  Africa    28000000            1600
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

[96 rows x 4 columns]

In [32]:
df[["Country","GDP_per_capita"]]               # to select required columns

        Country  GDP_per_capita
0      Pakistan            1500
1         India            2500
2         China           12000
3       Germany           48000
4        France           45000
..          ...             ...
91       Rwanda             900
92      Burundi             300
93     Cameroon            1600
94      Senegal            1800
95  Ivory Coast            2500

[96 rows x 2 columns]

In [36]:
df.loc[df.Country == "Senegal"]

    Country  Region  Population  GDP_per_capita
94  Senegal  Africa    18000000            1800

In [42]:
df.loc[df.Country.isin(["Senegal", "Ivory Coast"])]    # Loc--> Label/columns based indexing

        Country  Region  Population  GDP_per_capita
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

In [43]:
df.loc[(df.Region == "Africa") & (df.Population >= 2000000) & (df.GDP_per_capita > 2500)]

         Country  Region  Population  GDP_per_capita
11  South Africa  Africa    60000000            7000
41         Egypt  Africa   110000000            3500
47       Morocco  Africa    37000000            3500
48       Algeria  Africa    45000000            4000
50        Angola  Africa    35000000            3000
84      Botswana  Africa     2600000            7000
85       Namibia  Africa     2600000            5000

In [52]:
df.iloc[0:10]       # n-1 rows start:stop:step

     Country         Region  Population  GDP_per_capita
0   Pakistan           Asia   240000000            1500
1      India           Asia  1400000000            2500
2      China           Asia  1410000000           12000
3    Germany         Europe    83000000           48000
4     France         Europe    67000000           45000
5         UK         Europe    67000000           46000
6        USA  North America   331000000           70000
7     Canada  North America    38000000           52000
8     Brazil  South America   215000000            9000
9  Argentina  South America    45000000           10000

In [53]:
df.loc[0:10]     # full 10 rows

      Country         Region  Population  GDP_per_capita
0    Pakistan           Asia   240000000            1500
1       India           Asia  1400000000            2500
2       China           Asia  1410000000           12000
3     Germany         Europe    83000000           48000
4      France         Europe    67000000           45000
5          UK         Europe    67000000           46000
6         USA  North America   331000000           70000
7      Canada  North America    38000000           52000
8      Brazil  South America   215000000            9000
9   Argentina  South America    45000000           10000
10    Nigeria         Africa   223000000            2200

### Data Filtering

In [61]:
df[(df["Population"] > 1000000000) & (df["GDP_per_capita"] > 3000)]

  Country Region  Population  GDP_per_capita
2   China   Asia  1410000000           12000

In [65]:
df.where(df["GDP_per_capita"] > 2000 , other = "Null")

        Country  Region  Population GDP_per_capita
0          Null    Null        Null           Null
1         India    Asia  1400000000           2500
2         China    Asia  1410000000          12000
3       Germany  Europe    83000000          48000
4        France  Europe    67000000          45000
..          ...     ...         ...            ...
91         Null    Null        Null           Null
92         Null    Null        Null           Null
93         Null    Null        Null           Null
94         Null    Null        Null           Null
95  Ivory Coast  Africa    28000000           2500

[96 rows x 4 columns]

In [66]:
data = {
"Name": ["Shahzaib","Arfa", "Asad","Asif","Shireen","Assar"],
 "Age" : [23,30,30,33,56,57] ,  
"Salary" : [25000,30000,40000,600000,25000,322000]
}

In [67]:
df = pd.DataFrame(data)
df

       Name  Age  Salary
0  Shahzaib   23   25000
1      Arfa   30   30000
2      Asad   30   40000
3      Asif   33  600000
4   Shireen   56   25000
5     Assar   57  322000

In [70]:
# Add new column 
df["Team"] = ["Finance" , "HR", "Accounting","Sales","HR","Marketing"]
df

       Name  Age  Salary        Team
0  Shahzaib   23   25000     Finance
1      Arfa   30   30000          HR
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [71]:
df["Bonus"] = df["Salary"] * 0.25
df

       Name  Age  Salary        Team     Bonus
0  Shahzaib   23   25000     Finance    6250.0
1      Arfa   30   30000          HR    7500.0
2      Asad   30   40000  Accounting   10000.0
3      Asif   33  600000       Sales  150000.0
4   Shireen   56   25000          HR    6250.0
5     Assar   57  322000   Marketing   80500.0

In [72]:
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Age  Salary        Team     Bonus     Total
0  Shahzaib   23   25000     Finance    6250.0   31250.0
1      Arfa   30   30000          HR    7500.0   37500.0
2      Asad   30   40000  Accounting   10000.0   50000.0
3      Asif   33  600000       Sales  150000.0  750000.0
4   Shireen   56   25000          HR    6250.0   31250.0
5     Assar   57  322000   Marketing   80500.0  402500.0

In [78]:
# Adding new rows
df.loc[len(df)] = ["Ali",25,30000,"IT",6000,36000]
df

       Name  Age  Salary        Team     Bonus     Total
0  Shahzaib   23   25000     Finance    6250.0   31250.0
1      Arfa   30   30000          HR    7500.0   37500.0
2      Asad   30   40000  Accounting   10000.0   50000.0
3      Asif   33  600000       Sales  150000.0  750000.0
4   Shireen   56   25000          HR    6250.0   31250.0
5     Assar   57  322000   Marketing   80500.0  402500.0
6       Ali   25   30000          IT    6000.0   36000.0
7       Ali   25   30000          IT    6000.0   36000.0

In [81]:
# Updating a value 
df.loc[0,"Team"] = "CEO"
df.loc[0,"Salary"] = 1000000
df

       Name  Age   Salary        Team     Bonus     Total
0  Shahzaib   23  1000000         CEO    6250.0   31250.0
1      Arfa   30    30000          HR    7500.0   37500.0
2      Asad   30    40000  Accounting   10000.0   50000.0
3      Asif   33   600000       Sales  150000.0  750000.0
4   Shireen   56    25000          HR    6250.0   31250.0
5     Assar   57   322000   Marketing   80500.0  402500.0
6       Ali   25    30000          IT    6000.0   36000.0
7       Ali   25    30000          IT    6000.0   36000.0

In [85]:
#deleting row 
df.drop(df[df.Name == "Ali"].index,inplace = True)
df

       Name  Age   Salary        Team     Bonus     Total
0  Shahzaib   23  1000000         CEO    6250.0   31250.0
1      Arfa   30    30000          HR    7500.0   37500.0
2      Asad   30    40000  Accounting   10000.0   50000.0
3      Asif   33   600000       Sales  150000.0  750000.0
4   Shireen   56    25000          HR    6250.0   31250.0
5     Assar   57   322000   Marketing   80500.0  402500.0

In [86]:
df.drop("Bonus",axis =1 , inplace = True)
df

       Name  Age   Salary        Team     Total
0  Shahzaib   23  1000000         CEO   31250.0
1      Arfa   30    30000          HR   37500.0
2      Asad   30    40000  Accounting   50000.0
3      Asif   33   600000       Sales  750000.0
4   Shireen   56    25000          HR   31250.0
5     Assar   57   322000   Marketing  402500.0

In [88]:
# df.drop("Bonus","Team" axis =1 , inplace = True)    --> to delete multiple columns 
# df.drop(1,axis = 0)   --> to delete rows

In [89]:
# sorting data 
df.sort_values("Age")   # by default it sorts in acending

       Name  Age   Salary        Team     Total
0  Shahzaib   23  1000000         CEO   31250.0
1      Arfa   30    30000          HR   37500.0
2      Asad   30    40000  Accounting   50000.0
3      Asif   33   600000       Sales  750000.0
4   Shireen   56    25000          HR   31250.0
5     Assar   57   322000   Marketing  402500.0

In [91]:
df.sort_values("Age", ascending = False)          # descending order

       Name  Age   Salary        Team     Total
5     Assar   57   322000   Marketing  402500.0
4   Shireen   56    25000          HR   31250.0
3      Asif   33   600000       Sales  750000.0
1      Arfa   30    30000          HR   37500.0
2      Asad   30    40000  Accounting   50000.0
0  Shahzaib   23  1000000         CEO   31250.0

In [93]:
df["DOJ"] = ["2024-01-01","2024-01-01","2024-01-02","2024-01-03","2024-01-04","2025-02-06"]
df

       Name  Age   Salary        Team     Total         DOJ
0  Shahzaib   23  1000000         CEO   31250.0  2024-01-01
1      Arfa   30    30000          HR   37500.0  2024-01-01
2      Asad   30    40000  Accounting   50000.0  2024-01-02
3      Asif   33   600000       Sales  750000.0  2024-01-03
4   Shireen   56    25000          HR   31250.0  2024-01-04
5     Assar   57   322000   Marketing  402500.0  2025-02-06

In [95]:
# formating date time 
df["DOJ"] = pd.to_datetime(df["DOJ"])
df

       Name  Age   Salary        Team     Total        DOJ
0  Shahzaib   23  1000000         CEO   31250.0 2024-01-01
1      Arfa   30    30000          HR   37500.0 2024-01-01
2      Asad   30    40000  Accounting   50000.0 2024-01-02
3      Asif   33   600000       Sales  750000.0 2024-01-03
4   Shireen   56    25000          HR   31250.0 2024-01-04
5     Assar   57   322000   Marketing  402500.0 2025-02-06

In [3]:
data = [
    {"Name": "Shahzaib", "Age": 23, "Salary": 1000000, "Team": "CEO", "Total": 31250.0},
    {"Name": "Arfa", "Age": 30, "Salary": 30000, "Team": "HR", "Total": 37500.0},
    {"Name": "Asad", "Age": 30, "Salary": 40000, "Team": "Accounting", "Total": 50000.0},
    {"Name": "Asif", "Age": 33, "Salary": 600000, "Team": "Sales", "Total": 750000.0},
    {"Name": "Shireen", "Age": 56, "Salary": 25000, "Team": "HR", "Total": 31250.0},
    {"Name": "Assar", "Age": 57, "Salary": 322000, "Team": "Marketing", "Total": 402500.0}
]

In [5]:
df = pd.DataFrame(data)
df

       Name  Age   Salary        Team     Total
0  Shahzaib   23  1000000         CEO   31250.0
1      Arfa   30    30000          HR   37500.0
2      Asad   30    40000  Accounting   50000.0
3      Asif   33   600000       Sales  750000.0
4   Shireen   56    25000          HR   31250.0
5     Assar   57   322000   Marketing  402500.0

In [6]:
df["DOJ"] = ["2024-01-01","2024-01-01","2024-01-02","2024-01-03","2024-01-04","2025-02-06"]
df

       Name  Age   Salary        Team     Total         DOJ
0  Shahzaib   23  1000000         CEO   31250.0  2024-01-01
1      Arfa   30    30000          HR   37500.0  2024-01-01
2      Asad   30    40000  Accounting   50000.0  2024-01-02
3      Asif   33   600000       Sales  750000.0  2024-01-03
4   Shireen   56    25000          HR   31250.0  2024-01-04
5     Assar   57   322000   Marketing  402500.0  2025-02-06

In [7]:
df["DOJ"] = pd.to_datetime(df["DOJ"])
df

       Name  Age   Salary        Team     Total        DOJ
0  Shahzaib   23  1000000         CEO   31250.0 2024-01-01
1      Arfa   30    30000          HR   37500.0 2024-01-01
2      Asad   30    40000  Accounting   50000.0 2024-01-02
3      Asif   33   600000       Sales  750000.0 2024-01-03
4   Shireen   56    25000          HR   31250.0 2024-01-04
5     Assar   57   322000   Marketing  402500.0 2025-02-06

In [8]:
df["DOJ"].dtype

dtype('<M8[us]')

In [9]:
df["DOJ"] .dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
5    2025
Name: DOJ, dtype: int32

In [10]:
df["DOJ"].dt.month

0    1
1    1
2    1
3    1
4    1
5    2
Name: DOJ, dtype: int32

In [11]:
df["Month"] = df["DOJ"].dt.month
df

       Name  Age   Salary        Team     Total        DOJ  Month
0  Shahzaib   23  1000000         CEO   31250.0 2024-01-01      1
1      Arfa   30    30000          HR   37500.0 2024-01-01      1
2      Asad   30    40000  Accounting   50000.0 2024-01-02      1
3      Asif   33   600000       Sales  750000.0 2024-01-03      1
4   Shireen   56    25000          HR   31250.0 2024-01-04      1
5     Assar   57   322000   Marketing  402500.0 2025-02-06      2

In [12]:
df.isnull()

    Name    Age  Salary   Team  Total    DOJ  Month
0  False  False   False  False  False  False  False
1  False  False   False  False  False  False  False
2  False  False   False  False  False  False  False
3  False  False   False  False  False  False  False
4  False  False   False  False  False  False  False
5  False  False   False  False  False  False  False

### Handling Null values

In [13]:
import numpy as np

In [15]:
df.loc[df.Name == "Arfa" , "Salary" ] = np.nan                     # this creates a null value in the salary of arfa 
df

       Name  Age     Salary        Team     Total        DOJ  Month
0  Shahzaib   23  1000000.0         CEO   31250.0 2024-01-01      1
1      Arfa   30        NaN          HR   37500.0 2024-01-01      1
2      Asad   30    40000.0  Accounting   50000.0 2024-01-02      1
3      Asif   33   600000.0       Sales  750000.0 2024-01-03      1
4   Shireen   56    25000.0          HR   31250.0 2024-01-04      1
5     Assar   57   322000.0   Marketing  402500.0 2025-02-06      2

In [16]:
df.isnull().sum()

Name      0
Age       0
Salary    1
Team      0
Total     0
DOJ       0
Month     0
dtype: int64

In [17]:
df.loc[df.Name == "Assar" , "Team"] = np.nan
df.isnull().sum()

Name      0
Age       0
Salary    1
Team      1
Total     0
DOJ       0
Month     0
dtype: int64

In [18]:
# filling the null values 
df.fillna(0)

       Name  Age     Salary        Team     Total        DOJ  Month
0  Shahzaib   23  1000000.0         CEO   31250.0 2024-01-01      1
1      Arfa   30        0.0          HR   37500.0 2024-01-01      1
2      Asad   30    40000.0  Accounting   50000.0 2024-01-02      1
3      Asif   33   600000.0       Sales  750000.0 2024-01-03      1
4   Shireen   56    25000.0          HR   31250.0 2024-01-04      1
5     Assar   57   322000.0           0  402500.0 2025-02-06      2

In [20]:
df.loc[df.Name == "Assar" , "Team"] = "Cashier"
df.loc[df.Name == "Arfa" ,"Salary" ] = 700000
df

       Name  Age     Salary        Team     Total        DOJ  Month
0  Shahzaib   23  1000000.0         CEO   31250.0 2024-01-01      1
1      Arfa   30   700000.0          HR   37500.0 2024-01-01      1
2      Asad   30    40000.0  Accounting   50000.0 2024-01-02      1
3      Asif   33   600000.0       Sales  750000.0 2024-01-03      1
4   Shireen   56    25000.0          HR   31250.0 2024-01-04      1
5     Assar   57   322000.0     Cashier  402500.0 2025-02-06      2

### Aggregation

In [23]:
df["Team"].value_counts()           # it counts the total number of members in a team

Team
HR            2
CEO           1
Accounting    1
Sales         1
Cashier       1
Name: count, dtype: int64

In [26]:
df[df["Month"]== 1].value_counts()              # counting total values in month 1 (jan)

Name      Age  Salary     Team        Total     DOJ         Month
Shahzaib  23   1000000.0  CEO         31250.0   2024-01-01  1        1
Arfa      30   700000.0   HR          37500.0   2024-01-01  1        1
Asad      30   40000.0    Accounting  50000.0   2024-01-02  1        1
Asif      33   600000.0   Sales       750000.0  2024-01-03  1        1
Shireen   56   25000.0    HR          31250.0   2024-01-04  1        1
Name: count, dtype: int64

In [29]:
df.groupby("Month")["Salary"].sum()    # we can use mean also

Month
1    2365000.0
2     322000.0
Name: Salary, dtype: float64

In [35]:
df.groupby("Month").agg({"Salary" : "mean" , "Name" : "count"})

         Salary  Name
Month
1      473000.0     5
2      322000.0     1

### Concatenate and merge data frames (joins)

In [36]:
data = {"Name" : ["Ali" , "Shahzaib" , "Asad", "Asif"] , "ID" : [1,2,3,4]}

In [37]:
df1 = pd.DataFrame(data)
df1

       Name  ID
0       Ali   1
1  Shahzaib   2
2      Asad   3
3      Asif   4

In [39]:
df2 = pd.DataFrame({"ID" : [1,2,2,3,4,5] , "Score" : [88,78,77,89,59,100]})

In [44]:
pd.concat([df1,df2] , axis = 0)      # this only appended row wise / top on top

       Name  ID  Score
0       Ali   1    NaN
1  Shahzaib   2    NaN
2      Asad   3    NaN
3      Asif   4    NaN
0       NaN   1   88.0
1       NaN   2   78.0
2       NaN   2   77.0
3       NaN   3   89.0
4       NaN   4   59.0
5       NaN   5  100.0

In [46]:
pd.concat([df1,df2] , axis = 1)       # join through coulmns/ side on side

       Name   ID  ID  Score
0       Ali  1.0   1     88
1  Shahzaib  2.0   2     78
2      Asad  3.0   2     77
3      Asif  4.0   3     89
4       NaN  NaN   4     59
5       NaN  NaN   5    100

### Merge (join)

In [48]:
pd.merge(df1,df2, how = "inner" , on = "ID")

       Name  ID  Score
0       Ali   1     88
1  Shahzaib   2     78
2  Shahzaib   2     77
3      Asad   3     89
4      Asif   4     59

In [49]:
pd.merge(df1,df2, how = "left" , on = "ID")

       Name  ID  Score
0       Ali   1     88
1  Shahzaib   2     78
2  Shahzaib   2     77
3      Asad   3     89
4      Asif   4     59

In [51]:
pd.merge(df1,df2, how = "right" , on = "ID")   # here ID is in both tables, so we use simple on, if  both tables had diffrent names, then we can use left on and righton

       Name  ID  Score
0       Ali   1     88
1  Shahzaib   2     78
2  Shahzaib   2     77
3      Asad   3     89
4      Asif   4     59
5       NaN   5    100

In [1]:
import pandas as pd

In [4]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.xlsx", header =1 )
df

        Country  Region  Population  GDP_per_capita
0      Pakistan    Asia   240000000            1500
1         India    Asia  1400000000            2500
2         China    Asia  1410000000           12000
3       Germany  Europe    83000000           48000
4        France  Europe    67000000           45000
..          ...     ...         ...             ...
91       Rwanda  Africa    14000000             900
92      Burundi  Africa    13000000             300
93     Cameroon  Africa    28000000            1600
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

[96 rows x 4 columns]

In [7]:
df[df["Region"] =="Africa"]

         Country  Region  Population  GDP_per_capita
10       Nigeria  Africa   223000000            2200
11  South Africa  Africa    60000000            7000
41         Egypt  Africa   110000000            3500
42      Ethiopia  Africa   120000000            1000
43         Kenya  Africa    55000000            2000
44      Tanzania  Africa    65000000            1500
45        Uganda  Africa    48000000             900
46         Ghana  Africa    33000000            2500
47       Morocco  Africa    37000000            3500
48       Algeria  Africa    45000000            4000
49         Sudan  Africa    45000000             800
50        Angola  Africa    35000000            3000
84      Botswana  Africa     2600000            7000
85       Namibia  Africa     2600000            5000
86        Zambia  Africa    20000000            1500
87      Zimbabwe  Africa    16000000            2000
88        Malawi  Africa    20000000             800
89    Mozambique  Africa    33000000             700
90    Madagascar  Africa    30000000             600
91        Rwanda  Africa    14000000             900
92       Burundi  Africa    13000000             300
93      Cameroon  Africa    28000000            1600
94       Senegal  Africa    18000000            1800
95   Ivory Coast  Africa    28000000            2500

In [11]:
df.rename(columns = {"GDP_per_capita" : "GDP"} , inplace = True)
df

        Country  Region  Population    GDP
0      Pakistan    Asia   240000000   1500
1         India    Asia  1400000000   2500
2         China    Asia  1410000000  12000
3       Germany  Europe    83000000  48000
4        France  Europe    67000000  45000
..          ...     ...         ...    ...
91       Rwanda  Africa    14000000    900
92      Burundi  Africa    13000000    300
93     Cameroon  Africa    28000000   1600
94      Senegal  Africa    18000000   1800
95  Ivory Coast  Africa    28000000   2500

[96 rows x 4 columns]

In [13]:
df.loc[(df.Region == "Asia") & (df.Population > 15000000) & (df.GDP > 1000)]

         Country Region  Population    GDP
0       Pakistan   Asia   240000000   1500
1          India   Asia  1400000000   2500
2          China   Asia  1410000000  12000
14         Japan   Asia   125000000  42000
15    Bangladesh   Asia   170000000   2800
16     Indonesia   Asia   275000000   5000
17   Philippines   Asia   115000000   3500
18       Vietnam   Asia   100000000   4000
19      Thailand   Asia    70000000   7500
51  Saudi Arabia   Asia    36000000  27000
56        Turkey   Asia    85000000  10000
57          Iran   Asia    88000000   5000
58          Iraq   Asia    45000000   4500

In [14]:
data = {
    "Name": [
        "Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"
    ],
    "Salary": [
        95000, 72000, 105000, 88000, 62000, 
        115000, 54000, 91000, 78000, 83000
    ],
    "Position": [
        "Software Engineer", "Data Scientist", "Project Manager", "UX Designer", "Intern",
        "CTO", "Marketing Associate", "DevOps Engineer", "Sales Lead", "Product Owner"
    ]
}

In [15]:
df = pd.DataFrame(data)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [16]:
df["Bonus"] = df["Salary"] * 0.25
df

       Name  Salary             Position    Bonus
0      Liam   95000    Software Engineer  23750.0
1    Sophia   72000       Data Scientist  18000.0
2      Noah  105000      Project Manager  26250.0
3      Emma   88000          UX Designer  22000.0
4    Oliver   62000               Intern  15500.0
5       Ava  115000                  CTO  28750.0
6     Ethan   54000  Marketing Associate  13500.0
7  Isabella   91000      DevOps Engineer  22750.0
8     Lucas   78000           Sales Lead  19500.0
9       Mia   83000        Product Owner  20750.0

In [17]:
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Salary             Position    Bonus     Total
0      Liam   95000    Software Engineer  23750.0  118750.0
1    Sophia   72000       Data Scientist  18000.0   90000.0
2      Noah  105000      Project Manager  26250.0  131250.0
3      Emma   88000          UX Designer  22000.0  110000.0
4    Oliver   62000               Intern  15500.0   77500.0
5       Ava  115000                  CTO  28750.0  143750.0
6     Ethan   54000  Marketing Associate  13500.0   67500.0
7  Isabella   91000      DevOps Engineer  22750.0  113750.0
8     Lucas   78000           Sales Lead  19500.0   97500.0
9       Mia   83000        Product Owner  20750.0  103750.0

In [24]:
avg = df["Total"].mean()
print(avg)
df[df["Total"] > avg]

105375.0

       Name  Salary           Position    Bonus     Total
0      Liam   95000  Software Engineer  23750.0  118750.0
2      Noah  105000    Project Manager  26250.0  131250.0
3      Emma   88000        UX Designer  22000.0  110000.0
5       Ava  115000                CTO  28750.0  143750.0
7  Isabella   91000    DevOps Engineer  22750.0  113750.0

In [26]:
df.isnull().sum()

Name        0
Salary      0
Position    0
Bonus       0
Total       0
dtype: int64

In [31]:
df[df["Position"].str.contains("Engineer")]

       Name  Salary           Position    Bonus     Total
0      Liam   95000  Software Engineer  23750.0  118750.0
7  Isabella   91000    DevOps Engineer  22750.0  113750.0

In [32]:
df = df.drop(columns = ["Total"])
df

       Name  Salary             Position    Bonus
0      Liam   95000    Software Engineer  23750.0
1    Sophia   72000       Data Scientist  18000.0
2      Noah  105000      Project Manager  26250.0
3      Emma   88000          UX Designer  22000.0
4    Oliver   62000               Intern  15500.0
5       Ava  115000                  CTO  28750.0
6     Ethan   54000  Marketing Associate  13500.0
7  Isabella   91000      DevOps Engineer  22750.0
8     Lucas   78000           Sales Lead  19500.0
9       Mia   83000        Product Owner  20750.0