In [7]:
import pandas as pd 
import numpy as np 

from sklearn.linear_model import LinearRegression

In [22]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Companies data MICE.xlsx")
df.sample(5)

    R&D Spend  Administration  Marketing Spend       State     Profit
28   66051.52       182645.56        118148.20     Florida  103282.38
49       0.00       116983.80         45173.06  California   14681.40
2   153441.51       101145.55        407934.54     Florida  191050.39
45    1000.23       124153.04          1903.93    New York   64926.08
5   131876.90        99814.71        362861.36    New York  156991.12

In [23]:
df[["R&D Spend" , "Administration" , "Marketing Spend" ,"Profit"]]= np.round(df[["R&D Spend" , "Administration" , "Marketing Spend" ,"Profit"]]/10000,2)

In [24]:
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend     State  Profit
15      11.45           12.26            26.18  New York   12.99
38       2.02            6.59            18.53  New York    8.12
22       7.40           12.28            30.33   Florida   11.04
18       9.17           11.42            29.49   Florida   12.43
7       13.03           14.55            32.39   Florida   15.58

In [25]:
df.drop(columns = ["State"] , inplace = True)

In [33]:
df= df.iloc[:,0 :3]
df

    R&D Spend  Administration  Marketing Spend
15      11.45           12.26            26.18
38        NaN            6.59            18.53
22       7.40           12.28            30.33
18       9.17             NaN            29.49
7       13.03           14.55              NaN

In [32]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan