In [7]:
from sklearn.preprocessing import LabelEncoder 
import pandas as pd

In [5]:
data = {"Name" : ["Asif", "Shahzaib" , "Salman", "Arfa" ,"Sahran" , "Shireen" , "Inza" ], 
        "Gender" : ["Male" ,"Male" ,"Male" ,"Female" ,"Male" , "Female","Female"]}

In [7]:
df= pd.DataFrame(data)

In [8]:
le = LabelEncoder()

In [9]:
label = df.copy()

In [13]:
label["Gender_Encoded"] = le.fit_transform(label["Gender"])

In [15]:
label["City"] = ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta"]

In [16]:
label = pd.get_dummies(label , columns = ["City"] , dtype = int)
print(label)

       Name  Gender  Gender_Encoded  City_Islamabad  City_Karachi  \
0      Asif    Male               1               0             1
1  Shahzaib    Male               1               0             0
2    Salman    Male               1               1             0
3      Arfa  Female               0               0             1
4    Sahran    Male               1               0             0
5   Shireen  Female               0               0             0
6      Inza  Female               0               0             0

   City_Lahore  City_Peshawar  City_Quetta
0            0              0            0
1            1              0            0
2            0              0            0
3            0              0            0
4            1              0            0
5            0              1            0
6            0              0            1

In [30]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [18]:
data = {
    "Study hours" :[10, 15, 20, 30] , "Marks" : [ 50 , 60 ,70 ,80] 
}

In [20]:
df = pd.DataFrame(data)

In [21]:
SS = StandardScaler()

In [22]:
Scaled = SS.fit_transform(df)

In [23]:
print(pd.DataFrame(Scaled , columns = ["Study hours" , "Marks"] ))

   Study hours     Marks
0    -1.183216 -1.341641
1    -0.507093 -0.447214
2     0.169031  0.447214
3     1.521278  1.341641

In [24]:
MM = MinMaxScaler()

In [26]:
MM = MM.fit_transform(df)

In [27]:
print(pd.DataFrame(MM , columns = ["Study Hours" , "Marks"]))

   Study Hours     Marks
0         0.00  0.000000
1         0.25  0.333333
2         0.50  0.666667
3         1.00  1.000000

In [33]:
df[df["Marks"] == 70]["Study hours"]

2    20
Name: Study hours, dtype: int64

In [36]:
df[["Study hours"][0:3]]

   Study hours
0           10
1           15
2           20
3           30

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X = df[["Study hours"]]
Y = df[["Marks"]]

In [41]:
X_train , X_test, Y_train ,Y_test = train_test_split(X,Y, test_size = 0.25 , random_state = 42)

In [42]:
print("Training Data")
print(X_train)
print("Testing Data")
print(X_test)
print("-" * 50)
print("Training Data")
print(Y_train)
print("Testing Data")
print(Y_test)

Training Data
   Study hours
3           30
0           10
2           20
Testing Data
   Study hours
1           15
--------------------------------------------------
Training Data
   Marks
3     80
0     50
2     70
Testing Data
   Marks
1     60

In [43]:
df

   Study hours  Marks
0           10     50
1           15     60
2           20     70
3           30     80

In [3]:
data = {"Name" : ["Asif", "Shahzaib" , "Salman", "Arfa" ,"Sahran" , "Shireen" , "Inza" ], 
        "Gender" : ["Male" ,"Male" ,"Male" ,"Female" ,"Male" , "Female","Female"]}

In [4]:
df = pd.DataFrame(data)
df

       Name  Gender
0      Asif    Male
1  Shahzaib    Male
2    Salman    Male
3      Arfa  Female
4    Sahran    Male
5   Shireen  Female
6      Inza  Female

In [8]:
le = LabelEncoder()

In [9]:
df["Gender Encoded"] = le.fit_transform(df["Gender"])

In [10]:
df["City"] = ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta"]

In [14]:
df = pd.get_dummies(df, columns = ["City"] , dtype = int)

In [15]:
df

,Name,Gender,Gender Encoded,City_Islamabad,City_Karachi,City_Lahore,City_Peshawar,City_Quetta
0,Asif,Male,1,0,1,0,0,0
1,Shahzaib,Male,1,0,0,1,0,0
2,Salman,Male,1,1,0,0,0,0
3,Arfa,Female,0,0,1,0,0,0
4,Sahran,Male,1,0,0,1,0,0
5,Shireen,Female,0,0,0,0,1,0
6,Inza,Female,0,0,0,0,0,1

In [16]:
data = { "Study_Hours" : [5 ,10 ,15 ,20] , "Marks" : [50,60,70,80]}

In [20]:
df = pd.DataFrame(data)

In [21]:
SS = StandardScaler()

In [24]:
print(pd.DataFrame(Scaled, columns = ["Study_Hours" , "Marks"]))

   Study_Hours     Marks
0    -1.341641 -1.341641
1    -0.447214 -0.447214
2     0.447214  0.447214
3     1.341641  1.341641

In [45]:
from sklearn.linear_model import LinearRegression

In [49]:
Model = LinearRegression()
X = [[5],[8],[9],[10], [11],[13],[15],[20]]
Y = [30,55,68,75,77,80,85,95]
Model.fit(X,Y)
hours = float(input("Enter number of hours you studied:"))
results = Model.predict([[hours]])[0]
print(f"Based on your given study hours {hours}, you probably would get {round(results,2)} marks")

Enter number of hours you studied: 10

Based on your given study hours 10.0, you probably would get 65.24 marks

In [50]:
from sklearn.linear_model import LogisticRegression

In [52]:
Model = LogisticRegression()
X = [[5],[8],[9],[10], [11],[13],[15],[20]]
Y = [0,0,0,0,1,1,1,1]
Model.fit(X,Y)
hours = float(input("Enter the number of hours:"))
results = Model.predict([[hours]])[0]

if results == 1:
    print(f"Based on your number of hours studied {hours}, you would get passed")
else :
    print(f"Based on your number of hours studied {hours} , you would get failed")

Enter the number of hours: 10

Based on your number of hours studied 10.0 , you would get failed

In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
Model = KNeighborsClassifier(n_neighbors = 3)
X = [[180, 6] , [190,7] , [200,8] ,[230,9] , [250,10] , [270 , 11] , [280,13],[290,14], [300,16] ]
Y= [0,0,0,0,1,1,1,1,1]

Model.fit(X,Y)
Weight = float(input("Enter your fruit's weight:"))
Size = float(input("Enter your fruit's size:"))

results = Model.predict([[Weight , Size]])[0]

if results == 0:
    print(f" Based on your given weight {Weight} and size {Size} this is likely an apple")
else :
    print(f"Based on your given weight {Weight} and size {Size} this is likely an orange")

Enter your fruit's weight: 222
Enter your fruit's size: 9.8

 Based on your given weight 222.0 and size 9.8 this is likely an apple