In [1]:
import pandas as pd

In [9]:
df =pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.xlsx", sheet_name ="Sheet3",header =2 )
df

,Unnamed: 0,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
0,NaN,USA,North America,50000,8133
1,NaN,China,Asia,11000,2300
2,NaN,Japan,Asia,6500,845
3,NaN,Germany,Europe,2500,3350
4,NaN,India,Asia,5000,880
5,NaN,UK,Europe,3000,310
6,NaN,France,Europe,2800,2436
7,NaN,Italy,Europe,2000,2451
8,NaN,Canada,North America,2200,77
9,NaN,Brazil,South America,1800,130
10,NaN,Australia,Oceania,1600,280
11,NaN,South Korea,Asia,2100,104
12,NaN,Spain,Europe,1200,281
13,NaN,Mexico,North America,900,120
14,NaN,Indonesia,Asia,850,78
15,NaN,Turkey,Asia,700,540
16,NaN,Netherlands,Europe,1500,612
17,NaN,Switzerland,Europe,1900,1040
18,NaN,Saudi Arabia,Asia,800,323

In [10]:
df.shape

(19, 5)

In [13]:
df = df.drop(df.columns[0],axis =1)
df

           Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0   North America                   50000                  8133
1            Asia                   11000                  2300
2            Asia                    6500                   845
3          Europe                    2500                  3350
4            Asia                    5000                   880
5          Europe                    3000                   310
6          Europe                    2800                  2436
7          Europe                    2000                  2451
8   North America                    2200                    77
9   South America                    1800                   130
10        Oceania                    1600                   280
11           Asia                    2100                   104
12         Europe                    1200                   281
13  North America                     900                   120
14           Asia                     850                    78
15           Asia                     700                   540
16         Europe                    1500                   612
17         Europe                    1900                  1040
18           Asia                     800                   323

In [15]:
df["Region"][0:3]

0    North America
1             Asia
2             Asia
Name: Region, dtype: str

In [19]:
df[df["Region"]== "Asia"]

   Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
1    Asia                   11000                  2300
2    Asia                    6500                   845
4    Asia                    5000                   880
11   Asia                    2100                   104
14   Asia                     850                    78
15   Asia                     700                   540
18   Asia                     800                   323

In [20]:
data = {
    "Name": [
        "Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"
    ],
    "Salary": [
        95000, 72000, 105000, 88000, 62000, 
        115000, 54000, 91000, 78000, 83000
    ],
    "Position": [
        "Software Engineer", "Data Scientist", "Project Manager", "UX Designer", "Intern",
        "CTO", "Marketing Associate", "DevOps Engineer", "Sales Lead", "Product Owner"
    ]
}

In [21]:
df = pd.DataFrame(data)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [23]:
df[df["Salary"] >= 80000]

       Name  Salary           Position
0      Liam   95000  Software Engineer
2      Noah  105000    Project Manager
3      Emma   88000        UX Designer
5       Ava  115000                CTO
7  Isabella   91000    DevOps Engineer
9       Mia   83000      Product Owner

In [25]:
df[df["Name"] == "Liam"]

   Name  Salary           Position
0  Liam   95000  Software Engineer

In [27]:
df.rename(columns = {"Salary" : "Take Home"}, inplace = True )
df

       Name  Take Home             Position
0      Liam      95000    Software Engineer
1    Sophia      72000       Data Scientist
2      Noah     105000      Project Manager
3      Emma      88000          UX Designer
4    Oliver      62000               Intern
5       Ava     115000                  CTO
6     Ethan      54000  Marketing Associate
7  Isabella      91000      DevOps Engineer
8     Lucas      78000           Sales Lead
9       Mia      83000        Product Owner

In [28]:
df.rename(columns = {"Take Home" : "Salary"}, inplace = True)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [30]:
df["Name"][0:5]

0      Liam
1    Sophia
2      Noah
3      Emma
4    Oliver
Name: Name, dtype: str

In [31]:
df.loc[df.Name == "Noah"]

   Name  Salary         Position
2  Noah  105000  Project Manager

In [33]:
df.loc[df.Salary == 83000]

  Name  Salary       Position
9  Mia   83000  Product Owner

In [37]:
df1 =pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.xlsx", sheet_name ="Sheet3",header = 2 )
df1

,Unnamed: 0,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
0,NaN,USA,North America,50000,8133
1,NaN,China,Asia,11000,2300
2,NaN,Japan,Asia,6500,845
3,NaN,Germany,Europe,2500,3350
4,NaN,India,Asia,5000,880
5,NaN,UK,Europe,3000,310
6,NaN,France,Europe,2800,2436
7,NaN,Italy,Europe,2000,2451
8,NaN,Canada,North America,2200,77
9,NaN,Brazil,South America,1800,130
10,NaN,Australia,Oceania,1600,280
11,NaN,South Korea,Asia,2100,104
12,NaN,Spain,Europe,1200,281
13,NaN,Mexico,North America,900,120
14,NaN,Indonesia,Asia,850,78
15,NaN,Turkey,Asia,700,540
16,NaN,Netherlands,Europe,1500,612
17,NaN,Switzerland,Europe,1900,1040
18,NaN,Saudi Arabia,Asia,800,323

In [42]:
df1 = df1.drop(df1.columns[0], axis =1)
df1

           Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0   North America                   50000                  8133
1            Asia                   11000                  2300
2            Asia                    6500                   845
3          Europe                    2500                  3350
4            Asia                    5000                   880
5          Europe                    3000                   310
6          Europe                    2800                  2436
7          Europe                    2000                  2451
8   North America                    2200                    77
9   South America                    1800                   130
10        Oceania                    1600                   280
11           Asia                    2100                   104
12         Europe                    1200                   281
13  North America                     900                   120
14           Asia                     850                    78
15           Asia                     700                   540
16         Europe                    1500                   612
17         Europe                    1900                  1040
18           Asia                     800                   323

In [45]:
df1.loc[(df1.Region == "Europe") & (df1.Stock_Market_Cap_BnUSD >= 100) & (df1.Gold_Reserves_Tonnes>=400)]

    Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
3   Europe                    2500                  3350
6   Europe                    2800                  2436
7   Europe                    2000                  2451
16  Europe                    1500                   612
17  Europe                    1900                  1040

In [46]:
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [47]:
df["Bonus"] = df["Salary"] * 0.2
df

       Name  Salary             Position    Bonus
0      Liam   95000    Software Engineer  19000.0
1    Sophia   72000       Data Scientist  14400.0
2      Noah  105000      Project Manager  21000.0
3      Emma   88000          UX Designer  17600.0
4    Oliver   62000               Intern  12400.0
5       Ava  115000                  CTO  23000.0
6     Ethan   54000  Marketing Associate  10800.0
7  Isabella   91000      DevOps Engineer  18200.0
8     Lucas   78000           Sales Lead  15600.0
9       Mia   83000        Product Owner  16600.0

In [49]:
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Salary             Position    Bonus     Total
0      Liam   95000    Software Engineer  19000.0  114000.0
1    Sophia   72000       Data Scientist  14400.0   86400.0
2      Noah  105000      Project Manager  21000.0  126000.0
3      Emma   88000          UX Designer  17600.0  105600.0
4    Oliver   62000               Intern  12400.0   74400.0
5       Ava  115000                  CTO  23000.0  138000.0
6     Ethan   54000  Marketing Associate  10800.0   64800.0
7  Isabella   91000      DevOps Engineer  18200.0  109200.0
8     Lucas   78000           Sales Lead  15600.0   93600.0
9       Mia   83000        Product Owner  16600.0   99600.0

In [2]:
data = {
    "Name": [
        "Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"
    ],
    "Salary": [
        95000, 72000, 105000, 88000, 62000, 
        115000, 54000, 91000, 78000, 83000
    ],
    "Position": [
        "Software Engineer", "Data Scientist", "Project Manager", "UX Designer", "Intern",
        "CTO", "Marketing Associate", "DevOps Engineer", "Sales Lead", "Product Owner"
    ]
}

In [3]:
df = pd.DataFrame(data)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [4]:
print(df.shape)
print(df.head(5))
print(df.tail(3))

(10, 3)
     Name  Salary           Position
0    Liam   95000  Software Engineer
1  Sophia   72000     Data Scientist
2    Noah  105000    Project Manager
3    Emma   88000        UX Designer
4  Oliver   62000             Intern
       Name  Salary         Position
7  Isabella   91000  DevOps Engineer
8     Lucas   78000       Sales Lead
9       Mia   83000    Product Owner

In [8]:
df.loc[0:2]

     Name  Salary           Position
0    Liam   95000  Software Engineer
1  Sophia   72000     Data Scientist
2    Noah  105000    Project Manager

In [12]:
df[df["Name"] == "Oliver"]

     Name  Salary Position
4  Oliver   62000   Intern

In [15]:
df[df["Salary"] >= 100000]

   Name  Salary         Position
2  Noah  105000  Project Manager
5   Ava  115000              CTO

In [18]:
df1 = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\all data.xlsx", header = 1)
df1

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
0,1,CHN,China,Beijing,Asia,1346563138,1319631875,1252303718,1184975561,1009922353,875266039,740609725,605953412,9706961,138.72
1,2,IND,India,New Delhi,Asia,251996221,246956296,234356485,221756674,188997165,163797543,138597921,113398299,3287590,76.65
2,3,USA,United States,"Washington, D.C.",North America,170967415,167548066,158999695,150451325,128225561,111128819,94032078,76935336,9372610,18.24
3,4,IDN,Indonesia,Jakarta,Asia,1098158599,1076195427,1021287497,966379567,823618949,713803089,603987229,494171369,1904569,576.59
4,5,PAK,Pakistan,Islamabad,Asia,79427434,77838885,73867513,69896141,59570575,51627832,43685088,35742345,881912,90.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,LSO,Lesotho,Maseru,Africa,57805104,56649001,53758746,50868491,43353828,37573317,31792807,26012296,30355,1904.30
146,147,SVN,Slovenia,Ljubljana,Europe,72970767,71511351,67862813,64214274,54728075,47430998,40133921,32836845,20273,3599.41
147,148,GNB,Guinea-Bissau,Bissau,Africa,45076770,44175234,41921396,39667557,33807577,29299900,24792223,20284546,36125,1247.80
148,149,MKD,North Macedonia,Skopje,Europe,21902250,21464205,20369092,19273980,16426687,14236462,12046237,9856012,25713,851.80
149,150,LVA,Latvia,Riga,Europe,21970209,21530804,20432294,19333783,16477656,14280635,12083614,9886594,64589,340.15

In [22]:
df1[df1["2022 Population"] >= 1000000000]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
0,1,CHN,China,Beijing,Asia,1346563138,1319631875,1252303718,1184975561,1009922353,875266039,740609725,605953412,9706961,138.72
3,4,IDN,Indonesia,Jakarta,Asia,1098158599,1076195427,1021287497,966379567,823618949,713803089,603987229,494171369,1904569,576.59

In [23]:
a =  ["China", "Pakistan" , "India" , "Bangladesh"]
df1[df1["Country"].isin(a)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
0,1,CHN,China,Beijing,Asia,1346563138,1319631875,1252303718,1184975561,1009922353,875266039,740609725,605953412,9706961,138.72
1,2,IND,India,New Delhi,Asia,251996221,246956296,234356485,221756674,188997165,163797543,138597921,113398299,3287590,76.65
4,5,PAK,Pakistan,Islamabad,Asia,79427434,77838885,73867513,69896141,59570575,51627832,43685088,35742345,881912,90.06
7,8,BGD,Bangladesh,Dhaka,Asia,441101090,432279068,410224013,388168959,330825817,286715708,242605599,198495490,147570,2989.10

In [27]:
df1[df1["Area (km²)"] >= 10000000]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
8,9,RUS,Russia,Moscow,Europe,596689023,584755242,554920791,525086340,447516767,387847864,328178962,268510060,17098242,34.9

In [28]:
df1[df1["Country"].str.contains("United")]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (P/km²)
2,3,USA,United States,"Washington, D.C.",North America,170967415,167548066,158999695,150451325,128225561,111128819,94032078,76935336,9372610,18.24
20,21,GBR,United Kingdom,London,Europe,52078423,51036854,48432933,45829012,39058817,33850974,28643132,23435290,242900,214.40
91,92,ARE,United Arab Emirates,Abu Dhabi,Asia,9417577,9229225,8758346,8287467,7063182,6121425,5179667,4237909,83600,112.65

In [29]:
print(df1.columns)

Index(['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (km²)', 'Density (P/km²)'],
      dtype='str')

In [32]:
df1.rename(columns = {"Area (km²)" : "Area"} , inplace = True)
print(df1.columns)

Index(['Rank', 'CCA3', 'Country', 'Capital', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area', 'Density (P/km²)'],
      dtype='str')

In [38]:
df1.loc[df1['Country'].isin(['Senegal', 'Pakistan']), df1.columns.str.contains('Population')]

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population
4,79427434,77838885,73867513,69896141,59570575,51627832,43685088,35742345
68,71531049,70100428,66523875,62947323,53648286,46495181,39342076,32188972

In [39]:
df2 = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.csv")
df2

        Country  Region  Population  GDP_per_capita
0      Pakistan    Asia   240000000            1500
1         India    Asia  1400000000            2500
2         China    Asia  1410000000           12000
3       Germany  Europe    83000000           48000
4        France  Europe    67000000           45000
..          ...     ...         ...             ...
91       Rwanda  Africa    14000000             900
92      Burundi  Africa    13000000             300
93     Cameroon  Africa    28000000            1600
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

[96 rows x 4 columns]

In [41]:
df2[df2["Population"] > 1000000000]

  Country Region  Population  GDP_per_capita
1   India   Asia  1400000000            2500
2   China   Asia  1410000000           12000

In [43]:
df2.rename(columns = {"GDP_per_capita" : "GDP"} , inplace = True)
df2.columns

Index(['Country', 'Region', 'Population', 'GDP'], dtype='str')

In [44]:
df2[["Country" , "GDP"]]

        Country    GDP
0      Pakistan   1500
1         India   2500
2         China  12000
3       Germany  48000
4        France  45000
..          ...    ...
91       Rwanda    900
92      Burundi    300
93     Cameroon   1600
94      Senegal   1800
95  Ivory Coast   2500

[96 rows x 2 columns]

In [51]:
df2.loc[(df2.Region == "Asia" ) & (df2.GDP >= 10000) & (df2.Population >= 10000000)]

         Country Region  Population    GDP
2          China   Asia  1410000000  12000
14         Japan   Asia   125000000  42000
51  Saudi Arabia   Asia    36000000  27000
52           UAE   Asia    10000000  43000
56        Turkey   Asia    85000000  10000

In [54]:
df2.where(df2["GDP"] > 15000, other = "Hahahahahahahaha")

             Country            Region        Population               GDP
0   Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
1   Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
2   Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
3            Germany            Europe          83000000             48000
4             France            Europe          67000000             45000
..               ...               ...               ...               ...
91  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
92  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
93  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
94  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha
95  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha  Hahahahahahahaha

[96 rows x 4 columns]

In [55]:
data = {
"Name": ["Shahzaib","Arfa", "Asad","Asif","Shireen","Assar"],
 "Age" : [23,30,30,33,56,57] ,  
"Salary" : [25000,30000,40000,600000,25000,322000]
}

In [56]:
df = pd.DataFrame(data)

In [57]:
df["Team"] = ["Finance" , "HR", "Accounting","Sales","HR","Marketing"]
df

       Name  Age  Salary        Team
0  Shahzaib   23   25000     Finance
1      Arfa   30   30000          HR
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [58]:
df["Bonus"] = df["Salary"] * 0.3
df["Total"] = df["Bonus"]  + df["Salary"]
df

       Name  Age  Salary        Team     Bonus     Total
0  Shahzaib   23   25000     Finance    7500.0   32500.0
1      Arfa   30   30000          HR    9000.0   39000.0
2      Asad   30   40000  Accounting   12000.0   52000.0
3      Asif   33  600000       Sales  180000.0  780000.0
4   Shireen   56   25000          HR    7500.0   32500.0
5     Assar   57  322000   Marketing   96600.0  418600.0

In [62]:
df.loc[0, "Team"] = "CEO"
df.loc[4 , "Team"] = "Head"
df.loc[0 , "Salary"] = 1000000
df

       Name  Age   Salary        Team     Bonus     Total
0  Shahzaib   23  1000000         CEO    7500.0   32500.0
1      Arfa   30    30000          HR    9000.0   39000.0
2      Asad   30    40000  Accounting   12000.0   52000.0
3      Asif   33   600000       Sales  180000.0  780000.0
4   Shireen   56    25000        Head    7500.0   32500.0
5     Assar   57   322000   Marketing   96600.0  418600.0

In [66]:
df

       Name  Age   Salary        Team
0  Shahzaib   23  1000000         CEO
1      Arfa   30    30000          HR
2      Asad   30    40000  Accounting
3      Asif   33   600000       Sales
4   Shireen   56    25000        Head
5     Assar   57   322000   Marketing

In [67]:
df["Bonus"] = df["Salary"] * 0.20
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Age   Salary        Team     Bonus      Total
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0
1      Arfa   30    30000          HR    6000.0    36000.0
2      Asad   30    40000  Accounting    8000.0    48000.0
3      Asif   33   600000       Sales  120000.0   720000.0
4   Shireen   56    25000        Head    5000.0    30000.0
5     Assar   57   322000   Marketing   64400.0   386400.0

In [68]:
df.where(df["Age"] > 28 , other = "Null")

      Name   Age  Salary        Team     Bonus     Total
0     Null  Null    Null        Null      Null      Null
1     Arfa    30   30000          HR    6000.0   36000.0
2     Asad    30   40000  Accounting    8000.0   48000.0
3     Asif    33  600000       Sales  120000.0  720000.0
4  Shireen    56   25000        Head    5000.0   30000.0
5    Assar    57  322000   Marketing   64400.0  386400.0

In [70]:
df.sort_values("Salary" , ascending = False)

       Name  Age   Salary        Team     Bonus      Total
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0
3      Asif   33   600000       Sales  120000.0   720000.0
5     Assar   57   322000   Marketing   64400.0   386400.0
2      Asad   30    40000  Accounting    8000.0    48000.0
1      Arfa   30    30000          HR    6000.0    36000.0
4   Shireen   56    25000        Head    5000.0    30000.0

In [71]:
df["DOJ"] = ["2024-01-01","2024-01-01","2024-01-02","2024-01-03","2024-01-04","2025-02-06"]
df

       Name  Age   Salary        Team     Bonus      Total         DOJ
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0  2024-01-01
1      Arfa   30    30000          HR    6000.0    36000.0  2024-01-01
2      Asad   30    40000  Accounting    8000.0    48000.0  2024-01-02
3      Asif   33   600000       Sales  120000.0   720000.0  2024-01-03
4   Shireen   56    25000        Head    5000.0    30000.0  2024-01-04
5     Assar   57   322000   Marketing   64400.0   386400.0  2025-02-06

In [73]:
df["DOJ"] = pd.to_datetime(df["DOJ"])

In [74]:
df["DOJ"].dt.year

0    2024
1    2024
2    2024
3    2024
4    2024
5    2025
Name: DOJ, dtype: int32

In [75]:
df = df.drop(columns = ["DOJ"])
df

       Name  Age   Salary        Team     Bonus      Total
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0
1      Arfa   30    30000          HR    6000.0    36000.0
2      Asad   30    40000  Accounting    8000.0    48000.0
3      Asif   33   600000       Sales  120000.0   720000.0
4   Shireen   56    25000        Head    5000.0    30000.0
5     Assar   57   322000   Marketing   64400.0   386400.0

In [76]:
df["DOJ"] = ["2024-01-01","2024-01-01","2024-01-02","2024-01-03","2024-01-04","2025-02-06"]
df

       Name  Age   Salary        Team     Bonus      Total         DOJ
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0  2024-01-01
1      Arfa   30    30000          HR    6000.0    36000.0  2024-01-01
2      Asad   30    40000  Accounting    8000.0    48000.0  2024-01-02
3      Asif   33   600000       Sales  120000.0   720000.0  2024-01-03
4   Shireen   56    25000        Head    5000.0    30000.0  2024-01-04
5     Assar   57   322000   Marketing   64400.0   386400.0  2025-02-06

In [77]:
df["DOJ"] = pd.to_datetime(df["DOJ"])

In [78]:
df["DOJ"].dt.month

0    1
1    1
2    1
3    1
4    1
5    2
Name: DOJ, dtype: int32

In [79]:
df["Month"] = df["DOJ"].dt.month
df

       Name  Age   Salary        Team     Bonus      Total        DOJ  Month
0  Shahzaib   23  1000000         CEO  200000.0  1200000.0 2024-01-01      1
1      Arfa   30    30000          HR    6000.0    36000.0 2024-01-01      1
2      Asad   30    40000  Accounting    8000.0    48000.0 2024-01-02      1
3      Asif   33   600000       Sales  120000.0   720000.0 2024-01-03      1
4   Shireen   56    25000        Head    5000.0    30000.0 2024-01-04      1
5     Assar   57   322000   Marketing   64400.0   386400.0 2025-02-06      2

In [81]:
df.where(df["Salary"] > 100000, other = "011001")

,Name,Age,Salary,Team,Bonus,Total,DOJ,Month
0,Shahzaib,23,1000000,CEO,200000.0,1200000.0,2024-01-01,1
1,011001,011001,011001,011001,011001,011001,2001-01-10,011001
2,011001,011001,011001,011001,011001,011001,2001-01-10,011001
3,Asif,33,600000,Sales,120000.0,720000.0,2024-01-03,1
4,011001,011001,011001,011001,011001,011001,2001-01-10,011001
5,Assar,57,322000,Marketing,64400.0,386400.0,2025-02-06,2

In [82]:
import numpy as np

In [84]:
df.loc[df.Name == "Arfa" , "Salary"] = np.nan
df

       Name  Age     Salary        Team     Bonus      Total        DOJ  Month
0  Shahzaib   23  1000000.0         CEO  200000.0  1200000.0 2024-01-01      1
1      Arfa   30        NaN          HR    6000.0    36000.0 2024-01-01      1
2      Asad   30    40000.0  Accounting    8000.0    48000.0 2024-01-02      1
3      Asif   33   600000.0       Sales  120000.0   720000.0 2024-01-03      1
4   Shireen   56    25000.0        Head    5000.0    30000.0 2024-01-04      1
5     Assar   57   322000.0   Marketing   64400.0   386400.0 2025-02-06      2

In [86]:
df.loc[df.Name == "Shireen", "Age"] = np.nan
df

,Name,Age,Salary,Team,Bonus,Total,DOJ,Month
0,Shahzaib,23.0,1000000.0,CEO,200000.0,1200000.0,2024-01-01,1
1,Arfa,30.0,NaN,HR,6000.0,36000.0,2024-01-01,1
2,Asad,30.0,40000.0,Accounting,8000.0,48000.0,2024-01-02,1
3,Asif,33.0,600000.0,Sales,120000.0,720000.0,2024-01-03,1
4,Shireen,NaN,25000.0,Head,5000.0,30000.0,2024-01-04,1
5,Assar,57.0,322000.0,Marketing,64400.0,386400.0,2025-02-06,2

In [88]:
df.isnull().sum()

Name      0
Age       1
Salary    1
Team      0
Bonus     0
Total     0
DOJ       0
Month     0
dtype: int64

In [89]:
df.loc[df.Name == "Shireen" , "Age"]  = 51
df.loc[df.Name  == "Arfa", "Salary" ] = 100000

In [91]:
df.isnull().sum()

Name      0
Age       0
Salary    0
Team      0
Bonus     0
Total     0
DOJ       0
Month     0
dtype: int64

In [96]:
df[df["Name"] == "Shahzaib"]

       Name   Age     Salary Team     Bonus      Total        DOJ  Month
0  Shahzaib  23.0  1000000.0  CEO  200000.0  1200000.0 2024-01-01      1

In [99]:
df.loc[df.Name == "Shahzaib"]

       Name   Age     Salary Team     Bonus      Total        DOJ  Month
0  Shahzaib  23.0  1000000.0  CEO  200000.0  1200000.0 2024-01-01      1

In [42]:
data1 = {
    "Order_ID": [
        201,202,203,204,205,206,207,208,209,210,
        211,212,213,214,215
    ],
    "Product": [
        "iPhone 15","MacBook Air","iPad Pro","AirPods Pro","Apple Watch",
        "iPhone 14","MacBook Pro","iPad Air","AirPods Max","Apple Watch Ultra",
        "iMac","iPhone 13","Mac Mini","iPad Mini","AirPods 3"
    ],
    "Category": [
        "iPhone","Mac","iPad","Accessories","Wearables",
        "iPhone","Mac","iPad","Accessories","Wearables",
        "Mac","iPhone","Mac","iPad","Accessories"
    ],
    "Price": [
        280000,350000,250000,75000,120000,
        240000,500000,180000,150000,220000,
        400000,200000,180000,140000,60000
    ],
    "Quantity": [
        2,1,1,3,2,
        2,1,2,1,1,
        1,3,2,2,4
    ],
    "Region": [
        "Karachi","Lahore","Islamabad","Karachi","Lahore",
        "Islamabad","Karachi","Lahore","Islamabad","Karachi",
        "Lahore","Islamabad","Karachi","Lahore","Islamabad"
    ],
    "Order_Date": [
        "2024-01-05","2024-01-10","2024-01-15","2024-01-20","2024-01-25",
        "2024-02-01","2024-02-05","2024-02-10","2024-02-15","2024-02-20",
        "2024-03-01","2024-03-05","2024-03-10","2024-03-15","2024-03-20"
    ]
}

In [4]:
df = pd.DataFrame(data)
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [7]:
df[df["Category"] == "Mac"]

    Order_ID      Product Category   Price  Quantity   Region  Order_Date
1        202  MacBook Air      Mac  350000         1   Lahore  2024-01-10
6        207  MacBook Pro      Mac  500000         1  Karachi  2024-02-05
10       211         iMac      Mac  400000         1   Lahore  2024-03-01
12       213     Mac Mini      Mac  180000         2  Karachi  2024-03-10

In [9]:
df[df["Price"] >= 500000]

   Order_ID      Product Category   Price  Quantity   Region  Order_Date
6       207  MacBook Pro      Mac  500000         1  Karachi  2024-02-05

In [11]:
df.rename(columns = {"Region" : "City"}, inplace = True)
df

,Order_ID,Product,Category,Price,Quantity,City,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [13]:
specific = ["iPhone", "iPad"]
df[df["Category"].isin(specific)]

    Order_ID    Product Category   Price  Quantity       City  Order_Date
0        201  iPhone 15   iPhone  280000         2    Karachi  2024-01-05
2        203   iPad Pro     iPad  250000         1  Islamabad  2024-01-15
5        206  iPhone 14   iPhone  240000         2  Islamabad  2024-02-01
7        208   iPad Air     iPad  180000         2     Lahore  2024-02-10
11       212  iPhone 13   iPhone  200000         3  Islamabad  2024-03-05
13       214  iPad Mini     iPad  140000         2     Lahore  2024-03-15

In [14]:
df[df["Product"].str.contains("iPhone")]

    Order_ID    Product Category   Price  Quantity       City  Order_Date
0        201  iPhone 15   iPhone  280000         2    Karachi  2024-01-05
5        206  iPhone 14   iPhone  240000         2  Islamabad  2024-02-01
11       212  iPhone 13   iPhone  200000         3  Islamabad  2024-03-05

In [16]:
df.loc[df.Product == "iPad Mini"]

    Order_ID    Product Category   Price  Quantity    City  Order_Date
13       214  iPad Mini     iPad  140000         2  Lahore  2024-03-15

In [17]:
df[df["Product"] == "iPad Mini"]

    Order_ID    Product Category   Price  Quantity    City  Order_Date
13       214  iPad Mini     iPad  140000         2  Lahore  2024-03-15

In [18]:
df.loc[(df.City == "Karachi") & (df.Price > 100000)]

,Order_ID,Product,Category,Price,Quantity,City,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10

In [19]:
df.loc[df.Price > 200000]

,Order_ID,Product,Category,Price,Quantity,City,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01

In [22]:
df.where(df["Price"] > 100000 , other ="Null")

,Order_ID,Product,Category,Price,Quantity,City,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,Null,Null,Null,Null,Null,Null,Null
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,Null,Null,Null,Null,Null,Null,Null

In [26]:
df["Per Price"] = round(df["Price"] / df["Quantity"],0)
df

,Order_ID,Product,Category,Price,Quantity,City,Order_Date,Per Price
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05,140000.0
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10,350000.0
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15,250000.0
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20,25000.0
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25,60000.0
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01,120000.0
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05,500000.0
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10,90000.0
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15,150000.0
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20,220000.0
10,211,iMac,Mac,400000,1,Lahore,2024-03-01,400000.0
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05,66667.0
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10,90000.0
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15,70000.0
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20,15000.0

In [29]:
row = [221, "Apple TV 4K", "Entertainment", 65000, 1, "Lahore", "2024-04-05", 65000]

In [30]:
df.loc[len(df)] = row 
df

,Order_ID,Product,Category,Price,Quantity,City,Order_Date,Per Price
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05,140000.0
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10,350000.0
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15,250000.0
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20,25000.0
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25,60000.0
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01,120000.0
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05,500000.0
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10,90000.0
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15,150000.0
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20,220000.0
10,211,iMac,Mac,400000,1,Lahore,2024-03-01,400000.0
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05,66667.0
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10,90000.0
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15,70000.0
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20,15000.0
15,221,Apple TV 4K,Entertainment,65000,1,Lahore,2024-04-05,65000.0

In [31]:
df.loc[15 , "Product"] = "Apple TV"
df

,Order_ID,Product,Category,Price,Quantity,City,Order_Date,Per Price
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05,140000.0
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10,350000.0
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15,250000.0
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20,25000.0
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25,60000.0
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01,120000.0
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05,500000.0
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10,90000.0
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15,150000.0
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20,220000.0
10,211,iMac,Mac,400000,1,Lahore,2024-03-01,400000.0
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05,66667.0
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10,90000.0
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15,70000.0
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20,15000.0
15,221,Apple TV,Entertainment,65000,1,Lahore,2024-04-05,65000.0

In [33]:
df.rename(columns = {"Per Price" : "Avg Price"} , inplace = True)
df.columns

Index(['Order_ID', 'Product', 'Category', 'Price', 'Quantity', 'City',
       'Order_Date', 'Avg Price'],
      dtype='str')

In [35]:
df.drop(df[df.Product == "Apple TV"].index, inplace = True)

In [41]:
df.sort_values("Price", ascending = False)

,Order_ID,Product,Category,Price,Quantity,City,Order_Date
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [43]:
df1 = pd.DataFrame( {"Name" : ["Shahzaib" , "Ali", "Arfa", "Asad"] , "ID" : [1,2,3,4]})

In [47]:
df2 = pd.DataFrame( {"Course" : ["Eng" , "Math" , "Sicence" , "Urdu"] , "ID" : [1,2,3,4]})
df2

    Course  ID
0      Eng   1
1     Math   2
2  Sicence   3
3     Urdu   4

In [49]:
pd.concat([df1,df2] , axis = 0)

       Name  ID   Course
0  Shahzaib   1      NaN
1       Ali   2      NaN
2      Arfa   3      NaN
3      Asad   4      NaN
0       NaN   1      Eng
1       NaN   2     Math
2       NaN   3  Sicence
3       NaN   4     Urdu

### Joins

In [79]:
customers = {
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Payment_ID": [201, 202, 203, 204, 205,206],
    "Name": ["Ali", "Sara", "Ahmed", "Zara", "Bilal", "Hina"],
    "City": ["Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad"]
}

In [80]:
payments = {
    "Payment_ID": [201, 202, 203, 204, 205],
    "Order_ID": [101, 102, 104, 105, 108],
    "Payment_Method": ["Card", "Cash", "Card", "Cash", "Card"],
    "Status": ["Paid", "Paid", "Pending", "Paid", "Failed"]
}

In [81]:
orders = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107],
    "Customer_ID": [1, 2, 2, 3, 5, 6, 7],
    "Product": ["Laptop", "Phone", "Tablet", "Shoes", "Watch", "Bag", "Camera"],
    "Amount": [120000, 80000, 60000, 7000, 15000, 5000, 90000]
}

In [82]:
df1 = pd.DataFrame(customers)
df2 = pd.DataFrame(payments)
df3 = pd.DataFrame(orders)

In [83]:
df1.merge(df3)     # inner join

   Customer_ID  Payment_ID   Name       City  Order_ID Product  Amount
0            1         201    Ali    Karachi       101  Laptop  120000
1            2         202   Sara     Lahore       102   Phone   80000
2            2         202   Sara     Lahore       103  Tablet   60000
3            3         203  Ahmed  Islamabad       104   Shoes    7000
4            5         205  Bilal     Lahore       105   Watch   15000
5            6         206   Hina  Islamabad       106     Bag    5000

In [84]:
df1.merge(df3 ,  how = "outer" , on = "Customer_ID")

   Customer_ID  Payment_ID   Name       City  Order_ID Product    Amount
0            1       201.0    Ali    Karachi     101.0  Laptop  120000.0
1            2       202.0   Sara     Lahore     102.0   Phone   80000.0
2            2       202.0   Sara     Lahore     103.0  Tablet   60000.0
3            3       203.0  Ahmed  Islamabad     104.0   Shoes    7000.0
4            4       204.0   Zara    Karachi       NaN     NaN       NaN
5            5       205.0  Bilal     Lahore     105.0   Watch   15000.0
6            6       206.0   Hina  Islamabad     106.0     Bag    5000.0
7            7         NaN    NaN        NaN     107.0  Camera   90000.0

In [88]:
df1.merge(df2 , how = "left" , on = "Payment_ID")

   Customer_ID  Payment_ID   Name       City  Order_ID Payment_Method   Status
0            1         201    Ali    Karachi     101.0           Card     Paid
1            2         202   Sara     Lahore     102.0           Cash     Paid
2            3         203  Ahmed  Islamabad     104.0           Card  Pending
3            4         204   Zara    Karachi     105.0           Cash     Paid
4            5         205  Bilal     Lahore     108.0           Card   Failed
5            6         206   Hina  Islamabad       NaN            NaN      NaN

In [89]:
df1.merge(df2, how = "cross")

,Customer_ID,Payment_ID_x,Name,City,Payment_ID_y,Order_ID,Payment_Method,Status
0,1,201,Ali,Karachi,201,101,Card,Paid
1,1,201,Ali,Karachi,202,102,Cash,Paid
2,1,201,Ali,Karachi,203,104,Card,Pending
3,1,201,Ali,Karachi,204,105,Cash,Paid
4,1,201,Ali,Karachi,205,108,Card,Failed
5,2,202,Sara,Lahore,201,101,Card,Paid
6,2,202,Sara,Lahore,202,102,Cash,Paid
7,2,202,Sara,Lahore,203,104,Card,Pending
8,2,202,Sara,Lahore,204,105,Cash,Paid
9,2,202,Sara,Lahore,205,108,Card,Failed
10,3,203,Ahmed,Islamabad,201,101,Card,Paid
11,3,203,Ahmed,Islamabad,202,102,Cash,Paid
12,3,203,Ahmed,Islamabad,203,104,Card,Pending
13,3,203,Ahmed,Islamabad,204,105,Cash,Paid
14,3,203,Ahmed,Islamabad,205,108,Card,Failed
15,4,204,Zara,Karachi,201,101,Card,Paid
16,4,204,Zara,Karachi,202,102,Cash,Paid
17,4,204,Zara,Karachi,203,104,Card,Pending
18,4,204,Zara,Karachi,204,105,Cash,Paid
19,4,204,Zara,Karachi,205,108,Card,Failed
20,5,205,Bilal,Lahore,201,101,Card,Paid
21,5,205,Bilal,Lahore,202,102,Cash,Paid
22,5,205,Bilal,Lahore,203,104,Card,Pending
23,5,205,Bilal,Lahore,204,105,Cash,Paid
24,5,205,Bilal,Lahore,205,108,Card,Failed
25,6,206,Hina,Islamabad,201,101,Card,Paid
26,6,206,Hina,Islamabad,202,102,Cash,Paid
27,6,206,Hina,Islamabad,203,104,Card,Pending
28,6,206,Hina,Islamabad,204,105,Cash,Paid
29,6,206,Hina,Islamabad,205,108,Card,Failed

In [94]:
pd.concat([df1,df2] , join = "inner")

   Payment_ID
0         201
1         202
2         203
3         204
4         205
5         206
0         201
1         202
2         203
3         204
4         205

In [95]:
df1.merge(df3 , how = "right" )

   Customer_ID  Payment_ID   Name       City  Order_ID Product  Amount
0            1       201.0    Ali    Karachi       101  Laptop  120000
1            2       202.0   Sara     Lahore       102   Phone   80000
2            2       202.0   Sara     Lahore       103  Tablet   60000
3            3       203.0  Ahmed  Islamabad       104   Shoes    7000
4            5       205.0  Bilal     Lahore       105   Watch   15000
5            6       206.0   Hina  Islamabad       106     Bag    5000
6            7         NaN    NaN        NaN       107  Camera   90000

In [99]:
dfc = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name = "Customer")
dfc

,customer_id,name,city,age,phone,join_date,gender
0,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F
1,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F
2,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M
3,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M
4,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F
5,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M
6,C007,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F
7,C008,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F
8,C009,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M
9,C010,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F
10,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F
11,C012,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F

In [100]:
dfa  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='accounts')
dft  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='transactions')
dfl  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='loans')

In [101]:
dfl

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08

In [102]:
dfc.merge(dfl, how = "left")

,customer_id,name,city,age,phone,join_date,gender,loan_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F,L007,Business Loan,551378.0,10.4,33.0,Closed,2023-03-05
1,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L001,Business Loan,3259410.0,13.1,159.0,Closed,2021-11-09
4,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L003,Home Loan,1522769.0,15.6,72.0,Approved,2021-01-25
5,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L004,Car Loan,4331889.0,16.3,189.0,Pending,2021-03-20
6,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
7,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M,L008,Business Loan,4709020.0,13.3,126.0,Closed,2023-11-08
8,C007,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
9,C008,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
10,C009,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M,L002,Car Loan,3185486.0,15.8,71.0,Approved,2024-07-06
11,C010,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F,L005,Home Loan,4507670.0,10.0,18.0,Approved,2020-02-07
12,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F,L006,Education Loan,1625677.0,14.7,58.0,Closed,2021-12-07
13,C012,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [103]:
dfc.merge(dfa , how = "left")

,customer_id,name,city,age,phone,join_date,gender,account_id,account_type,balance,status,opened_date,branch
0,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F,A001,Current,479579,Dormant,2024-12-16,Faisalabad
1,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F,A002,Salary,21236,Active,2023-07-04,Islamabad
2,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F,A003,Savings,124426,Active,2021-05-18,Lahore
3,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F,A004,Salary,286015,Closed,2021-09-09,Karachi
4,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M,A005,Current,131639,Active,2020-05-20,Karachi
5,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M,A006,Fixed Deposit,80125,Closed,2018-08-26,Rawalpindi
6,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,A007,Salary,155034,Closed,2019-04-09,Quetta
7,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,A008,Current,431844,Active,2021-11-17,Faisalabad
8,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F,A009,Fixed Deposit,498042,Active,2024-05-08,Faisalabad
9,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F,A010,Current,59336,Dormant,2019-10-26,Islamabad
10,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M,A011,Salary,189534,Active,2023-10-22,Peshawar
11,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M,A012,Savings,457866,Active,2023-07-27,Quetta
12,C007,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F,A013,Savings,425170,Active,2020-10-26,Peshawar
13,C008,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F,A014,Salary,125746,Active,2024-10-09,Quetta
14,C009,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M,A015,Salary,377309,Dormant,2022-12-28,Islamabad
15,C010,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F,A016,Salary,391887,Active,2018-06-07,Quetta
16,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F,A017,Current,368725,Dormant,2021-01-09,Multan
17,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F,A018,Current,337450,Active,2018-07-05,Karachi
18,C012,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F,A019,Fixed Deposit,453779,Closed,2022-02-21,Multan

In [106]:
dfc[dfc["city"] == "Karachi"]

  customer_id          name     city  age         phone  join_date gender
5        C006    Omar Mirza  Karachi   63  0345-7350302 2024-01-09      M
8        C009     Sana Baig  Karachi   40  0316-3357787 2020-05-24      M
9        C010  Fatima Rizvi  Karachi   49  0328-9230948 2020-03-09      F

In [107]:
dfa[dfa["balance"] > 100000]

,account_id,customer_id,account_type,balance,status,opened_date,branch
0,A001,C001,Current,479579,Dormant,2024-12-16,Faisalabad
2,A003,C002,Savings,124426,Active,2021-05-18,Lahore
3,A004,C002,Salary,286015,Closed,2021-09-09,Karachi
4,A005,C003,Current,131639,Active,2020-05-20,Karachi
6,A007,C004,Salary,155034,Closed,2019-04-09,Quetta
7,A008,C004,Current,431844,Active,2021-11-17,Faisalabad
8,A009,C005,Fixed Deposit,498042,Active,2024-05-08,Faisalabad
10,A011,C006,Salary,189534,Active,2023-10-22,Peshawar
11,A012,C006,Savings,457866,Active,2023-07-27,Quetta
12,A013,C007,Savings,425170,Active,2020-10-26,Peshawar
13,A014,C008,Salary,125746,Active,2024-10-09,Quetta
14,A015,C009,Salary,377309,Dormant,2022-12-28,Islamabad
15,A016,C010,Salary,391887,Active,2018-06-07,Quetta
16,A017,C011,Current,368725,Dormant,2021-01-09,Multan
17,A018,C011,Current,337450,Active,2018-07-05,Karachi
18,A019,C012,Fixed Deposit,453779,Closed,2022-02-21,Multan

In [112]:
dfl.loc[dfl.status == "Approved"]

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07

In [115]:
dfl["status"].value_counts()

status
Closed      4
Approved    3
Pending     1
Name: count, dtype: int64

In [116]:
dfc.merge(dfl , how = "left")

,customer_id,name,city,age,phone,join_date,gender,loan_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,C001,Ali Mirza,Quetta,64,0348-9921099,2018-10-17,F,L007,Business Loan,551378.0,10.4,33.0,Closed,2023-03-05
1,C002,Rabia Chaudhry,Rawalpindi,45,0322-6473046,2024-05-11,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,C003,Rabia Qureshi,Peshawar,38,0311-8529958,2021-10-28,M,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L001,Business Loan,3259410.0,13.1,159.0,Closed,2021-11-09
4,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L003,Home Loan,1522769.0,15.6,72.0,Approved,2021-01-25
5,C004,Ahmed Ali,Multan,60,0339-1242430,2022-11-15,M,L004,Car Loan,4331889.0,16.3,189.0,Pending,2021-03-20
6,C005,Maryam Siddiqui,Faisalabad,60,0332-6475912,2021-06-15,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
7,C006,Omar Mirza,Karachi,63,0345-7350302,2024-01-09,M,L008,Business Loan,4709020.0,13.3,126.0,Closed,2023-11-08
8,C007,Sana Ali,Peshawar,63,0332-6614689,2020-12-19,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
9,C008,Ayesha Hussain,Faisalabad,65,0321-5979479,2021-11-28,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT
10,C009,Sana Baig,Karachi,40,0316-3357787,2020-05-24,M,L002,Car Loan,3185486.0,15.8,71.0,Approved,2024-07-06
11,C010,Fatima Rizvi,Karachi,49,0328-9230948,2020-03-09,F,L005,Home Loan,4507670.0,10.0,18.0,Approved,2020-02-07
12,C011,Zara Sheikh,Multan,58,0343-1379373,2019-01-14,F,L006,Education Loan,1625677.0,14.7,58.0,Closed,2021-12-07
13,C012,Fatima Hussain,Multan,38,0343-3253026,2020-06-06,F,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [2]:
df =pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.xlsx", sheet_name ="Sheet3",header =2 )
df

,Unnamed: 0,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
0,NaN,USA,North America,50000,8133
1,NaN,China,Asia,11000,2300
2,NaN,Japan,Asia,6500,845
3,NaN,Germany,Europe,2500,3350
4,NaN,India,Asia,5000,880
5,NaN,UK,Europe,3000,310
6,NaN,France,Europe,2800,2436
7,NaN,Italy,Europe,2000,2451
8,NaN,Canada,North America,2200,77
9,NaN,Brazil,South America,1800,130
10,NaN,Australia,Oceania,1600,280
11,NaN,South Korea,Asia,2100,104
12,NaN,Spain,Europe,1200,281
13,NaN,Mexico,North America,900,120
14,NaN,Indonesia,Asia,850,78
15,NaN,Turkey,Asia,700,540
16,NaN,Netherlands,Europe,1500,612
17,NaN,Switzerland,Europe,1900,1040
18,NaN,Saudi Arabia,Asia,800,323

In [3]:
df[df["Country"] == "Japan"]

   Unnamed: 0 Country Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
2         NaN   Japan   Asia                    6500                   845

In [5]:
a = ["Turkey", "Mexico"]
df[df["Country"].isin(a)]

,Unnamed: 0,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
13,NaN,Mexico,North America,900,120
15,NaN,Turkey,Asia,700,540

In [9]:
df=df.drop(df.columns[0] , axis = 1)
df

         Country         Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0            USA  North America                   50000                  8133
1          China           Asia                   11000                  2300
2          Japan           Asia                    6500                   845
3        Germany         Europe                    2500                  3350
4          India           Asia                    5000                   880
5             UK         Europe                    3000                   310
6         France         Europe                    2800                  2436
7          Italy         Europe                    2000                  2451
8         Canada  North America                    2200                    77
9         Brazil  South America                    1800                   130
10     Australia        Oceania                    1600                   280
11   South Korea           Asia                    2100                   104
12         Spain         Europe                    1200                   281
13        Mexico  North America                     900                   120
14     Indonesia           Asia                     850                    78
15        Turkey           Asia                     700                   540
16   Netherlands         Europe                    1500                   612
17   Switzerland         Europe                    1900                  1040
18  Saudi Arabia           Asia                     800                   323

In [13]:
df.rename(columns = {"Stock_Market_Cap_BnUSD" :"Market Cap"} , inplace = True)
df

         Country         Region  Market Cap  Gold_Reserves_Tonnes
0            USA  North America       50000                  8133
1          China           Asia       11000                  2300
2          Japan           Asia        6500                   845
3        Germany         Europe        2500                  3350
4          India           Asia        5000                   880
5             UK         Europe        3000                   310
6         France         Europe        2800                  2436
7          Italy         Europe        2000                  2451
8         Canada  North America        2200                    77
9         Brazil  South America        1800                   130
10     Australia        Oceania        1600                   280
11   South Korea           Asia        2100                   104
12         Spain         Europe        1200                   281
13        Mexico  North America         900                   120
14     Indonesia           Asia         850                    78
15        Turkey           Asia         700                   540
16   Netherlands         Europe        1500                   612
17   Switzerland         Europe        1900                  1040
18  Saudi Arabia           Asia         800                   323

In [15]:
df.rename(columns = {"Gold Reserves" : "Gold_Reserves"} , inplace = True)
df

         Country         Region  Market Cap  Gold_Reserves
0            USA  North America       50000           8133
1          China           Asia       11000           2300
2          Japan           Asia        6500            845
3        Germany         Europe        2500           3350
4          India           Asia        5000            880
5             UK         Europe        3000            310
6         France         Europe        2800           2436
7          Italy         Europe        2000           2451
8         Canada  North America        2200             77
9         Brazil  South America        1800            130
10     Australia        Oceania        1600            280
11   South Korea           Asia        2100            104
12         Spain         Europe        1200            281
13        Mexico  North America         900            120
14     Indonesia           Asia         850             78
15        Turkey           Asia         700            540
16   Netherlands         Europe        1500            612
17   Switzerland         Europe        1900           1040
18  Saudi Arabia           Asia         800            323

In [18]:
df.loc[(df.Region == "Asia")    & (df.Gold_Reserves > 350)]

   Country Region  Market Cap  Gold_Reserves
1    China   Asia       11000           2300
2    Japan   Asia        6500            845
4    India   Asia        5000            880
15  Turkey   Asia         700            540

In [21]:
df[0:2]

  Country         Region  Market Cap  Gold_Reserves
0     USA  North America       50000           8133
1   China           Asia       11000           2300

In [22]:
data = {
"Name": ["Shahzaib","Arfa", "Asad","Asif","Shireen","Assar"],
 "Age" : [23,30,30,33,56,57] ,  
"Salary" : [25000,30000,40000,600000,25000,322000]
}

In [24]:
df = pd.DataFrame(data)
df

       Name  Age  Salary
0  Shahzaib   23   25000
1      Arfa   30   30000
2      Asad   30   40000
3      Asif   33  600000
4   Shireen   56   25000
5     Assar   57  322000

In [25]:
df["Team"] = ["Finance" , "HR", "Accounting","Sales","HR","Marketing"]
df

       Name  Age  Salary        Team
0  Shahzaib   23   25000     Finance
1      Arfa   30   30000          HR
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [28]:
df[1,"HR"] = "Marketing"
df[0,25000] =70000
df

       Name  Age  Salary        Team    (1, HR)  (0, 25000)
0  Shahzaib   23   25000     Finance  Marketing       70000
1      Arfa   30   30000          HR  Marketing       70000
2      Asad   30   40000  Accounting  Marketing       70000
3      Asif   33  600000       Sales  Marketing       70000
4   Shireen   56   25000          HR  Marketing       70000
5     Assar   57  322000   Marketing  Marketing       70000

In [35]:
df.drop([(1, "HR"), (0, 25000)], axis=1, inplace=True)
df

       Name  Age  Salary        Team
0  Shahzaib   23   25000     Finance
1      Arfa   30   30000          HR
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [37]:
df.loc[0,"Salary"] = 35000
df.loc[1, "Team"] = "Marketing"
df

       Name  Age  Salary        Team
0  Shahzaib   23   35000     Finance
1      Arfa   30   30000   Marketing
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [38]:
df["Bonus"] = df["Salary"] * 0.25
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Age  Salary        Team     Bonus     Total
0  Shahzaib   23   35000     Finance    8750.0   43750.0
1      Arfa   30   30000   Marketing    7500.0   37500.0
2      Asad   30   40000  Accounting   10000.0   50000.0
3      Asif   33  600000       Sales  150000.0  750000.0
4   Shireen   56   25000          HR    6250.0   31250.0
5     Assar   57  322000   Marketing   80500.0  402500.0

In [39]:
df.drop(["Bonus", "Total"] , axis =1 , inplace = True)
df

       Name  Age  Salary        Team
0  Shahzaib   23   35000     Finance
1      Arfa   30   30000   Marketing
2      Asad   30   40000  Accounting
3      Asif   33  600000       Sales
4   Shireen   56   25000          HR
5     Assar   57  322000   Marketing

In [40]:
df["Bonus"] = df["Salary"] * 0.25
df["Total"] = df["Salary"] + df["Bonus"]
df

       Name  Age  Salary        Team     Bonus     Total
0  Shahzaib   23   35000     Finance    8750.0   43750.0
1      Arfa   30   30000   Marketing    7500.0   37500.0
2      Asad   30   40000  Accounting   10000.0   50000.0
3      Asif   33  600000       Sales  150000.0  750000.0
4   Shireen   56   25000          HR    6250.0   31250.0
5     Assar   57  322000   Marketing   80500.0  402500.0

In [41]:
df.sort_values("Salary")

       Name  Age  Salary        Team     Bonus     Total
4   Shireen   56   25000          HR    6250.0   31250.0
1      Arfa   30   30000   Marketing    7500.0   37500.0
0  Shahzaib   23   35000     Finance    8750.0   43750.0
2      Asad   30   40000  Accounting   10000.0   50000.0
5     Assar   57  322000   Marketing   80500.0  402500.0
3      Asif   33  600000       Sales  150000.0  750000.0

In [44]:
df1 = pd.DataFrame(data1)
df1

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [46]:
df.loc[len(df1)] = [215, "iPhone 13", "iPhone" , 70000,1, "Karachi" , "2024-03-15"]
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20
15,215,iPhone 13,iPhone,70000,1,Karachi,2024-03-15

In [48]:
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date,"(14, Price)"
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05,3333333
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10,3333333
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15,3333333
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20,3333333
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25,3333333
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01,3333333
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05,3333333
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10,3333333
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15,3333333
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20,3333333
10,211,iMac,Mac,400000,1,Lahore,2024-03-01,3333333
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05,3333333
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10,3333333
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15,3333333
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20,3333333
15,215,iPhone 13,iPhone,70000,1,Karachi,2024-03-15,3333333

In [49]:
df.drop([(14,"Price")] , axis =1 , inplace = True)
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20
15,215,iPhone 13,iPhone,70000,1,Karachi,2024-03-15

In [51]:
df.loc[14, "Price"] = 33333333
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,33333333,4,Islamabad,2024-03-20
15,215,iPhone 13,iPhone,70000,1,Karachi,2024-03-15

In [53]:
df.loc[(df.Category == "Mac") & (df.Price > 80000)]

    Order_ID      Product Category   Price  Quantity   Region  Order_Date
1        202  MacBook Air      Mac  350000         1   Lahore  2024-01-10
6        207  MacBook Pro      Mac  500000         1  Karachi  2024-02-05
10       211         iMac      Mac  400000         1   Lahore  2024-03-01
12       213     Mac Mini      Mac  180000         2  Karachi  2024-03-10

In [4]:
dfa  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='accounts')
dft  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='transactions')
dfl  = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\Bank Data.xlsx", sheet_name='loans')

In [5]:
dfl

,loan_id,customer_id,loan_type,amount,interest_rate,tenure_months,status,start_date
0,L001,C004,Business Loan,3259410,13.1,159,Closed,2021-11-09
1,L002,C009,Car Loan,3185486,15.8,71,Approved,2024-07-06
2,L003,C004,Home Loan,1522769,15.6,72,Approved,2021-01-25
3,L004,C004,Car Loan,4331889,16.3,189,Pending,2021-03-20
4,L005,C010,Home Loan,4507670,10.0,18,Approved,2020-02-07
5,L006,C011,Education Loan,1625677,14.7,58,Closed,2021-12-07
6,L007,C001,Business Loan,551378,10.4,33,Closed,2023-03-05
7,L008,C006,Business Loan,4709020,13.3,126,Closed,2023-11-08

In [6]:
dfl["status"].value_counts()

status
Closed      4
Approved    3
Pending     1
Name: count, dtype: int64

In [7]:
dfl[dfl["loan_type"] == "Business Loan"].value_counts()

loan_id  customer_id  loan_type      amount   interest_rate  tenure_months  status  start_date
L001     C004         Business Loan  3259410  13.1           159            Closed  2021-11-09    1
L007     C001         Business Loan  551378   10.4           33             Closed  2023-03-05    1
L008     C006         Business Loan  4709020  13.3           126            Closed  2023-11-08    1
Name: count, dtype: int64

In [8]:
dfl.groupby("loan_type")["amount"].value_counts()

loan_type       amount
Business Loan   3259410    1
                551378     1
                4709020    1
Car Loan        3185486    1
                4331889    1
Education Loan  1625677    1
Home Loan       1522769    1
                4507670    1
Name: count, dtype: int64

In [10]:
dfl["loan_type"].value_counts()

loan_type
Business Loan     3
Car Loan          2
Home Loan         2
Education Loan    1
Name: count, dtype: int64

In [15]:
dfl.groupby("status")["amount"].sum()

status
Approved     9215925
Closed      10145485
Pending      4331889
Name: amount, dtype: int64

In [16]:
sales_data = {
    "Date": ["2026-04-01", "2026-04-01", "2026-04-02", "2026-04-02", "2026-04-03", "2026-04-03"],
    "Flavor": ["Vanilla", "Chocolate", "Strawberry", "Vanilla", "Chocolate", "Mango"],
    "Sales": [120, 150, 90, 130, 170, 110],
    "Revenue": [6000, 7500, 4500, 6500, 8500, 5500],
    "City": ["Karachi", "Karachi", "Lahore", "Karachi", "Lahore", "Islamabad"],
    "Temperature": [32, 32, 35, 33, 36, 30]
}

In [17]:
df = pd.DataFrame(sales_data)
df

         Date      Flavor  Sales  Revenue       City  Temperature
0  2026-04-01     Vanilla    120     6000    Karachi           32
1  2026-04-01   Chocolate    150     7500    Karachi           32
2  2026-04-02  Strawberry     90     4500     Lahore           35
3  2026-04-02     Vanilla    130     6500    Karachi           33
4  2026-04-03   Chocolate    170     8500     Lahore           36
5  2026-04-03       Mango    110     5500  Islamabad           30

In [21]:
df["Flavor"].value_counts()

Flavor
Vanilla       2
Chocolate     2
Strawberry    1
Mango         1
Name: count, dtype: int64

In [27]:
df.groupby("Flavor")["Sales"].sum()

Flavor
Chocolate     320
Mango         110
Strawberry     90
Vanilla       250
Name: Sales, dtype: int64

In [28]:
df.sort_values("Sales")

         Date      Flavor  Sales  Revenue       City  Temperature
2  2026-04-02  Strawberry     90     4500     Lahore           35
5  2026-04-03       Mango    110     5500  Islamabad           30
0  2026-04-01     Vanilla    120     6000    Karachi           32
3  2026-04-02     Vanilla    130     6500    Karachi           33
1  2026-04-01   Chocolate    150     7500    Karachi           32
4  2026-04-03   Chocolate    170     8500     Lahore           36

In [29]:
df.groupby("City")["Sales"].sum()

City
Islamabad    110
Karachi      400
Lahore       260
Name: Sales, dtype: int64

In [30]:
df.groupby("City").agg({"Revenue" : ["mean" ,"max", "sum"]})

               Revenue
                  mean   max    sum
City
Islamabad  5500.000000  5500   5500
Karachi    6666.666667  7500  20000
Lahore     6500.000000  8500  13000

In [36]:
df.groupby(["City", "Flavor"]).agg({"Revenue" :[ "mean" , "sum", "max"] ,"Sales" :[ "mean" , "sum", "max"]})

                     Revenue               Sales
                        mean    sum   max   mean  sum  max
City      Flavor
Islamabad Mango       5500.0   5500  5500  110.0  110  110
Karachi   Chocolate   7500.0   7500  7500  150.0  150  150
          Vanilla     6250.0  12500  6500  125.0  250  130
Lahore    Chocolate   8500.0   8500  8500  170.0  170  170
          Strawberry  4500.0   4500  4500   90.0   90   90

In [37]:
df

         Date      Flavor  Sales  Revenue       City  Temperature
0  2026-04-01     Vanilla    120     6000    Karachi           32
1  2026-04-01   Chocolate    150     7500    Karachi           32
2  2026-04-02  Strawberry     90     4500     Lahore           35
3  2026-04-02     Vanilla    130     6500    Karachi           33
4  2026-04-03   Chocolate    170     8500     Lahore           36
5  2026-04-03       Mango    110     5500  Islamabad           30

In [48]:
df.drop(df.columns[4] , axis =1 , inplace = True)
df

         Date      Flavor  Sales  Revenue
0  2026-04-01     Vanilla    120     6000
1  2026-04-01   Chocolate    150     7500
2  2026-04-02  Strawberry     90     4500
3  2026-04-02     Vanilla    130     6500
4  2026-04-03   Chocolate    170     8500
5  2026-04-03       Mango    110     5500

In [51]:
df.rename(columns = {"Revenue" : "Income"} , inplace = True)
df

         Date      Flavor  Sales  Income
0  2026-04-01     Vanilla    120    6000
1  2026-04-01   Chocolate    150    7500
2  2026-04-02  Strawberry     90    4500
3  2026-04-02     Vanilla    130    6500
4  2026-04-03   Chocolate    170    8500
5  2026-04-03       Mango    110    5500

In [52]:
df.loc[0, "Flavor"] = "Peach"
df

         Date      Flavor  Sales  Income
0  2026-04-01       Peach    120    6000
1  2026-04-01   Chocolate    150    7500
2  2026-04-02  Strawberry     90    4500
3  2026-04-02     Vanilla    130    6500
4  2026-04-03   Chocolate    170    8500
5  2026-04-03       Mango    110    5500

In [53]:
df.loc[(df.Flavor == "Chocolate") & (df.Sales > 100) & (df.Income > 5000)]

         Date     Flavor  Sales  Income
1  2026-04-01  Chocolate    150    7500
4  2026-04-03  Chocolate    170    8500

In [54]:
df.groupby("Flavor")["Income"].sum()

Flavor
Chocolate     16000
Mango          5500
Peach          6000
Strawberry     4500
Vanilla        6500
Name: Income, dtype: int64

In [2]:
df =pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.xlsx", sheet_name ="Sheet3",header =2 )
df

,Unnamed: 0,Country,Region,Stock_Market_Cap_BnUSD,Gold_Reserves_Tonnes
0,NaN,USA,North America,50000,8133
1,NaN,China,Asia,11000,2300
2,NaN,Japan,Asia,6500,845
3,NaN,Germany,Europe,2500,3350
4,NaN,India,Asia,5000,880
5,NaN,UK,Europe,3000,310
6,NaN,France,Europe,2800,2436
7,NaN,Italy,Europe,2000,2451
8,NaN,Canada,North America,2200,77
9,NaN,Brazil,South America,1800,130
10,NaN,Australia,Oceania,1600,280
11,NaN,South Korea,Asia,2100,104
12,NaN,Spain,Europe,1200,281
13,NaN,Mexico,North America,900,120
14,NaN,Indonesia,Asia,850,78
15,NaN,Turkey,Asia,700,540
16,NaN,Netherlands,Europe,1500,612
17,NaN,Switzerland,Europe,1900,1040
18,NaN,Saudi Arabia,Asia,800,323

In [5]:
df.drop(df.columns[0], axis =1 ,inplace = True )
df

         Country         Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0            USA  North America                   50000                  8133
1          China           Asia                   11000                  2300
2          Japan           Asia                    6500                   845
3        Germany         Europe                    2500                  3350
4          India           Asia                    5000                   880
5             UK         Europe                    3000                   310
6         France         Europe                    2800                  2436
7          Italy         Europe                    2000                  2451
8         Canada  North America                    2200                    77
9         Brazil  South America                    1800                   130
10     Australia        Oceania                    1600                   280
11   South Korea           Asia                    2100                   104
12         Spain         Europe                    1200                   281
13        Mexico  North America                     900                   120
14     Indonesia           Asia                     850                    78
15        Turkey           Asia                     700                   540
16   Netherlands         Europe                    1500                   612
17   Switzerland         Europe                    1900                  1040
18  Saudi Arabia           Asia                     800                   323

In [8]:
df[df["Country"] == "Saudi Arabia"]

         Country Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
18  Saudi Arabia   Asia                     800                   323

In [9]:
df["Country"][0:1]

0    USA
Name: Country, dtype: str

In [11]:
df.loc[0:1]

  Country         Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0     USA  North America                   50000                  8133
1   China           Asia                   11000                  2300

In [13]:
df[df["Country"].str.contains("A")]

         Country         Region  Stock_Market_Cap_BnUSD  Gold_Reserves_Tonnes
0            USA  North America                   50000                  8133
10     Australia        Oceania                    1600                   280
18  Saudi Arabia           Asia                     800                   323

In [14]:
df.rename(columns = {"Stock_Market_Cap_BnUSD": "Stock Market" ,  "Gold_Reserves_Tonnes" : "Gold"} , inplace = True)
df

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
1          China           Asia         11000  2300
2          Japan           Asia          6500   845
3        Germany         Europe          2500  3350
4          India           Asia          5000   880
5             UK         Europe          3000   310
6         France         Europe          2800  2436
7          Italy         Europe          2000  2451
8         Canada  North America          2200    77
9         Brazil  South America          1800   130
10     Australia        Oceania          1600   280
11   South Korea           Asia          2100   104
12         Spain         Europe          1200   281
13        Mexico  North America           900   120
14     Indonesia           Asia           850    78
15        Turkey           Asia           700   540
16   Netherlands         Europe          1500   612
17   Switzerland         Europe          1900  1040
18  Saudi Arabia           Asia           800   323

In [15]:
df[(df["Region"] == "Asia") & (df["Stock Market"] > 1200)  & (df["Gold"] > 2000)]

  Country Region  Stock Market  Gold
1   China   Asia         11000  2300

In [16]:
df.loc[(df["Region"] == "Europe") & (df["Stock Market"] > 1300)]

        Country  Region  Stock Market  Gold
3       Germany  Europe          2500  3350
5            UK  Europe          3000   310
6        France  Europe          2800  2436
7         Italy  Europe          2000  2451
16  Netherlands  Europe          1500   612
17  Switzerland  Europe          1900  1040

In [18]:
df.loc[len(df)] = ["Pakistan" , "Asia" , 2121 , 3333]
df

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
1          China           Asia         11000  2300
2          Japan           Asia          6500   845
3        Germany         Europe          2500  3350
4          India           Asia          5000   880
5             UK         Europe          3000   310
6         France         Europe          2800  2436
7          Italy         Europe          2000  2451
8         Canada  North America          2200    77
9         Brazil  South America          1800   130
10     Australia        Oceania          1600   280
11   South Korea           Asia          2100   104
12         Spain         Europe          1200   281
13        Mexico  North America           900   120
14     Indonesia           Asia           850    78
15        Turkey           Asia           700   540
16   Netherlands         Europe          1500   612
17   Switzerland         Europe          1900  1040
18  Saudi Arabia           Asia           800   323
19      Pakistan           Asia          2121  3333
20      Pakistan           Asia          2121  3333

In [20]:
df.drop(df[df.Country == "Pakistan"].index, inplace =True)
df

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
1          China           Asia         11000  2300
2          Japan           Asia          6500   845
3        Germany         Europe          2500  3350
4          India           Asia          5000   880
5             UK         Europe          3000   310
6         France         Europe          2800  2436
7          Italy         Europe          2000  2451
8         Canada  North America          2200    77
9         Brazil  South America          1800   130
10     Australia        Oceania          1600   280
11   South Korea           Asia          2100   104
12         Spain         Europe          1200   281
13        Mexico  North America           900   120
14     Indonesia           Asia           850    78
15        Turkey           Asia           700   540
16   Netherlands         Europe          1500   612
17   Switzerland         Europe          1900  1040
18  Saudi Arabia           Asia           800   323

In [21]:
df.loc[len(df)] = ["Pakistan" ,  "Asia" , 2121, 3333]
df

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
1          China           Asia         11000  2300
2          Japan           Asia          6500   845
3        Germany         Europe          2500  3350
4          India           Asia          5000   880
5             UK         Europe          3000   310
6         France         Europe          2800  2436
7          Italy         Europe          2000  2451
8         Canada  North America          2200    77
9         Brazil  South America          1800   130
10     Australia        Oceania          1600   280
11   South Korea           Asia          2100   104
12         Spain         Europe          1200   281
13        Mexico  North America           900   120
14     Indonesia           Asia           850    78
15        Turkey           Asia           700   540
16   Netherlands         Europe          1500   612
17   Switzerland         Europe          1900  1040
18  Saudi Arabia           Asia           800   323
19      Pakistan           Asia          2121  3333

In [22]:
df.drop(df[df.Country == "Indonesia"].index , inplace = True)
df

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
1          China           Asia         11000  2300
2          Japan           Asia          6500   845
3        Germany         Europe          2500  3350
4          India           Asia          5000   880
5             UK         Europe          3000   310
6         France         Europe          2800  2436
7          Italy         Europe          2000  2451
8         Canada  North America          2200    77
9         Brazil  South America          1800   130
10     Australia        Oceania          1600   280
11   South Korea           Asia          2100   104
12         Spain         Europe          1200   281
13        Mexico  North America           900   120
15        Turkey           Asia           700   540
16   Netherlands         Europe          1500   612
17   Switzerland         Europe          1900  1040
18  Saudi Arabia           Asia           800   323
19      Pakistan           Asia          2121  3333

In [25]:
df.sort_values("Gold" , ascending = False)

         Country         Region  Stock Market  Gold
0            USA  North America         50000  8133
3        Germany         Europe          2500  3350
19      Pakistan           Asia          2121  3333
7          Italy         Europe          2000  2451
6         France         Europe          2800  2436
1          China           Asia         11000  2300
17   Switzerland         Europe          1900  1040
4          India           Asia          5000   880
2          Japan           Asia          6500   845
16   Netherlands         Europe          1500   612
15        Turkey           Asia           700   540
18  Saudi Arabia           Asia           800   323
5             UK         Europe          3000   310
12         Spain         Europe          1200   281
10     Australia        Oceania          1600   280
9         Brazil  South America          1800   130
13        Mexico  North America           900   120
11   South Korea           Asia          2100   104
8         Canada  North America          2200    77

In [26]:
df.isnull()

    Country  Region  Stock Market   Gold
0     False   False         False  False
1     False   False         False  False
2     False   False         False  False
3     False   False         False  False
4     False   False         False  False
5     False   False         False  False
6     False   False         False  False
7     False   False         False  False
8     False   False         False  False
9     False   False         False  False
10    False   False         False  False
11    False   False         False  False
12    False   False         False  False
13    False   False         False  False
15    False   False         False  False
16    False   False         False  False
17    False   False         False  False
18    False   False         False  False
19    False   False         False  False