In [1]:
import pandas as pd

In [3]:
data = {
    "Name": [
        "Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"
    ],
    "Salary": [
        95000, 72000, 105000, 88000, 62000, 
        115000, 54000, 91000, 78000, 83000
    ],
    "Position": [
        "Software Engineer", "Data Scientist", "Project Manager", "UX Designer", "Intern",
        "CTO", "Marketing Associate", "DevOps Engineer", "Sales Lead", "Product Owner"
    ]
}

In [4]:
df = pd.DataFrame(data)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [5]:
df[df["Salary"] > 100000]

   Name  Salary         Position
2  Noah  105000  Project Manager
5   Ava  115000              CTO

In [6]:
df["Name"][0:4]

0      Liam
1    Sophia
2      Noah
3      Emma
Name: Name, dtype: str

In [7]:
df.rename(columns = {"Position" : "Post"} , inplace = True )
df

       Name  Salary                 Post
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [8]:
df.drop(df.columns[0] ,axis = 1,  inplace = True)
df

   Salary                 Post
0   95000    Software Engineer
1   72000       Data Scientist
2  105000      Project Manager
3   88000          UX Designer
4   62000               Intern
5  115000                  CTO
6   54000  Marketing Associate
7   91000      DevOps Engineer
8   78000           Sales Lead
9   83000        Product Owner

In [9]:
df["Name"] = ["Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"]
df

   Salary                 Post      Name
0   95000    Software Engineer      Liam
1   72000       Data Scientist    Sophia
2  105000      Project Manager      Noah
3   88000          UX Designer      Emma
4   62000               Intern    Oliver
5  115000                  CTO       Ava
6   54000  Marketing Associate     Ethan
7   91000      DevOps Engineer  Isabella
8   78000           Sales Lead     Lucas
9   83000        Product Owner       Mia

In [10]:
df["Bonus"] = df["Salary"] * 0.25
df["Total"] = df["Salary"] + df["Bonus"]
df

   Salary                 Post      Name    Bonus     Total
0   95000    Software Engineer      Liam  23750.0  118750.0
1   72000       Data Scientist    Sophia  18000.0   90000.0
2  105000      Project Manager      Noah  26250.0  131250.0
3   88000          UX Designer      Emma  22000.0  110000.0
4   62000               Intern    Oliver  15500.0   77500.0
5  115000                  CTO       Ava  28750.0  143750.0
6   54000  Marketing Associate     Ethan  13500.0   67500.0
7   91000      DevOps Engineer  Isabella  22750.0  113750.0
8   78000           Sales Lead     Lucas  19500.0   97500.0
9   83000        Product Owner       Mia  20750.0  103750.0

In [11]:
df[df["Salary"] > 95000]

   Salary             Post  Name    Bonus     Total
2  105000  Project Manager  Noah  26250.0  131250.0
5  115000              CTO   Ava  28750.0  143750.0

In [12]:
df.columns

Index(['Salary', 'Post', 'Name', 'Bonus', 'Total'], dtype='str')

In [13]:
df.loc[8 , "Salary"] = 545454
df

   Salary                 Post      Name    Bonus     Total
0   95000    Software Engineer      Liam  23750.0  118750.0
1   72000       Data Scientist    Sophia  18000.0   90000.0
2  105000      Project Manager      Noah  26250.0  131250.0
3   88000          UX Designer      Emma  22000.0  110000.0
4   62000               Intern    Oliver  15500.0   77500.0
5  115000                  CTO       Ava  28750.0  143750.0
6   54000  Marketing Associate     Ethan  13500.0   67500.0
7   91000      DevOps Engineer  Isabella  22750.0  113750.0
8  545454           Sales Lead     Lucas  19500.0   97500.0
9   83000        Product Owner       Mia  20750.0  103750.0

In [14]:
data1 = {
    "Order_ID": [
        201,202,203,204,205,206,207,208,209,210,
        211,212,213,214,215
    ],
    "Product": [
        "iPhone 15","MacBook Air","iPad Pro","AirPods Pro","Apple Watch",
        "iPhone 14","MacBook Pro","iPad Air","AirPods Max","Apple Watch Ultra",
        "iMac","iPhone 13","Mac Mini","iPad Mini","AirPods 3"
    ],
    "Category": [
        "iPhone","Mac","iPad","Accessories","Wearables",
        "iPhone","Mac","iPad","Accessories","Wearables",
        "Mac","iPhone","Mac","iPad","Accessories"
    ],
    "Price": [
        280000,350000,250000,75000,120000,
        240000,500000,180000,150000,220000,
        400000,200000,180000,140000,60000
    ],
    "Quantity": [
        2,1,1,3,2,
        2,1,2,1,1,
        1,3,2,2,4
    ],
    "Region": [
        "Karachi","Lahore","Islamabad","Karachi","Lahore",
        "Islamabad","Karachi","Lahore","Islamabad","Karachi",
        "Lahore","Islamabad","Karachi","Lahore","Islamabad"
    ],
    "Order_Date": [
        "2024-01-05","2024-01-10","2024-01-15","2024-01-20","2024-01-25",
        "2024-02-01","2024-02-05","2024-02-10","2024-02-15","2024-02-20",
        "2024-03-01","2024-03-05","2024-03-10","2024-03-15","2024-03-20"
    ]
}

In [15]:
df = pd.DataFrame(data1)
df

,Order_ID,Product,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [16]:
df.rename(columns = {"Product" : "Type" } , inplace  = True)
df

,Order_ID,Type,Category,Price,Quantity,Region,Order_Date
0,201,iPhone 15,iPhone,280000,2,Karachi,2024-01-05
1,202,MacBook Air,Mac,350000,1,Lahore,2024-01-10
2,203,iPad Pro,iPad,250000,1,Islamabad,2024-01-15
3,204,AirPods Pro,Accessories,75000,3,Karachi,2024-01-20
4,205,Apple Watch,Wearables,120000,2,Lahore,2024-01-25
5,206,iPhone 14,iPhone,240000,2,Islamabad,2024-02-01
6,207,MacBook Pro,Mac,500000,1,Karachi,2024-02-05
7,208,iPad Air,iPad,180000,2,Lahore,2024-02-10
8,209,AirPods Max,Accessories,150000,1,Islamabad,2024-02-15
9,210,Apple Watch Ultra,Wearables,220000,1,Karachi,2024-02-20
10,211,iMac,Mac,400000,1,Lahore,2024-03-01
11,212,iPhone 13,iPhone,200000,3,Islamabad,2024-03-05
12,213,Mac Mini,Mac,180000,2,Karachi,2024-03-10
13,214,iPad Mini,iPad,140000,2,Lahore,2024-03-15
14,215,AirPods 3,Accessories,60000,4,Islamabad,2024-03-20

In [17]:
df.loc[(df.Category == "iPhone" ) & (df.Price > 100000) & (df.Region == "Karachi")]

   Order_ID       Type Category   Price  Quantity   Region  Order_Date
0       201  iPhone 15   iPhone  280000         2  Karachi  2024-01-05

In [18]:
df[df["Category"].str.contains("Mac" , "iPad")]

    Order_ID         Type Category   Price  Quantity   Region  Order_Date
1        202  MacBook Air      Mac  350000         1   Lahore  2024-01-10
6        207  MacBook Pro      Mac  500000         1  Karachi  2024-02-05
10       211         iMac      Mac  400000         1   Lahore  2024-03-01
12       213     Mac Mini      Mac  180000         2  Karachi  2024-03-10

In [22]:
df.isnull().sum()

Order_ID      0
Type          0
Category      0
Price         0
Quantity      0
Region        0
Order_Date    0
dtype: int64

In [23]:
df["Category"].value_counts()

Category
Mac            4
iPhone         3
iPad           3
Accessories    3
Wearables      2
Name: count, dtype: int64

In [25]:
df.groupby("Category")["Price"].sum()

Category
Accessories     285000
Mac            1430000
Wearables       340000
iPad            570000
iPhone          720000
Name: Price, dtype: int64

In [28]:
df.groupby("Category").agg({"Price" : "mean" , "Order_ID" : "count"})

                Price  Order_ID
Category
Accessories   95000.0         3
Mac          357500.0         4
Wearables    170000.0         2
iPad         190000.0         3
iPhone       240000.0         3

In [2]:
df = pd.read_csv(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\countries.csv")
df

        Country  Region  Population  GDP_per_capita
0      Pakistan    Asia   240000000            1500
1         India    Asia  1400000000            2500
2         China    Asia  1410000000           12000
3       Germany  Europe    83000000           48000
4        France  Europe    67000000           45000
..          ...     ...         ...             ...
91       Rwanda  Africa    14000000             900
92      Burundi  Africa    13000000             300
93     Cameroon  Africa    28000000            1600
94      Senegal  Africa    18000000            1800
95  Ivory Coast  Africa    28000000            2500

[96 rows x 4 columns]

In [3]:
df.describe()

         Population  GDP_per_capita
count  9.600000e+01       96.000000
mean   7.187208e+07    21103.125000
std    2.048841e+08    24797.230122
min    3.700000e+05      300.000000
25%    6.950000e+06     3500.000000
50%    1.900000e+07     9000.000000
75%    5.275000e+07    38500.000000
max    1.410000e+09   120000.000000

In [4]:
df.rename(columns = {"GDP_per_capita" : "GDP"}, inplace = True)
df

        Country  Region  Population    GDP
0      Pakistan    Asia   240000000   1500
1         India    Asia  1400000000   2500
2         China    Asia  1410000000  12000
3       Germany  Europe    83000000  48000
4        France  Europe    67000000  45000
..          ...     ...         ...    ...
91       Rwanda  Africa    14000000    900
92      Burundi  Africa    13000000    300
93     Cameroon  Africa    28000000   1600
94      Senegal  Africa    18000000   1800
95  Ivory Coast  Africa    28000000   2500

[96 rows x 4 columns]

In [5]:
df.set_index("Country", inplace = True)
df

             Region  Population    GDP
Country
Pakistan       Asia   240000000   1500
India          Asia  1400000000   2500
China          Asia  1410000000  12000
Germany      Europe    83000000  48000
France       Europe    67000000  45000
...             ...         ...    ...
Rwanda       Africa    14000000    900
Burundi      Africa    13000000    300
Cameroon     Africa    28000000   1600
Senegal      Africa    18000000   1800
Ivory Coast  Africa    28000000   2500

[96 rows x 3 columns]

In [6]:
df.loc["Pakistan"]

Region             Asia
Population    240000000
GDP                1500
Name: Pakistan, dtype: object

In [7]:
df.reset_index(inplace = True)

In [8]:
df.set_index(["Region", "Country"] , inplace = True)
df

                    Population    GDP
Region Country
Asia   Pakistan      240000000   1500
       India        1400000000   2500
       China        1410000000  12000
Europe Germany        83000000  48000
       France         67000000  45000
...                        ...    ...
Africa Rwanda         14000000    900
       Burundi        13000000    300
       Cameroon       28000000   1600
       Senegal        18000000   1800
       Ivory Coast    28000000   2500

[96 rows x 2 columns]

In [10]:
pd.set_option("display.max_rows" , 96)
df

                                  Population     GDP
Region        Country
Asia          Pakistan             240000000    1500
              India               1400000000    2500
              China               1410000000   12000
Europe        Germany               83000000   48000
              France                67000000   45000
              UK                    67000000   46000
North America USA                  331000000   70000
              Canada                38000000   52000
South America Brazil               215000000    9000
              Argentina             45000000   10000
Africa        Nigeria              223000000    2200
              South Africa          60000000    7000
Oceania       Australia             26000000   55000
              New Zealand            5000000   48000
Asia          Japan                125000000   42000
              Bangladesh           170000000    2800
              Indonesia            275000000    5000
              Philippines          115000000    3500
              Vietnam              100000000    4000
              Thailand              70000000    7500
Europe        Italy                 59000000   40000
              Spain                 47000000   38000
              Netherlands           17000000   52000
              Belgium               11500000   51000
              Sweden                10500000   55000
              Norway                 5400000   75000
              Denmark                5800000   60000
              Finland                5500000   53000
              Poland                38000000   18000
              Ukraine               36000000    5000
North America Mexico               128000000   10000
              Cuba                  11000000    9000
              Dominican Republic    11000000    8500
              Guatemala             18000000    5000
              Panama                 4400000   15000
South America Chile                 19000000   16000
              Peru                  34000000    7000
              Colombia              52000000    6500
              Venezuela             28000000    4000
              Bolivia               12000000    3500
              Ecuador               18000000    6000
Africa        Egypt                110000000    3500
              Ethiopia             120000000    1000
              Kenya                 55000000    2000
              Tanzania              65000000    1500
              Uganda                48000000     900
              Ghana                 33000000    2500
              Morocco               37000000    3500
              Algeria               45000000    4000
              Sudan                 45000000     800
              Angola                35000000    3000
Asia          Saudi Arabia          36000000   27000
              UAE                   10000000   43000
              Qatar                  3000000   60000
              Kuwait                 4300000   48000
              Oman                   4500000   20000
              Turkey                85000000   10000
              Iran                  88000000    5000
              Iraq                  45000000    4500
              Israel                 9500000   52000
              Jordan                11000000    4500
Europe        Greece                10400000   22000
              Portugal              10200000   25000
              Ireland                5000000   85000
              Switzerland            8700000   90000
              Austria                9000000   55000
              Czech Republic        10700000   27000
              Hungary                9600000   19000
              Romania               19000000   15000
              Bulgaria               6800000   13000
              Serbia                 6800000    9000
              Croatia                4000000   17000
              Slovakia               5400000   21000
              Slovenia               2100000   30000
              Iceland                 370000   70000
              Luxembourg              650000  120000
North America Costa Rica             5200000   13000
              Honduras              10000000    3000
              El Salvador            6500000    4500
              Nicaragua              6800000    2500
South America Paraguay               7000000    6000
              Uruguay                3500000   18000
              Suriname                600000   14000
              Guyana                  800000   15000
Africa        Botswana               2600000    7000
              Namibia                2600000    5000
              Zambia                20000000    1500
              Zimbabwe              16000000    2000
              Malawi                20000000     800
              Mozambique            33000000     700
              Madagascar            30000000     600
              Rwanda                14000000     900
              Burundi               13000000     300
              Cameroon              28000000    1600
              Senegal               18000000    1800
              Ivory Coast           28000000    2500

In [12]:
df.loc["Asia" , "Pakistan"]

Population    240000000
GDP                1500
Name: (Asia, Pakistan), dtype: int64

In [15]:
df.groupby("Region").agg({"Population" : "sum" })

               Population
Region
Africa         1101200000
Asia           4201300000
Europe          561420000
North America   569900000
Oceania          31000000
South America   434900000

In [18]:
df.groupby("Region").agg({"Population" : "min" , "GDP" : "max"})

               Population     GDP
Region
Africa            2600000    7000
Asia              3000000   60000
Europe             370000  120000
North America     4400000   70000
Oceania           5000000   55000
South America      600000   18000

In [19]:
df.loc[df.groupby("Region")["GDP"].idxmax()]

                            Population     GDP
Region        Country
Africa        South Africa    60000000    7000
Asia          Qatar            3000000   60000
Europe        Luxembourg        650000  120000
North America USA            331000000   70000
Oceania       Australia       26000000   55000
South America Uruguay          3500000   18000

In [3]:
data = {
    "Name": [
        "Liam", "Sophia", "Noah", "Emma", "Oliver", 
        "Ava", "Ethan", "Isabella", "Lucas", "Mia"
    ],
    "Salary": [
        95000, 72000, 105000, 88000, 62000, 
        115000, 54000, 91000, 78000, 83000
    ],
    "Position": [
        "Software Engineer", "Data Scientist", "Project Manager", "UX Designer", "Intern",
        "CTO", "Marketing Associate", "DevOps Engineer", "Sales Lead", "Product Owner"
    ]}

In [5]:
df  = pd.DataFrame(data)
df

       Name  Salary             Position
0      Liam   95000    Software Engineer
1    Sophia   72000       Data Scientist
2      Noah  105000      Project Manager
3      Emma   88000          UX Designer
4    Oliver   62000               Intern
5       Ava  115000                  CTO
6     Ethan   54000  Marketing Associate
7  Isabella   91000      DevOps Engineer
8     Lucas   78000           Sales Lead
9       Mia   83000        Product Owner

In [8]:
df[["Name" , "Salary"]].head()

     Name  Salary
0    Liam   95000
1  Sophia   72000
2    Noah  105000
3    Emma   88000
4  Oliver   62000

In [11]:
df.iloc[2:4 , 0:1]  # first is for rows and after comma is for columns

   Name
2  Noah
3  Emma

In [13]:
df[["Name" , "Salary"]].iloc[1:8]

       Name  Salary
1    Sophia   72000
2      Noah  105000
3      Emma   88000
4    Oliver   62000
5       Ava  115000
6     Ethan   54000
7  Isabella   91000

In [17]:
df.loc[len(df)] = ["Ali", 100000 , "AI engineer"]
df

        Name  Salary             Position
0       Liam   95000    Software Engineer
1     Sophia   72000       Data Scientist
2       Noah  105000      Project Manager
3       Emma   88000          UX Designer
4     Oliver   62000               Intern
5        Ava  115000                  CTO
6      Ethan   54000  Marketing Associate
7   Isabella   91000      DevOps Engineer
8      Lucas   78000           Sales Lead
9        Mia   83000        Product Owner
10       Ali  100000          AI engineer

In [18]:
df.loc[len(df)-3] = ["Shahzaib", 100000 , "AI engineer"]
df

        Name  Salary             Position
0       Liam   95000    Software Engineer
1     Sophia   72000       Data Scientist
2       Noah  105000      Project Manager
3       Emma   88000          UX Designer
4     Oliver   62000               Intern
5        Ava  115000                  CTO
6      Ethan   54000  Marketing Associate
7   Isabella   91000      DevOps Engineer
8   Shahzaib  100000          AI engineer
9        Mia   83000        Product Owner
10       Ali  100000          AI engineer

In [20]:
len(df.Position.unique())

10

In [24]:
df[(df.Position == "Product Owner") & (df.Salary > 50000)]

  Name  Salary       Position
9  Mia   83000  Product Owner

In [25]:
df = pd.read_excel(r"C:\Users\asifb\OneDrive\Desktop\Python language\Jupyter Notebook\Data sets\messy_sales_data.xlsx")
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status
0,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
1,1002,2024-01-07,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,NaN,0.0,Bob Smith,Pending
2,1001,2024-01-05,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
3,1003,2024-01-10,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,NaN,5.0,Carol White,Completed
4,1004,2024-01-12,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,NaN,David Brown,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,NaN,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,NaN,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,NaN,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,NaN,0.0,Bob Smith,Completed
100,1100,2024-12-10,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,NaN,0.0,Bob Smith,Pending

In [28]:
type(df.Date[0])

str

In [35]:
df["Date"] = pd.to_datetime(df.Date, format = "mixed" , dayfirst = True)

In [36]:
type(df["Date"])

pandas.Series

In [40]:
df["Date"][0:2].dt.month

0    5
1    7
Name: Date, dtype: int32

In [41]:
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status
0,1001,2024-05-01,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
1,1002,2024-07-01,Jane Smith,jane.smith@email.com,South,Mouse,Accessories,5,29.99,NaN,0.0,Bob Smith,Pending
2,1001,2024-05-01,John Doe,john.doe@email.com,North,Laptop,Electronics,2,999.99,NaN,10.0,Alice Johnson,Completed
3,1003,2024-10-01,NaN,carol@email.com,East,Keyboard,Accessories,3,49.99,NaN,5.0,Carol White,Completed
4,1004,2024-12-01,Mike Brown,NaN,West,Monitor,Electronics,1,299.99,NaN,NaN,David Brown,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,1096,2024-02-13,Eve Hall,evehall@email.com,West,Keyboard,Accessories,3,966.19,NaN,10.0,David Brown,Completed
97,1097,2024-09-25,Hank Jones,hankjones@gmail.com,South,Mouse,Accessories,10,950.14,NaN,0.0,Bob Smith,Completed
98,1098,2024-10-20,Grace Young,graceyoung@yahoo.com,West,Monitor,Electronics,8,311.41,NaN,20.0,David Brown,Pending
99,1099,2024-03-18,Alice Young,aliceyoung@gmail.com,South,Webcam,Electronics,4,279.35,NaN,0.0,Bob Smith,Completed
100,1100,2024-10-12,Bob Brown,bobbrown@gmail.com,West,Monitor,Electronics,10,480.51,NaN,0.0,Bob Smith,Pending

In [45]:
df["Month"] = df["Date"].dt.month

In [48]:
df.sort_values("Date", inplace = True)

In [49]:
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Total_Sales,Discount_%,Sales_Rep,Status,Month
24,1024,2024-01-03,NaN,n/a@email.com,East,Laptop,Electronics,1,999.99,NaN,0.0,NaN,Pending,1.0
6,1006,2024-01-15,Tom Clark,tom@email.com,South,Webcam,Electronics,three,79.99,NaN,0.0,Bob Smith,Completed,1.0
7,1007,2024-01-18,Lisa Hall,lisa@email.com,East,Headphones,Accessories,4,expensive,NaN,10.0,Carol White,Completed,1.0
95,1095,2024-01-19,Carol Wilson,carolwilson@gmail.com,North,Headphones,Accessories,5,703.47,NaN,5.0,David Brown,Completed,1.0
8,1008,2024-01-20,James Wilson,james@email.com,north,laptop,electronics,1,999.99,NaN,5.0,alice johnson,completed,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,1092,2024-12-15,Dave Wilson,davewilson@hotmail.com,West,Headphones,Accessories,9,356.88,NaN,20.0,Carol White,Pending,12.0
43,1043,2024-12-16,Alice Jones,alicejones@hotmail.com,East,Mouse,Accessories,1,256.05,NaN,20.0,Alice Johnson,Completed,12.0
94,1094,2024-12-18,Hank Wilson,hankwilson@hotmail.com,North,Mouse,Accessories,5,242.93,NaN,5.0,Carol White,Completed,12.0
63,1063,2024-12-26,Dave Brown,davebrown@yahoo.com,West,Laptop,Electronics,3,741.83,NaN,10.0,David Brown,Cancelled,12.0
5,1005,NaT,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,NaN,15.0,Alice Johnson,Pending,NaN

In [51]:
df.drop(labels = "Total_Sales" , axis =1 , inplace = True )
df

,Order_ID,Date,Customer_Name,Email,Region,Product,Category,Quantity,Unit_Price,Discount_%,Sales_Rep,Status,Month
24,1024,2024-01-03,NaN,n/a@email.com,East,Laptop,Electronics,1,999.99,0.0,NaN,Pending,1.0
6,1006,2024-01-15,Tom Clark,tom@email.com,South,Webcam,Electronics,three,79.99,0.0,Bob Smith,Completed,1.0
7,1007,2024-01-18,Lisa Hall,lisa@email.com,East,Headphones,Accessories,4,expensive,10.0,Carol White,Completed,1.0
95,1095,2024-01-19,Carol Wilson,carolwilson@gmail.com,North,Headphones,Accessories,5,703.47,5.0,David Brown,Completed,1.0
8,1008,2024-01-20,James Wilson,james@email.com,north,laptop,electronics,1,999.99,5.0,alice johnson,completed,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,1092,2024-12-15,Dave Wilson,davewilson@hotmail.com,West,Headphones,Accessories,9,356.88,20.0,Carol White,Pending,12.0
43,1043,2024-12-16,Alice Jones,alicejones@hotmail.com,East,Mouse,Accessories,1,256.05,20.0,Alice Johnson,Completed,12.0
94,1094,2024-12-18,Hank Wilson,hankwilson@hotmail.com,North,Mouse,Accessories,5,242.93,5.0,Carol White,Completed,12.0
63,1063,2024-12-26,Dave Brown,davebrown@yahoo.com,West,Laptop,Electronics,3,741.83,10.0,David Brown,Cancelled,12.0
5,1005,NaT,Sara Lee,sara@email.com,North,NaN,Electronics,2,149.99,15.0,Alice Johnson,Pending,NaN

In [59]:
df.dropna(subset= ["Date" , "Customer_Name", "Sales_Rep", "Email" , "Status"] , inplace =  True)

In [75]:
df["Unit_price1"] = pd.to_numeric(df["Unit_Price"] , errors = "coerce")

In [76]:
df["Unit_price1"].max()

np.float64(999.99)

In [80]:
df.drop(labels = "Unit_price" , axis =1 , inplace = True)

In [88]:
df["Unit_price1"].idxmin()

np.int64(11)

In [93]:
df["Unit_price1"].idxmin()

np.int64(11)

In [95]:
df.loc[11]

Order_ID                        1011
Date             2024-01-27 00:00:00
Customer_Name            Anna Taylor
Email                 anna@email.com
Region                         North
Product                     Keyboard
Category                 Accessories
Quantity                           2
Discount_%                       0.0
Sales_Rep              Alice Johnson
Status                     Completed
Month                            1.0
Unit_price1                   -49.99
Name: 11, dtype: object

In [98]:
df["Category"].value_counts()

Category
Electronics    52
Accessories    42
electronics     1
ACCESSORIES     1
Name: count, dtype: int64

In [101]:
df.groupby("Category")["Unit_price1"].sum()

Category
ACCESSORIES       29.99
Accessories    14431.94
Electronics    21015.01
electronics      999.99
Name: Unit_price1, dtype: float64

In [104]:
df["Category"] = df["Category"].str.title()

In [109]:
df.groupby(["Category","Status"])["Unit_price1"].sum()

Category     Status
Accessories  Cancelled    5324.86
             Cancled        49.99
             Completed    5965.18
             PENDING        29.99
             Pending      3091.91
Electronics  Cancelled    8014.70
             Compelted     299.99
             Completed    8937.66
             Pending      3762.66
             completed     999.99
Name: Unit_price1, dtype: float64

In [111]:
df.groupby("Category")[["Unit_price1","Discount_%"]].mean()

             Unit_price1  Discount_%
Category
Accessories   344.331667   10.833333
Electronics   415.377358    8.301887

In [2]:
data = {
    "Job_Title": [
        "Software Engineer", "Software Engineer", "Software Engineer",
        "Data Analyst", "Data Analyst", "Data Analyst",
        "Data Scientist", "Data Scientist", "Data Scientist",
        "Frontend Developer", "Frontend Developer", "Frontend Developer",
        "DevOps Engineer", "DevOps Engineer", "DevOps Engineer",
        "Accountant", "Accountant", "Accountant",
        "Financial Analyst", "Financial Analyst", "Financial Analyst",
        "Bank Officer", "Bank Officer", "Bank Officer",
        "Marketing Manager", "Marketing Manager", "Marketing Manager",
        "SEO Specialist", "SEO Specialist", "SEO Specialist",
        "Content Writer", "Content Writer", "Content Writer",
        "Doctor (MBBS)", "Doctor (MBBS)", "Doctor (MBBS)",
        "Pharmacist", "Pharmacist", "Pharmacist",
        "Nurse", "Nurse", "Nurse",
        "Civil Engineer", "Civil Engineer", "Civil Engineer",
        "Mechanical Engineer", "Mechanical Engineer", "Mechanical Engineer",
    ],
    "Category": [
        "Tech", "Tech", "Tech",
        "Tech", "Tech", "Tech",
        "Tech", "Tech", "Tech",
        "Tech", "Tech", "Tech",
        "Tech", "Tech", "Tech",
        "Finance", "Finance", "Finance",
        "Finance", "Finance", "Finance",
        "Finance", "Finance", "Finance",
        "Marketing", "Marketing", "Marketing",
        "Marketing", "Marketing", "Marketing",
        "Marketing", "Marketing", "Marketing",
        "Healthcare", "Healthcare", "Healthcare",
        "Healthcare", "Healthcare", "Healthcare",
        "Healthcare", "Healthcare", "Healthcare",
        "Engineering", "Engineering", "Engineering",
        "Engineering", "Engineering", "Engineering",
    ],
    "City": [
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Rawalpindi",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Peshawar",
        "Karachi", "Lahore", "Faisalabad",
        "Karachi", "Lahore", "Islamabad",
        "Karachi", "Lahore", "Islamabad",
    ],
    "Experience": [
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
        "Junior (0-2 yrs)", "Mid (3-5 yrs)", "Senior (6+ yrs)",
    ],
    "Salary_PKR": [
        85000, 150000, 280000,
        70000, 120000, 220000,
        90000, 160000, 320000,
        75000, 140000, 260000,
        80000, 160000, 300000,
        55000, 90000, 160000,
        65000, 120000, 210000,
        60000, 95000, 170000,
        70000, 110000, 200000,
        50000, 85000, 140000,
        40000, 70000, 120000,
        120000, 220000, 420000,
        65000, 100000, 180000,
        45000, 70000, 120000,
        70000, 130000, 240000,
        65000, 120000, 220000,
    ]
}

In [3]:
df = pd.DataFrame(data)
df

              Job_Title     Category        City        Experience  Salary_PKR
0     Software Engineer         Tech     Karachi  Junior (0-2 yrs)       85000
1     Software Engineer         Tech      Lahore     Mid (3-5 yrs)      150000
2     Software Engineer         Tech   Islamabad   Senior (6+ yrs)      280000
3          Data Analyst         Tech     Karachi  Junior (0-2 yrs)       70000
4          Data Analyst         Tech      Lahore     Mid (3-5 yrs)      120000
5          Data Analyst         Tech   Islamabad   Senior (6+ yrs)      220000
6        Data Scientist         Tech     Karachi  Junior (0-2 yrs)       90000
7        Data Scientist         Tech      Lahore     Mid (3-5 yrs)      160000
8        Data Scientist         Tech   Islamabad   Senior (6+ yrs)      320000
9    Frontend Developer         Tech     Karachi  Junior (0-2 yrs)       75000
10   Frontend Developer         Tech      Lahore     Mid (3-5 yrs)      140000
11   Frontend Developer         Tech   Islamabad   Senior (6+ yrs)      260000
12      DevOps Engineer         Tech     Karachi  Junior (0-2 yrs)       80000
13      DevOps Engineer         Tech      Lahore     Mid (3-5 yrs)      160000
14      DevOps Engineer         Tech   Islamabad   Senior (6+ yrs)      300000
15           Accountant      Finance     Karachi  Junior (0-2 yrs)       55000
16           Accountant      Finance      Lahore     Mid (3-5 yrs)       90000
17           Accountant      Finance   Islamabad   Senior (6+ yrs)      160000
18    Financial Analyst      Finance     Karachi  Junior (0-2 yrs)       65000
19    Financial Analyst      Finance      Lahore     Mid (3-5 yrs)      120000
20    Financial Analyst      Finance   Islamabad   Senior (6+ yrs)      210000
21         Bank Officer      Finance     Karachi  Junior (0-2 yrs)       60000
22         Bank Officer      Finance      Lahore     Mid (3-5 yrs)       95000
23         Bank Officer      Finance  Rawalpindi   Senior (6+ yrs)      170000
24    Marketing Manager    Marketing     Karachi  Junior (0-2 yrs)       70000
25    Marketing Manager    Marketing      Lahore     Mid (3-5 yrs)      110000
26    Marketing Manager    Marketing   Islamabad   Senior (6+ yrs)      200000
27       SEO Specialist    Marketing     Karachi  Junior (0-2 yrs)       50000
28       SEO Specialist    Marketing      Lahore     Mid (3-5 yrs)       85000
29       SEO Specialist    Marketing   Islamabad   Senior (6+ yrs)      140000
30       Content Writer    Marketing     Karachi  Junior (0-2 yrs)       40000
31       Content Writer    Marketing      Lahore     Mid (3-5 yrs)       70000
32       Content Writer    Marketing   Islamabad   Senior (6+ yrs)      120000
33        Doctor (MBBS)   Healthcare     Karachi  Junior (0-2 yrs)      120000
34        Doctor (MBBS)   Healthcare      Lahore     Mid (3-5 yrs)      220000
35        Doctor (MBBS)   Healthcare   Islamabad   Senior (6+ yrs)      420000
36           Pharmacist   Healthcare     Karachi  Junior (0-2 yrs)       65000
37           Pharmacist   Healthcare      Lahore     Mid (3-5 yrs)      100000
38           Pharmacist   Healthcare    Peshawar   Senior (6+ yrs)      180000
39                Nurse   Healthcare     Karachi  Junior (0-2 yrs)       45000
40                Nurse   Healthcare      Lahore     Mid (3-5 yrs)       70000
41                Nurse   Healthcare  Faisalabad   Senior (6+ yrs)      120000
42       Civil Engineer  Engineering     Karachi  Junior (0-2 yrs)       70000
43       Civil Engineer  Engineering      Lahore     Mid (3-5 yrs)      130000
44       Civil Engineer  Engineering   Islamabad   Senior (6+ yrs)      240000
45  Mechanical Engineer  Engineering     Karachi  Junior (0-2 yrs)       65000
46  Mechanical Engineer  Engineering      Lahore     Mid (3-5 yrs)      120000
47  Mechanical Engineer  Engineering   Islamabad   Senior (6+ yrs)      220000

In [6]:
df.rename(columns = {"Salary_PKR": "Salary"} , inplace = True)

In [8]:
df.groupby(["City" , "Job_Title"])["Salary"].mean()

City        Job_Title
Faisalabad  Nurse                  120000.0
Islamabad   Accountant             160000.0
            Civil Engineer         240000.0
            Content Writer         120000.0
            Data Analyst           220000.0
            Data Scientist         320000.0
            DevOps Engineer        300000.0
            Doctor (MBBS)          420000.0
            Financial Analyst      210000.0
            Frontend Developer     260000.0
            Marketing Manager      200000.0
            Mechanical Engineer    220000.0
            SEO Specialist         140000.0
            Software Engineer      280000.0
Karachi     Accountant              55000.0
            Bank Officer            60000.0
            Civil Engineer          70000.0
            Content Writer          40000.0
            Data Analyst            70000.0
            Data Scientist          90000.0
            DevOps Engineer         80000.0
            Doctor (MBBS)          120000.0
            Financial Analyst       65000.0
            Frontend Developer      75000.0
            Marketing Manager       70000.0
            Mechanical Engineer     65000.0
            Nurse                   45000.0
            Pharmacist              65000.0
            SEO Specialist          50000.0
            Software Engineer       85000.0
Lahore      Accountant              90000.0
            Bank Officer            95000.0
            Civil Engineer         130000.0
            Content Writer          70000.0
            Data Analyst           120000.0
            Data Scientist         160000.0
            DevOps Engineer        160000.0
            Doctor (MBBS)          220000.0
            Financial Analyst      120000.0
            Frontend Developer     140000.0
            Marketing Manager      110000.0
            Mechanical Engineer    120000.0
            Nurse                   70000.0
            Pharmacist             100000.0
            SEO Specialist          85000.0
            Software Engineer      150000.0
Peshawar    Pharmacist             180000.0
Rawalpindi  Bank Officer           170000.0
Name: Salary, dtype: float64

In [14]:
Karachi_jobs = df[df["City"] == "Karachi"]

In [17]:
Karachi_jobs["Salary"].mean()

np.float64(69062.5)

In [24]:
df.groupby("Job_Title")[["Salary"]].agg(["mean", "min" , "max"]).sort_values(by = ("Salary","mean"))

                            Salary
                              mean     min     max
Job_Title
Content Writer        76666.666667   40000  120000
Nurse                 78333.333333   45000  120000
SEO Specialist        91666.666667   50000  140000
Accountant           101666.666667   55000  160000
Bank Officer         108333.333333   60000  170000
Pharmacist           115000.000000   65000  180000
Marketing Manager    126666.666667   70000  200000
Financial Analyst    131666.666667   65000  210000
Mechanical Engineer  135000.000000   65000  220000
Data Analyst         136666.666667   70000  220000
Civil Engineer       146666.666667   70000  240000
Frontend Developer   158333.333333   75000  260000
Software Engineer    171666.666667   85000  280000
DevOps Engineer      180000.000000   80000  300000
Data Scientist       190000.000000   90000  320000
Doctor (MBBS)        253333.333333  120000  420000